### ISSUE TITLE
@ModifyVariable Mixin with @At("FIELD") does not generate refmapping

### ISSUE THREAD

**Issue by orbwoi** [FabricMC/fabric-loom#100]
Here are two very similar mixins (comment one out to try the other).
The top ModifyVariable mixin does NOT generate mappings in the refmap.
The bottom Inject mixin DOES generate mappings in the refmap.

Both work in dev env mode without obfuscation. 
I was just doing a random test to make sure i knew how to make mixins but this is crazy lol
There are no compile errors for either one.
Tested with loom 0.2.2, 0.2.3, and 0.2.4.

```
@Mixin(LightmapTextureManager.class)
public class FullBrightMixin {
    @ModifyVariable(method = "update(F)V",
                    index = 5,
                    at = @At(value = "FIELD",
                             target = "Lnet/minecraft/client/render/LightmapTextureManager;worldRenderer:Lnet/minecraft/client/render/GameRenderer;",
                             ordinal = 1))
    private float onWorldRenderAccess(float current) {
        if (DarkEyeMod.isFullBrightEnabled)
        {
            return 1.0F;
        } else {
            return current;
        }
    }
}
```

```
@Mixin(LightmapTextureManager.class)
public class FullBrightMixin {
    @Inject(method = "update(F)V",
            at = @At(value = "FIELD",
                     target = "Lnet/minecraft/client/render/LightmapTextureManager;worldRenderer:Lnet/minecraft/client/render/GameRenderer;",
                     ordinal = 1))
    private void onWorldRenderAccess(CallbackInfo info) {
        System.out.println("This line is printed by an example mod mixin!");
    }
}
```

**Comment by grondag** [comment]
This might be a problem more generally.  This mixin won't generate a remap at all if the @Inject is removed: https://github.com/grondag/clear-skies/blob/4794e030369fe57cb8d6b2936bd2a76491c5d366/src/main/java/grondag/clearskies/mixin/MixinBackgroundRenderer.java

**Comment by modmuss50** [comment]
I believe I fixed field remapping, if this is still an issue please open a new bug report.
