### ISSUE TITLE
[Bug] The datagen run config has a strange name when I use `createSourceSet`

### ISSUE THREAD

**Issue by maityyy** [FabricMC/fabric-loom#1000]
![image](https://github.com/FabricMC/fabric-loom/assets/47220489/e28dcec0-527e-4655-8126-c784fcb620f9)
And without `createSourceSet`
![image](https://github.com/FabricMC/fabric-loom/assets/47220489/a8841557-125b-4e0d-818f-f7184cecd82a)

From discord https://discord.com/channels/507304429255393322/592749519171616796/1184584733343105044

**Comment by maityyy** [comment]
for context https://discord.com/channels/507304429255393322/592749519171616796/1201481834756841512

**Comment by modmuss50** [comment]
Fixed for real this time.
