### ISSUE TITLE
Add ability to change runtime minecraft version and compile minecraft version

### ISSUE THREAD

**Issue by Jab125** [FabricMC/fabric-loom#1004]
For example, it would be useful to use 1.20.4 during runtime, whilst compiling the mod for 1.20.1 (if a mod doesn't touch modified features)

**Comment by Linguardium** [comment]
if the mod doesnt touch any modified thing, then it will work fine. compiling against identical (including dependent) code will produce the same executable

"runtime minecraft version" is controlled by fabric.mod.json
if your runtime minecraft version does _not_ match the compilation mc version and references differences in MC, then it will crash, though

**Comment by modmuss50** [comment]
You can easily do this with subprojects. Doing it within one project isnt really feasible both with how Gradle works, and it would also require a major refactor to loom.
