### ISSUE TITLE
[0.2.4] modRuntime doesn't work with local files

### ISSUE THREAD

**Issue by kgscialdone** [FabricMC/fabric-loom#101]
Not much else to say. No errors or warnings logged, any lines like the following are seemingly just ignored:
```groovy
modRuntime files("file/path/here.jar")
modRuntime fileTree(dir: "dir/path/here", include: "*.jar")
```
With a bit of finegling, CurseForge's automatic Maven repo is a decent substitute when trying to add local dev mods (and probably better in the long run anyways), but this is definitely a slight annoyance and may not be avoidable for other applications. `modCompile` does work with `files`, but not with `fileTree`, and obviously doesn't have the benefit of `modRuntime`'s runtime-only properties.

**Comment by Chocohead** [comment]
This broke merging in #96 [here](https://github.com/FabricMC/fabric-loom/commit/467b696393028c765adebef75930756e9efcb5a2#diff-1d4ad3c6fa63a89f105a284fb297f29aR53).

**Comment by nok-ko** [comment]
Was this ever fixed?

**Comment by natanfudge** [comment]
No it wasn't, apparently it's hard

**Comment by nok-ko** [comment]
I suppose we should reopen it if it's worth fixing.

**Comment by modmuss50** [comment]
Reopened, as it would be nice to get it fixed.

**Comment by kgscialdone** [comment]
@modmuss50 I closed this because I got sick and tired of receiving literal death threats and suicide encouragement over my choice of modding framework and want to erase as much evidence of my ever being involved in the Minecraft modding community as I possibly can. I want nothing to do with any of you or anything you've made, on either side of the Forge/Fabric divide. Please reopen an equivalent issue if you want to work on this and leave mine the hell out of it, or preferably delete it entirely. Thank you.
