### ISSUE TITLE
What is needed to connect to a local server using a client?

### ISSUE THREAD

**Issue by AlexeyAntivirus** [FabricMC/fabric-loom#1011]
Hi there,

I have a question regarding mod development with fabric-loom.
I downloaded a generated template, downloaded all assets, generated Minecraft source code and launched both Client and Server (via runClient and runServer respectively; they both ran successfully).

I tried to connect to a local server I ran via runServer using a client I ran via runClient, and I received an error message "Failed to log in: Invalid session". The reason is because i'm not authenticated. I tried to find in the documentation regarding how to configure a client via fabric-loom, so that I could provide my valid credentials, but no luck.

Is there any ways to give a client valid credentials via fabric-loom configuration? Or it is not supposed to do so?

Thank you in advance.

**Comment by Juuxel** [comment]
You need to set `online-mode = false` in the generated server.properties file in the run directory to disable account checking. (See more details on the [MC Wiki](https://minecraft.wiki/w/Server.properties) if needed).

**Comment by AlexeyAntivirus** [comment]
That worked! Thanks for your help.
