### ISSUE TITLE
Support for modCompileOnly

### ISSUE THREAD

**Issue by sargunv** [FabricMC/fabric-loom#102]
I'd like some way to include a mod in my build time classpath, at run time, but not in my pom. In the normal java world, I think I'd use compileOnly and runtimeOnly together for that. With loom, I don't see any way to do it. I'd love to see support for modCompileOnly to enable this.

Use case: modCompileOnly for modmenu in autoconfig so I can use its API, see it at runtime, but not have it pulled in when other mods modImplementation autoconfig.

**Comment by mattmess1221** [comment]
It's best to wrap a dependency in a method. e.g.

```gradle
dependencies {
    implementation mapped(dep) {
        // any options
    }
}
```

**Comment by falkreon** [comment]
While I can see the appeal of converting any existing/standard configuration into a mapped one, I'm not sure that's realistic. I'll leave that to the implementors to judge I guess.

We're all running into this same issue with soft dependencies leaking out to consumers.

The other thing we're missing - and this may not be possible, we may be resigned to api jars forever - is a configuration that behaves equivalent to dropping a `dev`-classified jar into the `run/mods` folder. This would allow us to test our soft dependencies from the provided `runClient` task, without exposing them in any way in an exported POM.

**Comment by modmuss50** [comment]
There is no way to do what @killjoy1221 suggested, someone was looking into doing this but struggled with the new gradle api. 

It would be great to be able to use any configuration. If anyone is willing/able to finish of the PR to move to gradle's new system, or even fix the old system the help would be appricated.

As for adding modCompileOnly it should be possible to add with the current system without too much work.

**Comment by modmuss50** [comment]
added
