### ISSUE TITLE
SelfResolvingDependency slated for deprecation

### ISSUE THREAD

**Issue by zml2008** [FabricMC/fabric-loom#1022]
This doesn't appear to be a a near term thing by any means, but per https://github.com/gradle/gradle/pull/27420, it looks like the Gradle folks are discussing deprecating `SelfResolvingDependency`, which loom appears to use for some of its mappings resolution.

Hopefully this deprecation is still a ways out, but looking ahead will hopefully make it less of a scramble at the last minute to resolve deprecation warnings :)

**Comment by modmuss50** [comment]
Thanks, its been a while since I touched this stuff, I doubt it will be too hard to move away from this. Can be something for 1.6 👍 

This should show up as all of our tests run with deprecation warnings set to fail the build.

**Comment by modmuss50** [comment]
Done, thanks for the heads up.
