### ISSUE TITLE
Fabric-loader installer.json needs a way to specify `annotationProcessor` dependencies

### ISSUE THREAD

**Issue by LlamaLad7** [FabricMC/fabric-loom#1025]
Future things in MixinExtras will use a separate artifact for the AP and the installer.json will need to support this

**Comment by modmuss50** [comment]
@LlamaLad7 is this still needed? I believe you changed the approach you are going to take, I just dont want to close this issue if it still needs some more discussion. Thanks

**Comment by LlamaLad7** [comment]
I’d still ideally like a separate AP artifact so that there doesn’t need to be unnecessary stuff in the runtime jar.

**Comment by LlamaLad7** [comment]
Not sure if that’s worth the hassle of migrating though. There’s not actually that much logic.

**Comment by LlamaLad7** [comment]
On second thoughts i’ll probably just keep the setup as-is. Keeps the dependency simpler and means people don’t need to change anything.
