### ISSUE TITLE
modCompile does not work with composite builds

### ISSUE THREAD

**Issue by mattmess1221** [FabricMC/fabric-loom#103]
[Composite Builds](https://docs.gradle.org/current/userguide/composite_builds.html)

When `modCompile` is used with a dependency defined by `includeBuild`, the configuration of the project fails when the `build` task has not been run. Temporary fix is to use `compile` instead of `modCompile` when `includeBuild` is used.

Error: https://hastebin.com/ocahamerus.cs

**Comment by natanfudge** [comment]
The Hastebin has expired.

**Comment by modmuss50** [comment]
Log is dead, I have spent a lot of time trying to support composite build without any luck. For now they wont be supported.
