### ISSUE TITLE
"...Failed to apply access wideners..." Error

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric-loom#1051]
Hi,

I want to start Fabric modding and tried to open this Fabric mod template, but the error below appears every time I open the project.

-----------------------------------------------

`Starting Gradle Daemon...
Gradle Daemon started in 1 s 181 ms

> Configure project :
Fabric Loom: 1.5.7
Found existing cache lock file, rebuilding loom cache. This may have been caused by a failed or canceled build.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'maiam-fabric-1.20.4'.
> Failed to setup Minecraft, java.io.UncheckedIOException: Failed to apply access wideners to C:\Users\***\OneDrive\Desktop\!DESKTOP!\Dateien\Others\Spiele\Minecraft\maiam-fabric-1.20.4\.gradle\loom-cache\minecraftMaven\net\minecraft\minecraft-merged-e7cf13955e\1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2\minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

CONFIGURE FAILED in 28s
`

**Comment by modmuss50** [comment]
Id reccomend not using OneDrive, its likely the cause of this issue.
