### ISSUE TITLE
 Task with name 'genIdeaWorkspace' not found in project

### ISSUE THREAD

**Issue by huanmeng-qwq** [FabricMC/fabric-loom#1057]
I am trying to use buildSrc to manage versions

buildSrc/src/main/kotlin/legacy-fabric.gradle.kts: https://mclo.gs/SThMRax

versions/v1_8/build.gradle.kts:
```kt
plugins {
    `legacy-fabric`
}
```

error: https://mclo.gs/JFeB8nn

**Comment by modmuss50** [comment]
Legacy fabric isnt an official Fabric project, so not something we provide support for.
