### ISSUE TITLE
Subproject issue

### ISSUE THREAD

**Issue by MetsukiMio** [FabricMC/fabric-loom#1062]
fabric loom is likely not supported for mod subprojects (dev client cannot launch due to remap issue)
how can I make a minecraft mod with subprojects?

**Comment by modmuss50** [comment]
Loom does support sub projects, it works almost identically to how Gradle does, however there is a bit of loom specific stuff that you need to account for here: https://fabricmc.net/wiki/documentation:fabric_loom#depending_on_sub_projects

**Comment by MetsukiMio** [comment]
Thanks, and my problem is solved by this wiki
