### ISSUE TITLE
Failure to determine game version from non-standard Yarn versions

### ISSUE THREAD

**Issue by ChloeDawn** [FabricMC/fabric-loom#107]
Failed with `java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 7` at

https://github.com/FabricMC/fabric-loom/blob/1c56fb2eda3ae4acc94d7c11e5becff935b9246d/src/main/java/net/fabricmc/loom/util/Version.java#L43

when using `mappings "com.github.SleeplessDevelopment:yarn:9c83d56"`

**Comment by modmuss50** [comment]
For now, use the standard versioning for different mappings.
