### ISSUE TITLE
[Enhancement & Fix] Avoid specifying the datagen mod id as it must be identical to the main mod id

### ISSUE THREAD

**Issue by maityyy** [FabricMC/fabric-loom#1079]
See https://github.com/FabricMC/fabric-loom/issues/999

**Comment by modmuss50** [comment]
As far as I can tell this is working as expected, what am I missing? 

Doing:

```gradle
fabricApi {
	configureDataGeneration {
		createSourceSet = true
	}
}

loom.mods.forEach {
	println it.name
}
```

Correctly prints out the modid as specified in `src/datagen/resources/fabric.mod.json`

**Comment by maityyy** [comment]
Ahh, I should have created the FMJ in the datagen sourceset? I thought that FMJ should be read from the main sourceset

**Comment by maityyy** [comment]
https://discord.com/channels/507304429255393322/592749519171616796/1220732053201616927
