### ISSUE TITLE
Repository issue

### ISSUE THREAD

**Issue by MetsukiMio** [FabricMC/fabric-loom#1082]
![image](https://github.com/FabricMC/fabric-loom/assets/83895170/c30bf4b2-5993-4810-9cf5-59344b86f51c)
I am trying to add lwjgl-treetype dependency for a submodule, and I find that gradle was trying to download treetype native libs from libraries.minecraft.com, I hope it can download it from mavenCentral()

**Comment by MetsukiMio** [comment]
project link is here: github.com/PrimogemStudio/Advanced-Framework, and this issue only appears on Linux

**Comment by Jack253-png** [comment]
project link is here: github.com/PrimogemStudio/Advanced-Framework, and this issue only appears on Linux

**Comment by modmuss50** [comment]
Mojang do not support arm64 linux, so dont put those natives on their maven, I would just not bother with these as its not like the game is going to work on that platform anyway.

If for some reason you want to work around this you can see how loom does it here for older version.: https://github.com/FabricMC/fabric-loom/blob/dev/1.6/src/main/java/net/fabricmc/loom/LoomRepositoryPlugin.java#L134-L147

This isnt a loom bug so the following also applies:

👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.

**Comment by MetsukiMio** [comment]
so how can I solve this issue in loom 1.5 ?

**Comment by MetsukiMio** [comment]
so how can I solve this issue in loom 1.5 ?

**Comment by modmuss50** [comment]
Create a new maven repo with the central URL, that sets `exclusiveContent` for LWJGL in a similar way to loom. I recommend reading: https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring_content_exclusively_found_in_one_repository
