### ISSUE TITLE
RemapJar task fails with an unhelpful error when a mixin json file is malformed.

### ISSUE THREAD

**Issue by TaxMachine** [FabricMC/fabric-loom#1103]
When I build a 1.20.1 mod I get this error from the :remapJar task
```
Execution failed for task ':remapJar'.
> A failure occurred while executing net.fabricmc.loom.task.RemapJarTask$RemapAction
   > Failed to remap, com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 30 column 4 path $.injectors.defaultRequire
```

The mod uses fabric-loom 1.2-SNAPSHOT
I have no idea if this is a fabric or an issue with the mod but there's no error in the codebase

**Comment by modmuss50** [comment]
it appears that one of your mixin json files might be invalid.

**Comment by TaxMachine** [comment]
you're right thank you. Is there a way to make those errors more readable? I don't know how it catches those errors but It'd be nice to have improved logging on this side

**Comment by modmuss50** [comment]
Yeah, that should be possible, lets keep this issue around to look into improving this 👍
