### ISSUE TITLE
Evaluate moving to gradle 5.5 new transforming dependencies 

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-loom#112]
Quick overview [here](https://docs.gradle.org/5.5-rc-1/release-notes.html#artifact-transforms)

Detailed info [here](https://docs.gradle.org/5.5-rc-1/userguide/dependency_management_attribute_based_matching.html#sec:abm_artifact_transforms)

Moving over to this should fix a lot of the current issues surrounding mod deps.

It would require forcing gradle 5.5 but I think its worth it. Next step is to make a prototype / PR to see how well this could work.

**Comment by liach** [comment]
https://docs.gradle.org/5.5-rc-1/userguide/dependency_management_attribute_based_matching.html#implementing_incremental_artifact_transforms

This is definitely extremely useful for mapping some changed yarn code to intermediary when building a mod after some tiny tweaks!

**Comment by liach** [comment]
Bored today, I tried to wrote some snippet.
```java
public abstract class TinyRemap extends Remap<TinyRemap.Parameters> {

    public interface Parameters extends Remap.Parameters {

        // use inputNamespace.set "official"
        @Input
        Property<String> getInputNamespace();

        @Input
        Property<String> getOutputNamespace();

    }

    @Override
    protected void transform(File mapping, FileCollection libraries, TransformOutputs outputs) {
        Parameters parameters = getParameters();
        String input = parameters.getInputNamespace().convention("official").get();
        String output = parameters.getOutputNamespace().convention("named").get();

        File inputJar = getInputArtifact().get().getAsFile();
        Path path = outputs.file(MoreFiles.getNameWithoutExtension(inputJar.toPath()) + "-remapped.jar").toPath();

        TinyRemapper remapper = TinyRemapper.newRemapper()
                .withMappings(TinyUtils.createTinyMappingProvider(mapping.toPath(), input, output))
                .build();
        try (OutputConsumerPath consumer = new OutputConsumerPath.Builder(path).build()) {
            consumer.addNonClassFiles(path);
            remapper.readClassPath(StreamSupport.stream(libraries.spliterator(), false).map(File::toPath).toArray(Path[]::new));
            remapper.readInputs(inputJar.toPath());
            remapper.apply(consumer);
        } catch (IOException ex) {
            throw new UncheckedIOException(ex);
        } finally {
            remapper.finish();
        }
    }
}
```
guess this can work, and i had a few other classes for attribute management as well

**Comment by modmuss50** [comment]
@liach how well did that work? would it be possible to get the project in transform? I think that was our last major issue.

Can you post a snippit showing how you set the namespaces?

**Comment by liach** [comment]
Sorry, this is like a draft (just like the mod requests in fabricord), no detail yet.

When you use transforms, you do
```gradle
dependencies {
    registerTransform(TinyRemap) {
        from.attribute(TinyHooks.MAPPING_VERSION, "1.14.4").attribute(TinyHooks.MAPPING_TYPE, "official")
        to.attribute(TinyHooks.MAPPING_VERSION, "1.14.4+build.12").attribute(TinyHooks.MAPPING_TYPE, "named")

        parameters {
            inputNamespace.set "official"
            outputNamespace.set "named"
            inputVersion.set "1.14.4"
            outputVersion.set "1.14.4+build.12"
            // set more params
        }
    }
}
```
I am planning to move such configurations to utilities in loom (utility methods that calls such a block when called) to support multiple version's remap, etc.

**Comment by liach** [comment]
Hmm, this might be a helpful example of doing artifact transform https://docs.gradle.org/6.4/samples/zips/sample_java_modules_with_transform-groovy-dsl.zip

Seems the plugin should take care of most of the transform.

**Comment by modmuss50** [comment]
I believe we have looked into this but it has some major shortfalls that currenly block us from doing so.

**Comment by Juuxel** [comment]
I experimented with this a few months ago. The main issue is that you can't request attributes for transitive dependencies (or alternatively, a configuration as a whole), but only for explicitly declared ones.

This *could* be done if all mods were published with Gradle module metadata requesting a remapping attribute, but that seems like too much ecosystem work - it'd need new releases of all Maven artifacts. (Also, module metadata can't be published at all currently since Loom breaks software components)
