### ISSUE TITLE
Decompiler cache doesn't work with Mojang mappings

### ISSUE THREAD

**Issue by VelizarBG** [FabricMC/fabric-loom#1121]
Reusing the decompiler cache for sources mapped with Mojang mappings doesn't work. This might have something to do with cached classes being mapped in obfuscated ProGuard mappings, instead of Mojang mappings.

[Here](https://paste.gg/p/anonymous/7d6116cd00bd49f7b64c44fab1102141/files/5748e3ed40bc435f9f6f69bab92576aa/raw) is the stacktrace.

## Steps to reproduce
0. Delete your decompiler cache.
1. Clone the [reproduction repo](https://github.com/VelizarBG/decompilercachetest).
2. Checkout the `1.20.6-mojmap` branch.
3. Run `gradlew genSourcesWithVineflower --use-cache`
4. Run `gradlew genSourcesWithVineflower --use-cache --full-stacktrace`

**Comment by VelizarBG** [comment]
@modmuss50 The error is gone but the cached classes still get saved with obfuscated mappings.

**Comment by modmuss50** [comment]
> @modmuss50 The error is gone but the cached classes still get saved with obfuscated mappings.

Im not 100% sure what you mean? Can you try running `build --refresh-dependencies` and see if that helps?

What does you build.gradle look like, im testing with:

```gradle
loom {
	noIntermediateMappings()
}

dependencies {
	minecraft "com.mojang:minecraft:1.20.4"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
}
```

**Comment by VelizarBG** [comment]
Hmm, `--refresh-dependencies` seems to have gotten rid of the issue(basically almost every class used to be obfuscated). You can see my build.gradle in the branch from the reproduction repo linked in the steps for reproduction above. Anyway, thanks for fixing this!

**Comment by modmuss50** [comment]
Awesome, I think what happened was it had cached a broken copy of the jar from an older loom version. Im glad its working now. Have fun 👍
