### ISSUE TITLE
Fabric in the subproject is incompatible root project kotlin plugin with Kotlin 2.0.0

### ISSUE THREAD

**Issue by bluegreensea** [FabricMC/fabric-loom#1122]
About: https://github.com/FabricMC/fabric/issues/3788

When kotlin plugin is in the fabric subproject is also fine, but failed in this situation

Here is a simple project to test: [test.zip](https://github.com/FabricMC/fabric-loom/files/15402478/test.zip)

**Comment by modmuss50** [comment]
As I said in the first issue you are not applying the plugins correctly as detailed in the gradle docs here: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl

Once I make that change the project you provided works as expected.

build.gradle.kts:
```gradle
plugins {
    kotlin("jvm") version "2.0.0"
    id("fabric-loom") version "1.6-SNAPSHOT" apply false
}
```
fabric/build.gradle.kts:
```gradle
plugins {
    id("fabric-loom")
}
```
settings.gradle.kts:
```gradle
pluginManagement {
    repositories {
        mavenCentral()
        maven("https://maven.fabricmc.net") { name = "Fabric" }
    }
}

rootProject.name = "Test"

include("fabric")
```

You MUST have all the projects defined in the root project, even if they arent applied.
