### ISSUE TITLE
Remapped dependencies have no sources attached

### ISSUE THREAD

**Issue by thecodewarrior** [FabricMC/fabric-loom#114]
It seems remapped mods (fabric api included) lose their source attachments. This is reasonable, but is a significant inconvenience when trying to, for example, figure out how to register a resource reload listener. Without the ability to search for methods that accept a `ResourceReloadListener` argument the only other options are to manually browse through the class list until you see something interesting or try and guess what the method name would be so you can search that.

If nothing else it would be very helpful if loom could try to decompile the remapped jars and attach those as sources.

[Here's a project that manifests this issue](https://github.com/FabricMC/fabric-loom/files/3318850/fabric-example-multiproject.zip)

**Comment by JamiesWhiteShirt** [comment]
This is likely an issue with the IDE integration. For me at least, source jars are downloaded and remapped as they should, they just have to be attached manually in IntelliJ.

**Comment by modmuss50** [comment]
I believe this was all sorted with the latest idea update along with some changes I did in a newer loom version. please open a new issue if its still an issue.
