### ISSUE TITLE
`ServerLifecycleEvents` not triggered for datagen

### ISSUE THREAD

**Issue by solonovamax** [FabricMC/fabric-loom#1145]
When using datagen in a dev env, `ServerLifecycleEvents` are not triggered.

This can cause issues with mods/apis that, for example, rely on `ServerLifecycleEvents.SERVER_STOPPING` to clean up some resources.

As an example, I ran into this issue with AzureDoom/AzureLib#62, where a thread executor is spawned in non-daemon mode, and will be closed down when the `ServerLifecycleEvents.SERVER_STOPPING` event is emitted.
However, since it is never emitted, this causes the datagen to never exit, as the jvm sees that there's an active thread that is not marked as a daemon thread.

Should `ServerLifecycleEvents.SERVER_STOPPING` be emitted when the datagen finishes, or should it be added to the docs to not use it for cleaning up resources, as it can fail during datagen?

**Comment by apple502j** [comment]
I believe `SERVER_STOPPING` should always be used in conjunction with `SERVER_STARTING`. And in any case, this is not a Loom issue.

**Comment by modmuss50** [comment]
Neither of these should be fired during data generation. If the starting one is then it's a bug. (Report it to FabricAPI) I would almost always create your threads as daemons, Minecraft doesn't really have much of a concept of shutting down beyond saving the world. The essayist way to clean everything up is to close the entire process.

**Comment by solonovamax** [comment]
wait I just realized I opened this on the wrong repo lmao 💀

**Comment by solonovamax** [comment]
I moved the issue over to the fabric api repo, and also updated it to indicate that a documentation change is desired, rather than a code change.
