### ISSUE TITLE
make Providers Singletons

### ISSUE THREAD

**Issue by NikkyAI** [FabricMC/fabric-loom#115]
I think this is the best approach to cleaning up loom and make atrifact transformations work relaibly using gralde 5.5 features
(might also make submodules and differing mc versions and mappings across submodules possible)

the MappingsProvider, MinecraftProvider, MinecraftMappedProvider
would be `static` Singletons, eg. one instance across all projects

all access has to pass along mc version, mappings, and the like
that makes it possible to pass selective data through the `TransformParameter` and have caching work properly 
(one parameter as input that is the loom version, to make sure you never have old broken transforms lurking around)

Do you think this is a good idea? 
i think this would allow to clean up code a lot
and it can be introduced before all the other gradle 5.5 features

**Comment by asiekierka** [comment]
Mind that these would also be cached across *daemons*.

**Comment by modmuss50** [comment]
Yeah, there was a few reasons I did it this way.

One way to try a fix the major issues with had with deamons before, and right now it works well with sub projects.

I can see a change like this bringing back some issues we had in the past.

**Comment by NikkyAI** [comment]
well currently they are accessed using the project
and with transform actions that will just not work.. transforms do not have access to the project or extensions, using a project ion there is rolling dice (may be the right one or not)

also even if they are cached in the daemon.. as long as the inputs are complete then the resulting mappings or remapped jars are fine to be cached in the daemon i hope

**Comment by modmuss50** [comment]
In 0.5 there is a shared caches option that basicly does what you are asking for.
