### ISSUE TITLE
Compatibility with Gradle 8.5 Java 21 for Minecraft 1.21

### ISSUE THREAD

**Issue by ErythroCraft** [FabricMC/fabric-loom#1151]
Minecraft 1.21 is using Java 21 64bit

https://docs.gradle.org/current/userguide/compatibility.html#java

Can you give an Version compatible with Gradle 8.5 ?

THX

**Comment by ErythroCraft** [comment]
Bug on my compiling test

    Failed to apply plugin class 'net.fabricmc.loom.bootstrap.LoomGradlePluginBootstrap'.
    You are using an outdated version of Gradle (8.5). Gradle 8.8 or higher is required.

**Comment by modmuss50** [comment]
No, sorry please update to Gradle 8.8 or use an older Loom version. Its not feasible for us to test and maintain Loom for many old Gradle versions, there should be no reason why you cannot update.

**Comment by ErythroCraft** [comment]
Older Loom versions are using Gradle 8.3 not 8.5

8.3 is running with Java 17. That means Minecraft 1.20.x

**Comment by modmuss50** [comment]
I don't understand the problem? Why can you not update Gradle?
