### ISSUE TITLE
Can't be found in any repository

### ISSUE THREAD

**Issue by AKIT0M0YA** [FabricMC/fabric-loom#1165]
Here's my repository setup

repositories {
	mavenCentral()
	maven {
		name = "Fabric"
		url = "https://maven.fabricmc.net/"
	}
	maven {
		url = "https://repo.spongepowered.org/repository/maven-public/"
	}
	maven { url 'https://maven.aliyun.com/repository/google' }
	maven { url 'https://maven.aliyun.com/repository/public/' }
}

Here's my plugins setup

plugins {
	id 'fabric-loom' version '1.7-SNAPSHOT'
	id 'maven-publish'
}

Sometimes it works and downloads, but today neither my old project nor my newly created project can get the plugin properly
![image](https://github.com/user-attachments/assets/b5f4d570-6791-4d09-8909-d84dd64c801f)

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
