### ISSUE TITLE
Fabric Loom builds erroneous binaries for maven publication

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric-loom#117]
Using the fabric example mod, I found that the default built jars are the dev jar (in yarn mappings) and the sources jar (in intermediary mappings).

I believe it's supposed to build both jars (regular jar and sources jar) in intermediary mappings.

Steps of replication:
1. Clone fabric example mod
2. Run `./gradlew publishToMavenLocal`
3. Check `.m2/repositories/net/fabricmc/fabric-example-mod` for the built artifacts
4. Open both artifact (jar) with jd-gui, observe the yarn name of `MinecraftClient` in the example mixin in the dev jar and the intermediary name in the example mixin in the sources jar.

**Comment by liach** [comment]
Update: this issue does not appear in fabric api, which uses loom 0.2.3.

**Comment by modmuss50** [comment]
API uses 0.2.5

**Comment by liach** [comment]
I just discovered that it's because loom is setting the jar task's classifier to "dev" after project evaluation, which would override the settings from buildscript itself.

**Comment by modmuss50** [comment]
Is there an issue here then, I dont really follow what the issue is?

try running build before publishing?

**Comment by liach** [comment]
This is the criminal. https://github.com/FabricMC/fabric-loom/blob/91c150c7e76182be1ab211330decb9073b4499dc/src/main/java/net/fabricmc/loom/AbstractPlugin.java#L334

**Comment by modmuss50** [comment]
Yes, thats correct, as that jar is the dev jar.

**Comment by liach** [comment]
Maybe we can only set the classifier when there is no classifier present?

**Comment by modmuss50** [comment]
If you want to set the classifier you need to do it in afterEvaluate

**Comment by liach** [comment]
Thanks for closing this forgotten issue!

**Comment by modmuss50** [comment]
Is this still an issue? I didnt think it was?

**Comment by liach** [comment]
I don't think I ever experienced it after like 0.2.6, which is years ago.
