### ISSUE TITLE
Unable to handle module-info.class dependency

### ISSUE THREAD

**Issue by Stardito** [FabricMC/fabric-loom#1172]
## Gradle Setting
``` gradle
plugins{
    id("fabric-loom") version "1.7-SNAPSHOT"
}

dependencies {
    implementation("io.ebean:ebean:15.5.0")
    // Other Deps...
}
```

## Issues Describe
I am using ebean to handle the database, but ebean is based on module info to handle its sub dependencies. Fabric room does not seem to parse during build, resulting in the generated jar being just a useless jar package containing module info. class. Running it will lose the class, and it is confirmed that the project code can run normally in runServer Task, which is a packaging issue

**Comment by Linguardium** [comment]
implementation adds it to your run environment

you seem to want to use shadow as well to pull in its dependencies as well in your built jar 

I believe this is not a loom issue but an understanding issue

**Comment by Stardito** [comment]
> implementation adds it to your run environment
> 
> you seem to want to use shadow as well to pull in its dependencies as well in your built jar
> 
> I believe this is not a loom issue but an understanding issue

Oh, yeah. It's my problem. I'm very sorry, and I saw ebean in the final shadow file. I will close this issue
