### ISSUE TITLE
Loom 1.7 causes minecraft to not get remapped

### ISSUE THREAD

**Issue by IThundxr** [FabricMC/fabric-loom#1173]
This happened somewhere between 1.6.12 and 1.7.0-alpha.2

Only changes to the example mod were:
- Switching to mojmap + parchment via layered mappings
- Importing the porting lib base module

[Loom-1.7-Test-Mod.zip](https://github.com/user-attachments/files/17006724/Loom-1.7-Test-Mod.zip)

**Comment by modmuss50** [comment]
Does this happen without parchment? I think the issue might be becuase you are trying to layer mojmap ontop of parchment.

Please try with:

```
	mappings loom.layered {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-$minecraft_version:$parchment_version@zip")
	}
```

**Comment by modmuss50** [comment]
Tested myself and it was due to you trying to layer mojmap onto parchment. This has nothing to do with the library mods, removing those had no effect. Fixed by using my example as shown in the parchment documentation: https://parchmentmc.net/docs/getting-started
