### ISSUE TITLE
Support Java 23

### ISSUE THREAD

**Issue by DrMrBepis-hub** [FabricMC/fabric-loom#1175]
So it's kind of in the title, when I run the above line it gets to about 30% and then hit me with 
 
What went wrong:
Execution failed for task ':genSourcesWithVineflower'.
> Failed to decompile, org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk-23\bin\java.exe'' finished with non-zero exit value 1

I cannot seem to find an issue like this so Im putting it in here.

I'm using: Fabric Loom: 1.7.4
d
![FAILURE](https://github.com/user-attachments/assets/4a0942d3-2881-4d1b-9f55-b5dcc47f2ab6)

**Comment by modmuss50** [comment]
We dont yet support Java 23, we are waiting on a new version of the ASM library.

**Comment by DrMrBepis-hub** [comment]
> We dont yet support Java 23, we are waiting on a new version of the ASM library.

Is this why Im getting this issue, or is it you just cannot help yet?

**Comment by modmuss50** [comment]
Yes, you are using Java 23, I would suggest using Java 21 LTS. I will keep this issue open to keep track of Java 23 support.

**Comment by DrMrBepis-hub** [comment]
Oh my god, thank you so much <3

**Comment by derklaro** [comment]
FYI asm 9.7.1 was published this morning 🎉

**Comment by modmuss50** [comment]
ASM is now updated.
