### ISSUE TITLE
FabricItemSettings doesnt exist

### ISSUE THREAD

**Issue by DrMrBepis-hub** [FabricMC/fabric-loom#1176]
So my issue with adding a new custom sword is that when I try to copy other people (mainly KaupenJoe), they all do FabricItemSettings, unfortunately it only gives me the option to do FabricItem.Settings and that completely screws me over.

This is what Im trying to do but I get stuck on it.

public static final Item GREATSWORD = registerItem("greatsword", new FabricItem.Settings());

NOTE: I have the json file, textures and everything else BUT the actual ITEM in the ModItems folder...

**Comment by Juuxel** [comment]
`FabricItemSettings` was an obsolete subclass of vanilla's `Item.Settings` that was removed in Fabric API's 1.20.5 port. You can just replace it with `Item.Settings`. (`FabricItem` is a separate thing.)

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
