### ISSUE TITLE
Incorrect location of launch.json for vscode task

### ISSUE THREAD

**Issue by Lassebq** [FabricMC/fabric-loom#1186]
After updating to loom 1.8.3. `./gradlew vscode` generates run config in the incorrect directory. The correct path for launch.json is `${projectDirectory}/.vscode/launch.json` but instead it gets output to `${projectDirectory}/vscode/launch.json`, which is not resolved by vscode so I don't see any new run configurations.

**Comment by Juuxel** [comment]
Seems to have been broken in 543e49dfe0fc871be7ea13dabb3be574ddaa5f79, should be a one-line fix:
https://github.com/FabricMC/fabric-loom/blob/8c2d5525e8cca7e0c6445e9e6940eda940567936/src/main/java/net/fabricmc/loom/task/GenVsCodeProjectTask.java#L76
