### ISSUE TITLE
How to customize the LWJGL version and the ‘run’ directory

### ISSUE THREAD

**Issue by LovelyCane** [FabricMC/fabric-loom#1198]
I put the Sodium mod into the mods folder.
After running it in IDEA, an error occurred:

**[20:09:06] [main/ERROR] (Sodium-EarlyDriverScanner) The game failed to start because the currently active LWJGL version is not compatible. Installed version: 3.3.2-snapshot. Required version: 3.3.1. You must change the LWJGL version in your launcher to continue. This is usually controlled by the settings for a profile or instance in your launcher.**

So, how do I customize the LWJGL version?
And I want to customize the location of the 'run' folder.

**Comment by LovelyCane** [comment]
And I want to use Java 21.

**Comment by modmuss50** [comment]
Loom is upgrading your LWJGL to work with Java 21, you cannot have have LWJGL 3.3.1 and Java 21 it wont work. Using Java 17 will solve this.

The loom wiki page shows how you can change the run dir (search for runDIr): https://fabricmc.net/wiki/documentation:fabric_loom

**Comment by dicedpixels** [comment]
You can force disable the check from Sodium using `-Dsodium.checks.issue2561=false`

Ideally you should be using the correct Java version like modmuss said.

**Comment by LovelyCane** [comment]
Thank you for your responses.
Afterward, I tried using other launcher to run Sodium with Java 21 and LWJGL 3.3.1, and it seemed to work without immediate errors.
Additionally, I modified fabric-loom to forcibly use LWJGL 3.3.1 on Java 21, and although LWJGL warned about an unsupported JNI version, it has not caused any errors so far.

**[22:07:32] [main/INFO] (FabricLoader) Loading 61 mods:**
        ......
	**- java 21
	- sodium 0.5.11+mc1.20.1**

**[22:07:32] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.20.1 with Fabric Loader 0.16.7
......
[22:07:46] [Render thread/INFO] (Minecraft) Backend library: LWJGL version 3.3.1 SNAPSHOT
......
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.**

**Comment by modmuss50** [comment]
If you run with debugging or preview features enabled it will likely crash.
