### ISSUE TITLE
[0.2.5] Own mod not added when using runClient/runServer

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric-loom#123]
When using runClient / runServer gradle tasks the mod currently being developped isn't added to the game when ran. A similar issue was happening in loom 0.2.4 before https://github.com/FabricMC/fabric-loom/commit/25b9a640c23513e5504561bfc3c77926c94793b9

**Comment by modmuss50** [comment]
I forgot to pull the commit over, fixed with https://github.com/FabricMC/fabric-loom/commit/927c3f22cc1be1c32b1c7446a3dd43ea386dce02
