### ISSUE TITLE
Why do you downgrade this project's gradle to 4.9?

### ISSUE THREAD

**Issue by forestbat** [FabricMC/fabric-loom#127]

**Comment by modmuss50** [comment]
It will still run on newer gradle versions. What is the issue you are having?

**Comment by forestbat** [comment]
> 
> 
> It will still run on newer gradle versions. What is the issue you are having?

When I'm building fabricloom's environment，cmd told me ProjectLayout is deprecated and recognized me to use ObjectFactory，I want to make some change and then I found gradle in this project has been downgraded by yourself，so I want to ask why.

**Comment by liach** [comment]
According to ac9c7fc1037721c9a8734f7e1c7db61de598ddc0, the downgrade is to fix the classifier on the default remap jar task.

**Comment by modmuss50** [comment]
No that’s not why.

It was upgraded to 5.5 to allow us to possibly use some of the new features but that was put on hold for now so it was downgraded again. There shouldn’t be any issue with this as it will work from 4.9 all the way up.
