### ISSUE TITLE
Improper plugin id

### ISSUE THREAD

**Issue by AntyMew** [FabricMC/fabric-loom#128]
Currently the plugin id is simply "fabric-loom". However, according to the [Gradle docs](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:creating_a_plugin_id), the id should be "fully qualified in a manner similar to Java packages (i.e. a reverse domain name)", i.e. "net.fabricmc.fabric-loom".

Leaving this unresolved could create issues in the future if, for whatever reason, somebody else uses the fabric-loom project name. Forcing the group name to "net.fabricmc" doesn't work in all cases, like, for example, a Gradle Kotlin DSL, where colons are not allowed in an id specified in `plugins { ... }`.

...that said, I understand if you close this issue as won't-fix. It's a change which breaks a lot of mod dev environments, and sometimes conformity isn't worth it. I just figured it's better to bring it up now rather than later, when it may be even more consequential to resolve.

**Comment by ramidzkh** [comment]
It wouldn't break unless you have a repository for plugins which provides an artifact with the `fabric-loom` group and the `fabric-loom.gradle.plugin` artifact id. I would say at that point you *want* it to break.

**Comment by natanfudge** [comment]
Doesn't maven-publish do the same thing?

**Comment by modmuss50** [comment]
This is a none issue I believe as we publlish to our own repo.
