### ISSUE TITLE
Support for alternate mappings systems

### ISSUE THREAD

**Issue by LemmaEOF** [FabricMC/fabric-loom#130]
This has to be talked about sometime, so I'm gonna make an issue. We need some way to choose what mappings a project will use in development and production. Currently, we just have a `mappings` dependency, but that only works with Yarns from the official Fabric maven. It doesn't have support for MCP, NMS (though why would you ever use that), or Mojang official mappings (which I'm gonna refer to as mojmap until someone gives me a better name), or Yarn forks. Since Mojmaps aren't coming out for anything below 1.14.4, we should definitely think about what to do to support older versions of Minecraft, along with anyone using alternative mappings for any other reason.

There are currently three formats mappings come in:
- Mojmap `.txt` files from the launcher metadata
- Yarn `.tiny` sets from a maven
- MCP `.csv` files from mcpbot

How best can we deal with supporting each of these?

**Comment by quat1024** [comment]
Being able to compose and flip mappings entirely within Loom would be very useful in this new landscape. Composition, especially, would allow you to download param-LVT-only mappings from someone's maven and apply them on top of mojang mappings

**Comment by liach** [comment]
Need some work for tiny remapper, I guess.

**Comment by LemmaEOF** [comment]
It looks like the work on tiny [has been PR'd](https://github.com/FabricMC/tiny-remapper/pull/13), thanks for getting on that liach

**Comment by modmuss50** [comment]
For loom I thought about making it have a basic api that would allow other mapping formats to be added.

Right now the mappings are pulled right from maven so it will require a little bit of work to allow none maven locations. Without breaking existing build scripts. Finding out what things would be needed is quite important.

I’m busy for a few days but I don’t mind looking into creating a pull request to get some feedback on this.

**Comment by modmuss50** [comment]
Im burnt out on this, its a lot of work for little to no gain. Mainly due to it being unclear if you can even use Mojangs names in your code.

Im gonna leave this open for someone else to look at, sorry for failing.

**Comment by liach** [comment]
I agree. Dependency transformation, etc. are more important.

**Comment by modmuss50** [comment]
This is now possible.
