### ISSUE TITLE
Gradle 6.0 compatability (future)

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric-loom#131]
Loom is currently using ProjectLayout.fileProperty() which will be removed in Gradle 6.0 I suggest we move to using `project.getObjects().fileProperty()` which is what gradle currently recommends. Whilst `.getObjects()` is included in Gradle 4.0, `.fileProperty()` was added in Gradle 5.0 so may break some build scripts using older versions of gradle.

https://github.com/FabricMC/fabric-loom/blob/91c150c7e76182be1ab211330decb9073b4499dc/src/main/java/net/fabricmc/loom/task/RemapJarTask.java#L57

**Comment by liach** [comment]
we can consider dropping 4, i guess, or just move to 5.6 for dependency remap

**Comment by modmuss50** [comment]
Until someone can get the dep remapping actually working 4 will still be the target
