### ISSUE TITLE
Loom attempts to download bad macOS natives

### ISSUE THREAD

**Issue by octylFractal** [FabricMC/fabric-loom#134]
This is the same issue as ForgeGradle had a while back: https://github.com/MinecraftForge/ForgeGradle/issues/520

Stacktrace from Gradle (repeated many times): https://gist.github.com/kenzierocks/6016916c3f2ac78902d4272666ee8ac0

**Comment by modmuss50** [comment]
Should be fixed in loom 0.2.6, you may need to regnerate your run configs.
