### ISSUE TITLE
Loom handles refmaps in dev when using gradle as the build/run environment 

### ISSUE THREAD

**Issue by DeadlyMC** [FabricMC/fabric-loom#136]
Regardless of whether switching to IDEA for build and run environment, loom shouldn't be pulling in the refmap when using gradle as the environment, it should never be handling refmaps in-dev.
It generated the refmap in `build/` in my case. 
Changing to Intellij IDEA for build and run fixed the issue.

**Comment by modmuss50** [comment]
humm, the reason this happens is becuase we apply the mixin annotation processor to gradles java task. Shoudl be possible to fix this.

**Comment by modmuss50** [comment]
Im unsure on what the issue is here, the latest mixin update had improves around this. Open a new issue if there is still something wrong.
