### ISSUE TITLE
Musings on a new Loom

### ISSUE THREAD

**Issue by asiekierka** [FabricMC/fabric-loom#142]
This is a brief draft of where I wanted to take Loom with certain future private projects in mind. Already talked to modmuss about this once, but haven't had time to take it anywhere. No ETA (assuming I'll ever get involved again), but help is absolutely welcome.

The new Loom would take the role of where Loom and Stitch combined stand now. In essence, it'd be based around a submodule build system with a backend-frontend split; the "backend" would be a set of libraries exposing desirable functionality (decompilation with line number remapping, JAR merging, Mixin management, etc.), whereas the "frontends" would be the various tools built on top.

In general, the MVP would involve three key components:

* "lib" - the library modules comprising Loom;
* "cli" - the CLI interface for Loom's functionality; this is where "Stitch" stands now;
* "gradle" - the Gradle plugin exposing Loom's functionality; this is where "Loom" stands now.

This way, "lib" could be adapted to other build systems and even used (in its parts) in various other projects, while also ensuring a common set of interfaces and tools used by "cli" and "gradle" without the current hackiness of it all. "lib" would try not to make any assumptions where avoidable; this is because I wanted to adapt Loom's functionality to non-Fabric workspaces. For "gradle", the jury is out - we can always write another Gradle frontend, or even multiple.

**Comment by liach** [comment]
I'd move some loom logic into stitch. Note that loom and loader both can be minecraft-agnostic or even mapping agnostic parts, while stitch largely deals with minecraft/mappings.

**Comment by Player3324** [comment]
Dependency handing is a feature gradle appears to only handle superficially and it's also the primary gap enduser-side in a gradle-less setup. It simply can't handle multiple versions of the same library in a reasonable way, which happens all the time with a modular approach as encouraged by us.

Stitch is a pretty big mess, it needs some re-engineering before considering to add more features...

**Comment by asiekierka** [comment]
As I said - the general idea I have in mind here is to expose all of those features scattered across various modules (mostly exposed via Loom and Stitch currently) in a library with a stable, coherent Java API, and later build frontends to it for whatever we need instead of, say, calling internal Stitch classes from Loom as happens right now.

**Comment by liach** [comment]
Much of the cli can be moved to gradle (as most of them are used by loom gradle tasks and yarn, both of which have gradle in their buildscript classpath). Without gradle, some interfacing (like input arguments, etc.) are bit complex to handle (like in the cli)

**Comment by dblsaiko** [comment]
I like this. That way it can also be somewhat easily adapted for other build systems, I assume, like sbt or that build tool I'm totally never going to finish.

**Comment by modmuss50** [comment]
Closing this as I dont think a rewrite is a good idea, I am slowly cleaning up the code and updating parts to be more inline with the new gradle standards. I dont think a rewrite is really needed anymore, there are just some isolated issues that can be fixed on their own.
