### ISSUE TITLE
Sources jar sometimes (in lambdas?) contains unmapped names 

### ISSUE THREAD

**Issue by natanfudge** [FabricMC/fabric-loom#149]
Just take a look at `fabric-registry-sync-v0`'s `net.fabricmc.fabric.impl.registry.FabricRegistryClientInit` with an attached source jar. 
![image](https://user-images.githubusercontent.com/25990014/68980448-2fecd700-0809-11ea-84a0-727ec5338f38.png)

**Comment by Juuxel** [comment]
Some other examples:
- fabric-commands-v0: MixinMinecraftDedicatedServer, `method_3734().method_9235()` (inside lambda)
- fabric-containers-v0: `ScreenProviderRegistryImpl.init`, some stuff inside a lambda
- fabric-dimensions-v1:
  - FabricDimensionInternals.changeDimension, `method_3777` (inside assert)
  - FabricDimensionClientInit.onClientInit, `class_2487 compound = buf.method_10798();` (inside lambda)
  - MixinPlayerManager.onPlayerConnect, `method_3724` (**not** inside lambda, inside an `@Inject` method)

**Comment by natanfudge** [comment]
The problem is related to the minecraft jar generated by 0.2.6 loom

**Comment by natanfudge** [comment]
Only happens when the minecraft jar uses v2 mappings

**Comment by natanfudge** [comment]
OK. The last 2 comments were lies. While I tested those, I forgot to attach the source jar.
This problem happens in Loom 0.2.5, with an empty local and global cache!

**Comment by modmuss50** [comment]
Seems fixed with: https://github.com/FabricMC/fabric-loom/commit/f529c6e01e57c0f88c9d85ecf51d19b2b41102cc

![](https://s.modm.us/Code_2020-06-01_12-26-59.png)
