### ISSUE TITLE
Sources don't match class bytecode

### ISSUE THREAD

**Issue by Draylar** [FabricMC/fabric-loom#150]
**Version:**
  - Fabric API 0.4.13
  - Fabric Loader 0.7.1
  - Minecraft 1.15-pre1
  - Yarn 3:v2
  - Loom 0.2.6
  - IDE: IntelliJ

In certain classes, I get the following error near the top of the screen:
![image](https://user-images.githubusercontent.com/17728338/69461053-4d56ff00-0d3b-11ea-813f-9cfc2463eb2a.png)
("_Library source does not match the bytecode for class XYZ_").

Sources:
![image](https://user-images.githubusercontent.com/17728338/69461259-bb032b00-0d3b-11ea-9655-dab251a7bbc7.png)

This is after running genSources, letting it fully complete, and then attaching said sources. This prevents me from adding breakpoints to several classes, makes some breakpoints stop at the wrong line, and stops me from viewing certain objects and method parameters. I can also confirm this happened on 19w46b.

**Comment by modmuss50** [comment]
This has been fully fixed in loom 0.2.7 and idea 2020.1
