### ISSUE TITLE
Allow more granularly setting nested dependencies

### ISSUE THREAD

**Issue by natanfudge** [FabricMC/fabric-loom#159]
Right now I have a setup where I publish 2 variants of jars:
- One without dependencies (modpack)
- One with dependencies (standalone)

Now I would like to extract a module out of my mod to be used in another one. There's not much point distributing the module because it will likely only be used by me. So what I would like to do is include it in _both_ variants. However, if I set `addNestedDependencies` to `true`, all dependencies will be added, and if I set it to false, none of them will be added. I need a way to include _only_ the one shared module. 
I think the best way of going about these is having a `forceAddNestedDependencies` (or a better name if you can think of one) on the `RemapJarTask` that is a list of `archivesBaseNames` that will be included even when `addNestedDependencies` are true.

**Comment by modmuss50** [comment]
You can now set the nested deps per remapJar task.
