### ISSUE TITLE
[0.2.6] Loom seems to take issue with a dependency whose version is 0.1.2-alpha

### ISSUE THREAD

**Issue by RedstoneParadox** [FabricMC/fabric-loom#161]
Long story short, I released version 0.1.2-alpha of Oak Tree on both github and my own maven repo and when trying to pull from either of those places (github via JitPack) Loom/Gradle did not attempt to download the JAR file but instead downloaded the pom file. I did get it through the maven but was unable to generate sources as loom/gradle told me it couldn't find the JAR file. Even attempting to pull it from my Maven after having deleted the jar file did not cause Loom to fail.

Strangely, it has no problem with versions 0.1.1-alpha or 0.1.3-alpha, the latter of which I discovered after re-uploading the 0.1.2-alpha jar under version 0.1.3-alpha.

**Comment by modmuss50** [comment]
Not heard of this, so going to close it. If its still an issue on the latest version of loom please reopen.
