### ISSUE TITLE
Remapped mod dependencies with classifiers are broken

### ISSUE THREAD

**Issue by Pyrofab** [FabricMC/fabric-loom#162]
**Description:**
When using `modCompile/modImplementation/modApi` on an artifact with a classifier, Loom puts the yarn suffix after the classifier. Gradle thus interprets the resulting dependency as one with the same group, name and version as the original (but a different classifier). As a result, Gradle tries to retrieve that remapped dependency from the same repository as the original, fails to find it, and crashes (the Idea plugin even throws an AssertionError). 

**Logs:** https://gist.github.com/Pyrofab/e4671f108b03a8cd8e424daa8c1f6d2c

**Comment by SelfMadeSystem** [comment]
I have this issue too! As a result jitpack, WorldEdit, and other mods can't be used as dependencies. (I think)

**Comment by modmuss50** [comment]
Loom has a test for this, I believe its working as expected now.
