### ISSUE TITLE
Sources for mod dependencies with classifiers are broken

### ISSUE THREAD

**Issue by TwilightFlower** [FabricMC/fabric-loom#164]
Mod dependencies with classifiers work now, but the source remapping does not. A sources jar with the correct filename does exist, but two errors occur: 1. the source attached by default is the jar without the classifier and 2. the jar with the classifier contains the source for the non-classifier version. (if you depend on `x.y.z:something:1.0.0:api` the `something-1.0.0-api@yarnversion-sources.jar` will contain the sources for `x.y.z:something:1.0.0`.) Likely related to #162.

**Comment by modmuss50** [comment]
If this is still an issue with the latest loom version please open a new issue.
