### ISSUE TITLE
gradlew build failed

### ISSUE THREAD

**Issue by MineYuanlu** [FabricMC/fabric-loom#176]
![图片](https://user-images.githubusercontent.com/38997444/73741213-bf5cb300-4784-11ea-9600-6aab1ced3a86.png)
![图片](https://user-images.githubusercontent.com/38997444/73741257-cdaacf00-4784-11ea-9a7f-32f8416ac58c.png)
![图片](https://user-images.githubusercontent.com/38997444/73741270-dbf8eb00-4784-11ea-8c2e-31765cbff9b2.png)
I download this project and import to eclipse, but it doesn't work

**Comment by MineYuanlu** [comment]
gradlew.bat downloadAssets

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\data\yuanlu\java\项目\fabric-yuanlu-test\build.gradle' line: 2

* What went wrong:
Plugin [id: 'fabric-loom', version: '0.2.6-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/5.5.1/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (could not resolve plugin artifact 'fabric-loom:fabric-loom.gradle.plugin:0.2.6-SNAPSHOT')
  Searched in the following repositories:
    BintrayJCenter
    Fabric(https://maven.fabricmc.net/)
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s




gradlew.bat eclipse
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\data\yuanlu\java\项目\fabric-yuanlu-test\build.gradle' line: 2

* What went wrong:
Plugin [id: 'fabric-loom', version: '0.2.6-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/5.5.1/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (could not resolve plugin artifact 'fabric-loom:fabric-loom.gradle.plugin:0.2.6-SNAPSHOT')
  Searched in the following repositories:
    BintrayJCenter
    Fabric(https://maven.fabricmc.net/)
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by sylv256** [comment]
Mine is a similar issue, except I'm using `IntelliJ`. I've tried everything, but nothing seems to work. Please help.

Edit: How has it been 15 days since OP posted?

`./gradlew idea`
or
`./gradlew downloadAssets`
or
`./gradlew`
returns:
```js
FAILURE: Build failed with an exception.

* Where:
Build file '/home/lubuntu/camillocraft/fabric-example-mod/build.gradle' line: 2

* What went wrong:
Could not apply requested plugin [id: 'fabric-loom', version: '0.2.6-SNAPSHOT'] as it does not provide a plugin with id 'fabric-loom'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'fabric-loom' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 842ms
```
`./gradlew --warning-mode 'all' --debug --info`
```js
Initialized native services in: /home/lubuntu/.gradle/native
Found daemon DaemonInfo{pid=21644, address=[208bbeab-3589-4dac-b5d8-85a99fabf882 port:42025, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1582067629070, context=DefaultDaemonContext[uid=20964cf0-0fef-4c2f-8d67-9be0182002a1,javaHome=/home/lubuntu/idea-IC-193.6494.35/jbr,daemonRegistryDir=/home/lubuntu/.gradle/daemon,pid=21644,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-Xmx1G,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} however its context does not match the desired criteria.
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=/usr/lib/jvm/java-11-openjdk-amd64,daemonRegistryDir=/home/lubuntu/.gradle/daemon,pid=24674,idleTimeout=null,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-Xmx1G,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
Actual: DefaultDaemonContext[uid=20964cf0-0fef-4c2f-8d67-9be0182002a1,javaHome=/home/lubuntu/idea-IC-193.6494.35/jbr,daemonRegistryDir=/home/lubuntu/.gradle/daemon,pid=21644,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-Xmx1G,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]

  Looking for a different daemon...
The client will now receive all logging from the daemon (pid: 23924). The daemon log file: /home/lubuntu/.gradle/daemon/5.5.1/daemon-23924.out.log
Starting 10th build in daemon [uptime: 15 mins 54.331 secs, performance: 100%]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/home/lubuntu/camillocraft/mods/essentials/settings.gradle'.
Projects loaded. Root project using build file '/home/lubuntu/camillocraft/mods/essentials/build.gradle'.
Included projects: [root project 'essentials']

> Configure project :
Evaluating root project 'essentials' using build file '/home/lubuntu/camillocraft/mods/essentials/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/lubuntu/camillocraft/fabric-example-mod/build.gradle' line: 2

* What went wrong:
Could not apply requested plugin [id: 'fabric-loom', version: '0.2.6-SNAPSHOT'] as it does not provide a plugin with id 'fabric-loom'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'fabric-loom' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 801ms
```

**Comment by TheChilliPL** [comment]
So how to fix that?...
