### ISSUE TITLE
Add a way of modifying mappings

### ISSUE THREAD

**Issue by Runemoro** [FabricMC/fabric-loom#184]
Since there is a lot of controversy about a few yarn names (`ScreenHandler` vs. `Menu`, `Container` vs. `Inventory`, etc.), and maintaining a yarn fork as suggested in https://github.com/FabricMC/yarn/pull/1165#pullrequestreview-376146740 takes a lot of work, it would be nice to add a way to easily modify mapping names from loom. 

One way this could be done is by specifying a second mapping dependency and having loom use that, and fall back to yarn for missing names only.

Another way would be specifying a `String -> String` method in `build.gradle` which loom calls on every name to obtain a possibly transformed name. The advantage of this is that it's more flexible, since it can use regexes to automatically transform a pattern of names like `(.*)Inventory` -> `$1Container`.

Note: Adding support for mapping composition was also suggested in https://github.com/FabricMC/fabric-loom/issues/130#issuecomment-528118972.

**Comment by modmuss50** [comment]
Layered mappings is a thing now.
