### ISSUE TITLE
Access wideners on subprojects do not attach the correct jar in IDEA

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#187]
Loom: 0.2.7 build 33
IDEA: 2019.3.3

This happens when an AW is attached to a fabric-api module, for example.

**Comment by modmuss50** [comment]
I will try this again, as this was a specific thing I tested.

**Comment by Juuxel** [comment]
There seems to be a bigger issue with subprojects inheriting the root project's jar -- [a project](https://github.com/FabLabsMC/ScreenHandlers/tree/1.16-aw) with AWs in the root project and no AWs in a subproject fails to build because the subproject can't find the root project's projectmapped jar.

Log: https://github.com/FabLabsMC/ScreenHandlers/runs/564717464

**Comment by modmuss50** [comment]
A workaround for this is

```
implementation (project(':')) {
        exclude module: 'minecraft'
}
```

I will look into finding a way to fix this.

**Comment by modmuss50** [comment]
I dont think there is a way to easily fix this, doing the above work around is fine.
