### ISSUE TITLE
StackOverFlow on compile java

### ISSUE THREAD

**Issue by Stuff-Stuffs** [FabricMC/fabric-loom#189]
Simply cloned a git repo and ran gradle, this is the output;
[LOG](https://hastebin.com/qaheyinaya.http)

**Comment by liach** [comment]
Mind post your code and your java version (javac version), as that might help find the cause

**Comment by Stuff-Stuffs** [comment]
javac 1.8.0_181
Code was just example mod updated to use snapshot version of minecraft, yarn, loom and, api

**Comment by liach** [comment]
Can you try with another version of javac, like a newer update like 211/212 or that for java 11/14? javac for java 8 is known to have some bugs that aren't fixed, such as placing type annotations at wrong places

**Comment by Stuff-Stuffs** [comment]
You are correct, just tried with javac 11 and it solved the problem
