### ISSUE TITLE
Question: remapJar with "official" mappings

### ISSUE THREAD

**Issue by LeafHacker** [FabricMC/fabric-loom#191]
I have a mod that needs to target non-fabric environments, however it'd still be nice to use fabric-loom for developing it. To this end I'd like to write a JarTask that generates an `official` mapped jar complete with a `named:official` mixin refmap.

I can see fabric-mixin-compile-extensions lists `ObfuscationServiceFabric supports type: "named:official"` and tiny-remapper of course supports this too. I'm just wondering what the best way to approach this would be, e.g. can this be done by just configuring fabric-loom in a specific way or should I be writing a remapJar inspired task from scratch?

In essence I'm asking how you would approach this as I'm fairly unfamiliar with the ecosystem and implementation details.

**Comment by modmuss50** [comment]
Looking at the code it currenly seems like this is hardcoded, but it shouldnt be too hard for me to expand this out to support changing the output namespace.

**Comment by LeafHacker** [comment]
That'd be great, thanks

**Comment by modmuss50** [comment]
This was done with the rewrite of remapping jars.
