### ISSUE TITLE
genSources broken on build 40

### ISSUE THREAD

**Issue by hYdos** [FabricMC/fabric-loom#195]
I was updating my fabric api fork and got this error when running genSources. I can confirm its not just me having this problem so I thought I should point it out. Here is a stacktrace: https://hastebin.com/hamubohinu.sql

**Comment by liach** [comment]
This has always been broken for multiproject builds, unfortunately.

**Comment by hYdos** [comment]
are there any plans on fixing it?

**Comment by modmuss50** [comment]
You should only be running gen sources on the root project, if it worked it would decompile the game loads of times. This can be done with `gradlew :genSouces`

It is a bug, but it needs more work than just fixing the crash here.

**Comment by modmuss50** [comment]
Also duplicate of #181

**Comment by shartte** [comment]
The problem I have with this is that I do seem to get multiple jars, one for each subproject, but if I run genSources on the root, it only will fix the line numbers for the root.
So on top of not having the right source attachment, I also dont get proper debugging when I launch _one of the subprojects_ (and not the root).
But I'll probably be moving over to source sets for the time being to avoid this.
