### ISSUE TITLE
Dependencies from non-mod configurations aren't included in the POM

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#200]
Normally you'd use `from components.java` to include deps from `api`/`implementation`, but that doesn't work with Loom additions like the remapped/dev jars.

**Comment by modmuss50** [comment]
This was done specifically to stop mc deps leaking in. Among other reasons. Gradle should allow you to specify what you want in the pom

**Comment by Juuxel** [comment]
There's no clean way to do it, though, since the standard way of `from components.java` just causes an error. Some mods (like mine) want to have non-mod deps that are still exposed, and `mod*` configurations just put them through pointless remapping.

**Comment by natanfudge** [comment]
I think the "clean" way here is to manually write the xml using `pom.withXml { .. }`

**Comment by Juuxel** [comment]
Fixed by #460.
