### ISSUE TITLE
NPE if you forget to properly set up mappings(?) in your gradle build

### ISSUE THREAD

**Issue by maxvar** [FabricMC/fabric-loom#201]
NPE here
https://github.com/FabricMC/fabric-loom/blob/26755cb82c443aaec0858c708b92e58513e4cb41
/src/main/java/net/fabricmc/loom/util/LoomDependencyManager.java#L120
occurred to me while migrating gradle build script to kotlin

**Comment by maxvar** [comment]
full stacktrace here https://pastebin.com/pYAmKNqG

**Comment by modmuss50** [comment]
Im fairly sure I fixed this in 0.4.0
