### ISSUE TITLE
Failed to remap mod: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by natanfudge** [FabricMC/fabric-loom#202]
To reproduce:
- `gradlew assemble`
- Delete `build` and `.gradle` directories (deleting one of them may be enough)
- `gradlew assemble` 

https://hatebin.com/pnwnzvfjtf

Workaround: `gradlew --stop`

**Comment by modmuss50** [comment]
Log link is dead please open a new issue if this is still the case.

**Comment by vlad0-0** [comment]
I'm having the same problem, the new issue was never opened still?
