### ISSUE TITLE
Failure to expose library dependencies for mixin to apply

### ISSUE THREAD

**Issue by dexman545** [FabricMC/fabric-loom#212]
Fabric Loom: 0.4.13 Build (Jenkins #13)

When attempting to mixin to a library added via Gradle, Loom does not properly add it to the classpath for mixin.
Mixin works in production but silently fails in dev environment.

Some relevant discussion with @ChloeDawn who helped me fix some other issues I had.
[Last part of the relevant discussion](https://discordapp.com/channels/507304429255393322/507982478276034570/712827144199209020)
[Example mod, fails in dev but works in production](https://github.com/dexman545/Fabric-Autoswitch/commit/79935c67281669c2a14a6b54333a417025d48f48)

`i would suggest trying it in production, to see if the class loading behaves differently
it may just be that it is an external library attached by loom that it is not visible to the mixin environment
if it works in production, i'd consider it a bug in loom, and it should be reported`

**Comment by modmuss50** [comment]
This is intended, the only reason it works in production is due to include turning the lib into a “mod”.

Mixins should only target minecraft and only if there is no other way other mods.

Ideally you should fork and repackage the lib. (Look into the shadow gradle plugin )

**Comment by dexman545** [comment]
Had issues with `include` on my fork, so I went with this method to obtain the desired functionality.
