### ISSUE TITLE
Comments cannot be placed above header in accesswidener

### ISSUE THREAD

**Issue by i509VCB** [FabricMC/fabric-loom#217]
A bit hard to decide whether this belongs in loom or loader.

I discovered there is an issue with specifying comments above the header. Loading fails in loom due to an `invalid header`

```
# AccessWideners are highly discouraged and should be a last resort.
# Accessors and Bridge (Duck) mixins are much prefered and should be your goal to attempt before adding AWs.
# If you feel there is no other alternative to creating an access transformer, speak with the developers to absolutely verify there is no other way.
accessWidener   v1  named
...
```

The question I have is this intentional?

Here's a stacktrace: https://gist.github.com/i509VCB/c8aad1bd71666d69c982d5f5b2dac056

**Comment by modmuss50** [comment]
Im going to close this as an intended feature. This was based of the idea from the tiny mappings where you can dertimine the file type and version without needing to reading the whole file or anything more than really needed.
