### ISSUE TITLE
A very important opinion for me

### ISSUE THREAD

**Issue by xtexx** [FabricMC/fabric-loom#219]
I am using IDEA.
I have installed 1.16pre2 with the launcher.
But loom needs to download all resources again.
In China, this is very slow.
I can't understand what is useful assets, because I am just sync, not Run.
I think a directory like .minecraft should be used.
Or at least you can choose to disable the URL specified in Libraries, using the Maven repository specified in Gradle.
Can you start using the specified .minecraft directory? Or create a new profile in the specified .minecraft directory, modify some content and start.
In China, it is really slow.
Because China has a Firewall.
Help！

**Comment by liach** [comment]
Try run with `--offline` flag in gradle?

**Comment by xtexx** [comment]
Thanks
