### ISSUE TITLE
Can't launch "MinecraftClient" because class not found

### ISSUE THREAD

**Issue by xtexx** [FabricMC/fabric-loom#222]
```
Warning: Class 'net.fabricmc.devlaunchinjector.Main' not found in module '(Project Name)'
```

**Comment by ramidzkh** [comment]
Edit your run configuration to use the module with `.main` at the end. If you end up reproducing this in a controlled environment, please tell us how

**Comment by xtexx** [comment]
Please elaborate, I don’t understand

**Comment by xtexx** [comment]
I can find "dev-launch-injector" in testRuntimeClasspath

**Comment by liach** [comment]
Run `gradlew idea` task

**Comment by xtexx** [comment]
> Run `gradlew idea` task

I have already run it, "MinecraftClient" and "MinecraftServer" only after running

**Comment by liach** [comment]
In `Run` tab in idea, there should be an `Edit Configuration` option, go in there. In the opened window, choose the Minecraft Client/ Minecraft Server configuration under applications. Then there should be `Use module` selection, and use the module with `.main` suffix, not the one without suffix

**Comment by xtexx** [comment]
> In `Run` tab in idea, there should be an `Edit Configuration` option, go in there. In the opened window, choose the Minecraft Client/ Minecraft Server configuration under applications. Then there should be `Use module` selection, and use the module with `.main` suffix, not the one without suffix

Thanks
