### ISSUE TITLE
Unhelpful exception thrown when invalid namespace specified in access widener

### ISSUE THREAD

**Issue by Stuff-Stuffs** [FabricMC/fabric-loom#226]
If you put an incorrect namespace in an access widener(ex. Named instead of named) the following error gets thrown: Failed to provide net.fabricmc:yarn:1.16-rc1+build.8 : null
This is improved somewhat if you enable the [stacktrace](https://hastebin.com/raw/getewesizi)
`

**Comment by modmuss50** [comment]
Log is dead, please open an new issue if this is still the case.
