### ISSUE TITLE
Loom should provide JSR 305 annotations on the compile classpath

### ISSUE THREAD

**Issue by octylFractal** [FabricMC/fabric-loom#231]
Minecraft itself uses JSR 305 annotations, and while `javac` typically does not require the annotations to be on the classpath, it appears that in certain cases it requires it to be present. One such case is when the source being compiled extends classes that use annotations, as can be seen at https://github.com/octylFractal/fabric-jsr305-bug. This project includes a class that extends a Minecraft class which contains uses of `@Nullable`. This will result in the following exception (on Java 8):
```java
.../fabric-jsr305-bug/src/main/java/net/fabricmc/example/TestClass.java:10: error: cannot access Nullable
public class TestClass extends AlwaysSelectedEntryListWidget<WorldListWidget.Entry> {
       ^
  class file for javax.annotation.Nullable not found
1 error

FAILURE: Build failed with an exception.
```
This can be resolved by using a `compileOnly` dependency on JSR 305. However, given that this is a general problem that affects all users of Fabric, it would be nice if Fabric could provide this `compileOnly` dependency by default. I realize this does implicitly provide the annotations to the users as well, and that documenting that it should not be used might not be effective. One solution I have for this issue, is to remap the JSR 305 annotations to non-source-representable names, e.g. `net.fabricmc.do-not-use.javax.annotations`, which would allow `javac` to use them without allowing end users access.

Note: while I do believe this is technically a `javac` bug (it should simply warn, not error), I have found multiple instances of it on the JDK bug tracker, either marked as fixed or long abandoned, leaving me to believe that it is unlikely to be resolved. Even if a fix were to be added to JDK 14 or 15, I find it even more unlikely that a fix would be backported to JDK 8. Therefore, this is the best solution that will be readily available.

**Comment by i509VCB** [comment]
This is an issue I've had with https://github.com/FabricMC/fabric/pull/641 game rules (linking it to this issue).

We have had talks about remapping the jsr305 annotations to jetbrains or checker framework (our choice on this will apply across all fabric projects), and we haven't exactly voted on it yet.

People using kotlin may be able to access that package but I am unsure on that.

EDIT: This may be a nuclear option, but we could strip all annotations at compile time from MC jar, but I don't like how hacky that is.

**Comment by modmuss50** [comment]
I have opened a PR here to provide a better solution: https://github.com/FabricMC/fabric-loom/pull/240

**Comment by modmuss50** [comment]
Sorted in 0.5 loom
