### ISSUE TITLE
Loom's include doesn't work with Relocation Artifacts on maven.

### ISSUE THREAD

**Issue by jaideepheer** [FabricMC/fabric-loom#241]
I think I have found a bug in loom. Loom's `include` doesn't work with Relocation Artifacts on maven.

To reproduce:-
1) Add `include("org.hibernate:hibernate-validator:6.1.5.Final")` (available at maven here: https://search.maven.org/artifact/org.hibernate/hibernate-validator/6.1.5.Final/jar)
2) Run `gradlew build` and open `modjar/META-INF/jars/`.
3) `hibernate-validator-6.1.5.Final.jar` is not present and thus mod causes class not found errors during loading.
4) Now replace the include line with `include("org.hibernate.validator:hibernate-validator:6.1.5.Final")` (available at maven here: https://search.maven.org/artifact/org.hibernate.validator/hibernate-validator/6.1.5.Final/jar).
5) Run `gradlew build` again.
6) Open `modjar/META-INF/jars/` and see `hibernate-validator-6.1.5.Final.jar` is present.

7 - Optional) Mod still doesn't work because of #242.

**Comment by modmuss50** [comment]
include is none transitive, you need to manually include all transitive deps.
