### ISSUE TITLE
Loom's include doesn't resolve library's version if wildcards are present and sets version in fabric.mod.json as the one with wildcards.

### ISSUE THREAD

**Issue by jaideepheer** [FabricMC/fabric-loom#243]
Steps to reproduce:- 
1) Add `include("com.fasterxml.jackson.core:jackson-core:+")` to your dependencies section in `build.gradle`.
2) Build jar using `gradlew build`.
3) Open jar and open `/META-INF/jars/jackson-core-2.11.1.jar/fabric.mod.json`.
4) See `version` property set to `+`.

This is problematic since the version added to `fabric.mod.json` isn't resolved and is added with wildcards. This obviously breaks any  code that wants to compare library versions since the true version is not in `fabric.mod.json`.

**Comment by jaideepheer** [comment]
I noticed [this line sets the lib version](https://github.com/FabricMC/fabric-loom/blob/4eb699c2fba79832c89712df744aaee27b4278b1/src/main/java/net/fabricmc/loom/util/NestedJars.java#L200).

Maybe https://gist.github.com/dudadornelles/be0bea9f98d3aa17404c this can be used to get resolved version.

**Comment by modmuss50** [comment]
Should be fixed in 0.5
