### ISSUE TITLE
Gradle 6+: Conflicting transitive dependencies result in "has more than one client module definitions" error

### ISSUE THREAD

**Issue by octylFractal** [FabricMC/fabric-loom#249]
Fabric 0.4.33, Gradle 6.5.1.

When adding a `modImplementation` dependency, if it has in some way a "conflicting" dependency, you will get the following error when running `compileJava`:
```
> Configure project :
Fabric Loom: 0.4.33 Build(jenkins #33)
:setting up loom dependencies
:setting up mappings (yarn 1.16.1+build.21)
Configuring compiler arguments for Java

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > com.google.code.gson:gson:2.8.0 has more than one client module definitions.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
1 actionable task: 1 executed
```

This can be reproduced with the following project: https://github.com/octylFractal/fabric-loom-duplicate-client-module
Uncommenting the `exclude` from the build script will fix the issue, but it is not a great solution. Loom should resolve this for the user.

**Comment by modmuss50** [comment]
I dont belive this has anything to do with loom, and is just the way gradle works? 

When they added this error we had to change the way loom handled natives. Feel free to prove me wrong tho.

**Comment by zml2008** [comment]
I think this may have something to do with the fact that loom adds all MC dependencies as direct dependencies of the project, but haven't had time/motivation to investigate further.

**Comment by ghost** [comment]
I get this error when I tried to have my mod rely on my dependency called `:api`. I'm currently trying to setup a multi-module project for my mod.

**Comment by modmuss50** [comment]
Not a loom issue
