### ISSUE TITLE
modRuntime doesn't work with local files

### ISSUE THREAD

**Issue by Earthcomputer** [FabricMC/fabric-loom#250]
Clone of #101, title and description copied from there.

Not much else to say. No errors or warnings logged, any lines like the following are seemingly just ignored:

```groovy
modRuntime files("file/path/here.jar")
modRuntime fileTree(dir: "dir/path/here", include: "*.jar")
```

With a bit of finegling, CurseForge's automatic Maven repo is a decent substitute when trying to add local dev mods (and probably better in the long run anyways), but this is definitely a slight annoyance and may not be avoidable for other applications. `modCompile` does work with `files`, but not with `fileTree`, and obviously doesn't have the benefit of `modRuntime`'s runtime-only properties.

**Comment by mbfrog** [comment]
got it to (almost) work this way for `modRuntime`:

```
repositories {
    // ...
    flatDir {
        dirs "/home/me/dl/mc-mods/fabric"
    }
}

dependencies {
    modRuntime name: "RoughlyEnoughItems-4.10.5"
}
```
But then loom does not remap the jar (if I'm not mistaken, the docs say it should):

```
Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod roughlyenoughitems
...
Caused by: java.lang.RuntimeException: Namespace (intermediary) does not match current runtime namespace (named)
...
```

**Comment by quat1024** [comment]
This is still an issue, biting me a bit since i'm trying to depend on a patreon beta of something lol

Oddly enough, if you peek inside `.gradle/loom-cache/remapped_mods` and look at the classes/access widener, it *does* appear to be successfully remapped. I dunno, maybe the game trying to load the wrong version of the mod or something?

edit: Some cursory futzing with the debugger (breakpoint in `net.fabricmc.loader.transformer.accesswidener.AccessWidener#loadFromMods`) confirms that the game is attempting to load the non-remapped mod jar. Peeking in `modContainer`'s `originUrl` shows a `file:` path that is the *same* as the one i specified in my buildscript, and not in `remapped_mods`.

**Comment by quat1024** [comment]
Really really really really REALLY disgusting workaround, if you absolutely need to depend on a local file right now today (depending on `your-dependency.jar` in a folder called `lib`):

```groovy
repositories {
	flatDir {
		dirs "./lib"
	}
	
	flatDir {
		dirs "./.gradle/loom-cache/remapped_mods"
	}
}

dependencies {
	//...
	
	modCompileOnly name: "your-dependency"
	modRuntime name: "your-dependency-@net.fabricmc.yarn.1_16_3.1.16.3+build.17-v2"
}
```

There's probably a way to derive that filename gunk with an expression, but I'm lazy and just copied and pasted the filename from the remapped_mods folder. It works until you change the yarn version... lol

**Comment by naritanara** [comment]
I'm having the same issue. A clearer workaround I found consists of having only the modCompile dependency and then putting a copy of the mod in the run/mods folder. You have to keep two copies of the mod, but at least version changes don't break it. A fix for this is really needed though.

**Comment by Earthcomputer** [comment]
This appears(?) to now also be broken for `include`

**Comment by Earthcomputer** [comment]
The workaround for JIJ'ing jars built from other source sets (e.g. an API jar) turned out to be quite simple:
```groovy
task remapApiJar(type: RemapJarTask, dependsOn: project.apiJar) {
	input = apiJar.archiveFile
	classifier = 'api'
	addNestedDependencies = false
}
remapJar.dependsOn remapApiJar

repositories {
	// ...
	flatDir {
		dirs file(remapApiJar.archivePath).parentFile
	}
}

dependencies {
	include name: file(remapApiJar.archivePath).name.with { it.endsWith('.jar') ? it.substring(0, it.length() - 4) : it }
}
```
Thanks to mbfrog for his workaround, didn't know flatDir repos existed until now.

**Comment by modmuss50** [comment]
In 0.7 loom I have expanded this to allow passing in any paths. You are supposed to be able to pass in a custom configuration as well but I broke this and do plan on fixing it.
