### ISSUE TITLE
AWs don't work properly with submodules

### ISSUE THREAD

**Issue by Martmists-GH** [FabricMC/fabric-loom#251]
While `gradle :gensources` works fine, `gradle :submodule:build` fails, complaining the AW-ed fields/classes/methods aren't public.

For reference, use [Gunpowder@dim-api](https://github.com/Gunpowder-MC/Gunpowder/tree/dim-api) where the issue occurs.

**Comment by Chocohead** [comment]
If you don't explicitly declare the AW for each Gradle project which depends on one of the widened things you'll get this. Because the AW isn't inherited it will be using a normal jar for the API project but the AW'd one for the base.

**Comment by Martmists-GH** [comment]
The problem is that the AW is specified on base and not used while compiling base.

**Comment by ghost** [comment]
I'm encountering the same issue, only seems to happen on loom `0.5-SNAPSHOT`, Expanded Storage depends on my internal container library however whilst building expanded storage the container libraries AW's aren't remapped and therefore produce errors at production runtime. Expanded Storage's AW's are remapped however.

**Comment by modmuss50** [comment]
I believe this sounds similar to the issue I had with fabric api on 0.5, for now just use 0.4

**Comment by modmuss50** [comment]
Link is dead, AWs are not passed onto submodules.
