### ISSUE TITLE
Remapping adds imports for unknown types

### ISSUE THREAD

**Issue by williewillus** [FabricMC/fabric-loom#255]
I'm working on porting a certain tech mod to Fabric from Forge, which means a few platform class names are errored out/not available in the environment.

Today, I used `migrateMappings` to move the in-progress port from 1.16.1+build.20 to 1.16.2+build.1. It went mostly smoothly, except that the task added imports for all the unknown forge classes:

```
import vazkii.botania.api.mana.IManaReceiver;
import vazkii.botania.common.block.tile.ModTiles;
import vazkii.botania.common.block.tile.TileMod;
import IEnergyStorage; // <-- ???
import LazyOptional; // <-- ???
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
```

this is probably a mercury bug or something, feel free to redirect.

**Comment by i509VCB** [comment]
Kinda sounds like Mercury. Jamie is here (https://discord.gg/frEnKFd) or at #cadix on espernet if you wanted to bring it up with him.

**Comment by williewillus** [comment]
I found a possibly related issue on the mercury repo so I'll move there
