### ISSUE TITLE
Is there a way to add access transformer?

### ISSUE THREAD

**Issue by laura240406** [FabricMC/fabric-loom#256]
The title is very self explaining. I'm currently trying to do some things with some private classes and methods etc. but I didn't find a way to specify access transformer to make them public. Did I miss something or is there no support for them?

**Comment by modmuss50** [comment]
Let me introduce access wideners: https://fabricmc.net/wiki/tutorial:accesswideners

**Comment by laura240406** [comment]
I don't know what I'm doing wrong but it doesn't change the visibility of the class I'm trying to change.
