### ISSUE TITLE
Feature Request: Loom GUI

### ISSUE THREAD

**Issue by TheoCGaming** [FabricMC/fabric-loom#257]
I want there to be a GUI to make development seem less intimidating (or maybe even easier) for beginners.

**Comment by laura240406** [comment]
I think that this should be a separate project.

**Comment by modmuss50** [comment]
What would this entail? What do you currently find hard? 

I think if there is a problem we need to look at all possible solutions.

**Comment by laura240406** [comment]
One good feature would be that you could add AW (see #258)

**Comment by modmuss50** [comment]
An IDE plug-in could provide code completion for this. As for them not working I’d that’s a bug then it needs to be fixed.

The K9 bot on discord now provides help with these.

**Comment by modmuss50** [comment]
This isn’t really a loom issue.
