### ISSUE TITLE
modCompile files("...") will not save remapped class files

### ISSUE THREAD

**Issue by asiekierka** [FabricMC/fabric-loom#26]
Only seems to happen with local files.

**Comment by Tschipp** [comment]
This issue occured for me in vscode when I had the "Java Linter", "Java Imports Snippets" and "Java Language Support" extensions installed. I'm not sure why or which extensions caused this issue, but I resolved it by uninstalling all java related extensions and only installing "Language Support for Java(TM) by Red Hat", "Debugger for Java", "Java Test Runner", "Maven for Java" and "Java extension Pack".
