### ISSUE TITLE
Included sub-projects are dev builds, not production.

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric-loom#265]
In loom 0.4 the refmap field in mixins.json is properly filled out by loom but this is no longer the case in loom 0.5(.22 / -SNAPSHOT)
Note, I'm not using shared caches.
Example of 0.4:
```json
{
  "required": true,
  "minVersion": "0.8",
  "package": "ninjaphenix.chainmail.mixins",
  "compatibilityLevel": "JAVA_8",
  "mixins": [
    "ItemGroupMixin",
    "PlayerManagerMixin",
    "WorldMixin"
  ],
  "client": [],
  "injectors": {
    "defaultRequire": 1
  },
  "refmap": "chainmail-refmap.json"
}
```

Example of 0.5:
```json
{
  "required": true,
  "minVersion": "0.8",
  "package": "ninjaphenix.chainmail.mixins",
  "compatibilityLevel": "JAVA_8",
  "mixins": [
    "ItemGroupMixin",
    "PlayerManagerMixin",
    "WorldMixin"
  ],
  "client": [
  ],
  "injectors": {
    "defaultRequire": 1
  }
}
```

**Comment by modmuss50** [comment]
humm, ok. thats odd. esp as your not using shared caches. I will take a look shortly.

**Comment by ghost** [comment]
Just though I'd mention, I tried `sharedCaches` yesterday and this issue persists even with it on.

Also to reproduce you can clone https://github.com/NinjaPhenix/FabricMods/tree/1.16.2
- Change the topmost `build.gradle` to use loom `0.5-SNAPSHOT`
- run `gradlew expandedstorage:build`
- The included chainmail jar located at `expandedstorage/build/libs/expandedstorage-x+1.16.2.jar/META-INF/jars/chainmail-x+1.16.2.jar` will not have the refmap field in it's `chainmail.mixins.json` file.

**Comment by modmuss50** [comment]
I cannot repoduce this with or without shareCaches. Can you try again ensuing your are using loom 0.5.22 (or newer). If so a log output when ran with --debug would be ideal.
