### ISSUE TITLE
Cannot DownloadSources

### ISSUE THREAD

**Issue by The-One-and-only-Lookas-the-L** [FabricMC/fabric-loom#269]
Every time i execute the   ":downloadSources_RANDOM-UUID", i get an error that it cannot include all files

the ijmiscinit.gradle:

allprojects {
  afterEvaluate { project ->
    if(project.path == ':') {
        def overwrite = project.tasks.findByName('DownloadSources') != null
        project.tasks.create(name: 'DownloadSources', overwrite: overwrite) {
        doLast {
          def configuration = null
          def repository = project.repositories.toList().find {
              project.repositories.clear()
              project.repositories.add(it)
              configuration = project.configurations.create('downloadSourcesFrom_' + it.name + '_' + UUID.randomUUID())
              configuration.transitive = false
              project.dependencies.add(configuration.name, 'net.minecraft:minecraft:1.16.2-mapped-net.fabricmc.yarn-1.16.2+build.1-v2:sources')
              configuration.resolvedConfiguration.lenientConfiguration.getFiles().any()
          }
          if (!repository) {
              configuration = project.configurations.create('downloadSources_' + UUID.randomUUID())
              configuration.transitive = false
              project.dependencies.add(configuration.name, 'net.minecraft:minecraft:1.16.2-mapped-net.fabricmc.yarn-1.16.2+build.1-v2:sources')
              configuration.resolve()
          }
          new File('C:\\Users\\----------\\AppData\\Local\\Temp\\sourcesloc\\path.tmp').write configuration?.singleFile?.path
        }
      }
    }
  }
}

and the gradle.properties:

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/use
	minecraft_version=1.16.2
	yarn_mappings=1.16.2+build.1
	loader_version=0.9.1+build.205

# Mod Properties
	mod_version = 1.0.0
	maven_group = net.fabricmc
	archives_base_name = fabric-example-mod

# Dependencies
	# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
	fabric_version=0.17.2+build.396-1.16

if you need anything else let me know

**Comment by modmuss50** [comment]
I dont know what you are trying to do here, this doesnt seem right at all and its not a bug with loom.
