### ISSUE TITLE
Importing a loom Gradle project into IDEA and running genSources from IDEA does not work

### ISSUE THREAD

**Issue by shadowfacts** [FabricMC/fabric-loom#27]
IDEA won't use the generated sources, it will still decompile the .class files itself, which results in mismatched line-numbers.

**Comment by asiekierka** [comment]
It won't use the generated sources? Even if you refresh the project in some manner to rescan for dependencies?

**Comment by Prospector** [comment]
I've noticed it still lets you open the `.class` files if you use the double-shift search. Make sure to only open `.java` ones.

**Comment by shadowfacts** [comment]
The issue persists after refreshing in the Gradle pane in IDEA.

Clicking file/line references in stack traces does not work, nor does searching show the source file, only the .class.

**Comment by asiekierka** [comment]
Could you check if removing the old IDEA files, using gradlew idea with sources generated, and loading that project (no import!) works?

That's not a fix, but it will narrow things down.

**Comment by shadowfacts** [comment]
Yes, using the project generated by `gradle genSources idea` works, it's when the IDEA Gradle import feature is used.

**Comment by modmuss50** [comment]
This is no longer an issue, it works fine with loom 0.2.7 and idea 2020.1
