### ISSUE TITLE
Errors in generated source files

### ISSUE THREAD

**Issue by Rubydesic** [FabricMC/fabric-loom#270]
`GameRenderer.java`, l232:

```java
int i = true;
```

`PlayerEntity.java`, l1048:

```java
int j = 0;
int j = j + EnchantmentHelper.getKnockback(this);
```

And there are a lot of compile errors, according to intellij. Is this to be expected?

**Comment by Earthcomputer** [comment]
This is due to bugs in the fernflower decompiler, but it's not an issue since Fabric doesn't recompile sources.

**Comment by modmuss50** [comment]
Yeah, its technically a bug, but not something we will fix. Hopefully we can get the CFR decompiler working well and that should fix a lot of these issues.
