### ISSUE TITLE
Compiling results in a logs/latest.log file being generated when using mixins

### ISSUE THREAD

**Issue by octylFractal** [FabricMC/fabric-loom#274]
Mixins log4j logger is picking up the log4j.xml on the classpath from Minecraft and using it, resulting in an empty `logs/latest.log` file being generated in the project directory.

I'm using Loom 0.4.33 and Mixins 0.8.1+build.21.

To reproduce:
1. Clone https://github.com/octylFractal/fabric-loom-latest-log
2. Run `./gradlew compileJava`
3. Notice a new `logs/latest.log` file.

**Comment by i509VCB** [comment]
Hmm so it wasn't just me. Good to know.

**Comment by modmuss50** [comment]
This has 100% been fixed after log4j was removed from the mixin AP
