### ISSUE TITLE
fabric.mod.json not synthesized for non-mod project dependencies.

### ISSUE THREAD

**Issue by kwvanderlinde** [FabricMC/fabric-loom#278]
According to the [loom docs](https://fabricmc.net/wiki/documentation:fabric_loom), the `include` keyword should always synthesize a `fabric.mod.json` file for non-mod dependencies. This used to work for project dependencies but since 0.5.23 the file is no longer synthesized for project dependencies.

Here is a basic project that demonstrates this: [test-include-project.zip](https://github.com/FabricMC/fabric-loom/files/5215178/test-include-project.zip). That project is composed of a `mod` project and a `nonmod` project, where the `mod` project depends on `nonmod`. The mod project is using `fabric-loom` 0.5.22.

After running `./gradlew :mod:remapJar` we get a `mod-1.0-SNAPSHOT.jar` with this structure:
```
.
├── fabric.mod.json
├── META-INF
│   ├── jars
│   │   └── nonmod-1.0-SNAPSHOT.jar
│   └── MANIFEST.MF
├── mod.mixins.json
└── test
    └── mod
        ├── client
        │   └── ModClient.class
        └── Mod.class
```
Note that it contains `nonmod-1.0-SNAPSHOT.jar` (as it should) which itself contains a `fabric.mod.json` despite not being a mod project:
```
.
├── fabric.mod.json
└── META-INF
    └── MANIFEST.MF
```

Now if we change the `fabric-loom` version to 0.5.23, we get the same structure for `mod-1.0-SNAPSHOT.jar`:
```
.
├── fabric.mod.json
├── META-INF
│   ├── jars
│   │   └── nonmod-1.0-SNAPSHOT.jar
│   └── MANIFEST.MF
├── mod.mixins.json
└── test
    └── mod
        ├── client
        │   └── ModClient.class
        └── Mod.class
```
But if we inspect `nonmod-1.0-SNAPSHOT.jar` we can see that `fabric.mod.json` is not present:
```
.
└── META-INF
    └── MANIFEST.MF

```

I dug around a bit, and believe it is due to [this change](https://github.com/FabricMC/fabric-loom/commit/545b0c946bc6a91965da63abb9bf7b04f51886e9) which specifically excludes project dependencies from the necessary processing.

**Comment by modmuss50** [comment]
If this is still an issue please open a new issue.
