### ISSUE TITLE
modImplementation not deobfuscating Mixin @Shadow

### ISSUE THREAD

**Issue by creeper123123321** [FabricMC/fabric-loom#279]
https://pastebin.com/TDdMNgwE = ./gradlew clean runClient -> crashing
https://github.com/ViaVersion/ViaFabric/blob/46cc0b729fa0b0790ea4e44a632c03d64b1e90af/src/main/java/com/github/creeper123123321/viafabric/mixin/client/MixinServerAddress.java#L50
https://github.com/creeper123123321/viafabricjarinjartest/blob/master/build.gradle

**Comment by modmuss50** [comment]
I have seen this in my own project as well, will take a look. What loom version?

**Comment by creeper123123321** [comment]
0.4-SNAPSHOT

**Comment by zml2008** [comment]
https://github.com/SpongePowered/Mixin/issues/431 looks like it is related

**Comment by valoeghese** [comment]
I have also encountered this with a library mod

**Comment by valoeghese** [comment]
TooManyEvents has a mixin which does not deobfuscate

**Comment by valoeghese** [comment]
Please shift this to high priority thanks

**Comment by modmuss50** [comment]
This should be fixed, what loader version are you using?

**Comment by valoeghese** [comment]
wait if it's fixed why is the issue open

**Comment by valoeghese** [comment]
I'm on loom 0.4-SNAPSHOT

**Comment by modmuss50** [comment]
Its a mixin issue, fabric-loader 0.10.1 should include the fix. 

This issue went unnoticed, can you confirm updating loader fixes it?

**Comment by valoeghese** [comment]
ye it seems to work now
