### ISSUE TITLE
genSources broken on latest loom snaphsot

### ISSUE THREAD

**Issue by RDIL** [FabricMC/fabric-loom#288]
Hi,
I admittedly haven't used loom for like a month or so, and I upgraded to 0.5 sometime, and I just tried to run genSources, but I got this error:

`Error: Could not find or load main class net.fabricmc.loom.decompilers.fernflower.FabricForkedFFExecutor`

repo: https://github.com/RDIL/Cherry

Thanks!

**Comment by modmuss50** [comment]
A full log would be useful, thanks.

**Comment by RDIL** [comment]
Here's a build scan @modmuss50 (includes logs and lots of details):
https://scans.gradle.com/s/5rzprctgmgkuy

**Comment by RDIL** [comment]
Interestingly enough, it works just fine with CFR.

**Comment by modmuss50** [comment]
It’s an issue caused by a recent fix to another bug. Right now loom has to be on the root project

**Comment by RDIL** [comment]
I tried adding it and got:
```
A problem occurred configuring root project 'Cherry'.
> No 'minecraft' dependency was specified!
```

**Comment by RDIL** [comment]
Finally got it to work.

**Comment by vpzomtrrfrt** [comment]
who were you denvercoder9

what did you see

**Comment by ghost** [comment]
How to fix this? I get same issue on latest loom version

**Comment by i509VCB** [comment]
Could you include a log of trying to generate sources?
