### ISSUE TITLE
genSources on multiproject builds eats up all available CPU

### ISSUE THREAD

**Issue by TheGlitch76** [FabricMC/fabric-loom#291]
I believe a fix for running genSources on subprojects was added, but this doesn't apply on parallel builds.

The result of running `gradlew genSources` on [patchwork-api](https://github.com/PatchworkMC/patchwork-api/tree/9ba44fa6df66c7ab6e857cdf918a30e5625e712d) is it running on every project, eating up all of the CPU and potentially freezing your PC.

**Comment by modmuss50** [comment]
This is just how gradle works. You should just run the task on the root project using `gradlew :genSources`
