### ISSUE TITLE
Time surpassed in ms shows massive values when building and when it says time for build it is many times the actual amount

### ISSUE THREAD

**Issue by Genau6502** [FabricMC/fabric-loom#293]
I am on loom 0.5-SNAPSHOT. A video of the exact issue can be found here: http://storeimg.dttp.tech/images/mjQqg.mp4. I didn't have this on loom 0.2.7, but got this after upgrading. 
![image](https://user-images.githubusercontent.com/66269211/97119963-b6918000-170b-11eb-964d-72daec43b174.png)
This build in reality took about 10 seconds to complete but the time elapsed was reported to have been over 25 mins. 
I also posted on the fabric discord with another case of this bug https://discord.com/channels/507304429255393322/766713756498788352/770024598427140156
https://discord.com/channels/507304429255393322/766713756498788352/770025108676149277

**Comment by modmuss50** [comment]
This is very odd? I fail to see how its loom's issue but would love to know if anyone has any ideas.

What gradle version are you using?

**Comment by Genau6502** [comment]
I am using gradle 6.6.1 I put the issue here as I only got it after updating loom
![image](https://user-images.githubusercontent.com/66269211/97120493-366d1980-170f-11eb-80ed-0956d7e453ac.png)
I'm also putting this here in case it is of use
