### ISSUE TITLE
Broken remapping of Fabric API.

### ISSUE THREAD

**Issue by naritanara** [FabricMC/fabric-loom#297]
In my mod I individually add the Fabric API modules:
```
modImplementation "net.fabricmc.fabric-api:fabric-api-base:${project.fabric_api_base_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-command-api-v1:${project.fabric_command_api_v1_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-item-api-v1:${project.fabric_item_api_v1_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-item-groups-v0:${project.fabric_item_groups_v0_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-networking-v0:${project.fabric_networking_v0_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-object-builder-api-v1:${project.fabric_object_builder_api_v1_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-renderer-registries-v1:${project.fabric_renderer_registries_v1_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-tool-attribute-api-v1:${project.fabric_tool_attribute_api_v1_version}"
```
It all worked perfectly until I added `fabric-renderer-registries-api`, gradle isn't remapping correctly some classes, giving me import lines like those:
```
import net.fabricmc.fabric.impl.client.renderer.registry.BlockEntityRendererRegistryImpl;
import net.minecraft.class_5614;
import net.minecraft.block.entity.BlockEntity;
import net.minecraft.block.entity.BlockEntityType;
```
I don't understand why this happens, because class_5614 as far as I know is mapped on my yarn version (1.16.4-build.6). It looks like my workspace is broken somewhat, but I tried to clean both loom and Gradle caches and it still gives the broken output. I can't compile my sources, neither find class_5614 nor it's mapped version.

What can I be doing wrong? I will send you any information that you need.

**Comment by i509VCB** [comment]
I believe you may using an incorrect version of the renderer registries api.

I would recommend using the example shown in the readme for fabric api to refer to individual modules so you don't need to worry about the mess which is the hash:
https://github.com/FabricMC/fabric#groovy-dsl-1

**Comment by naritanara** [comment]
I'll try that, though I'm getting those results with version `+`, which Gradle automatically detects as the latest.

**Comment by i509VCB** [comment]
You really shouldn't be using `.+` with fabric api since 1.16 and 1.17 could share the same latest version for different api modules.

**Comment by naritanara** [comment]
Oh I didn't take that into account, I guess that's why it was failing. I'll check it when I can.

**Comment by naritanara** [comment]
I changed my Gradle file to work like the example and it all works now, thank you for the help!
