### ISSUE TITLE
[0.5] Loom downloads custom manifests for Minecraft incorrectly

### ISSUE THREAD

**Issue by rizecookey** [FabricMC/fabric-loom#302]
I'm currently working with the newest Combat Snapshot, and thus need to use a custom manifest in the build.gradle, declared like this:
```
minecraft {
	customManifest = "https://gist.githubusercontent.com/rizecookey/4c6142baaccc3875f9b227fe22f2ace5/raw/c8ed74b19f7a5315813c9d4b199798b692a8f359/1.16_combat-6.json"
}
```
(I'm also using a custom Intermediary url, but that is not relevant here since it's downloaded correctly)

However, when running the build script, Gradle saves the following file as the version manifest in fabric-loom's cache instead:
https://gist.github.com/rizecookey/16af4f96f7c911427b290925aa0b7a80#file-minecraft-1-16_combat-6-info-json

**Comment by modmuss50** [comment]
I believe this has been fixed in 0.9
