### ISSUE TITLE
Loom assumes XstartOnFirstThread argument is needed. causing bugs in lwjgl 2.x.x on OSX

### ISSUE THREAD

**Issue by hYdos** [FabricMC/fabric-loom#303]
The argument -XstartOnFirstThread(something like that) is causing old versions of minecraft on mc (1.8.9) to not open a window.

**Comment by hYdos** [comment]
for context, here is how the temporary solution works https://gist.github.com/BoogieMonster1O1/33da454fc697413d7807569957351192

**Comment by modmuss50** [comment]
Why was this closed? I dont think it was fixed.

**Comment by modmuss50** [comment]
Fixed in 1.6
