### ISSUE TITLE
Loom assumes an access widener will have a mod metadata property

### ISSUE THREAD

**Issue by ChloeDawn** [FabricMC/fabric-loom#311]
**Loom version:** 0.5.42
I use an access widener for compile-time access transforming and cannot build my jar as Loom assumes that my access widener (which is not located in the source set path) will have a property in mod metadata, failing here:
https://github.com/FabricMC/fabric-loom/blob/86577525cdc72198727490dff37530dfaf013c88/src/main/java/net/fabricmc/loom/task/RemapJarTask.java#L215

**Comment by ChloeDawn** [comment]
The solution here would be to ignore the access widener if it is not located in the source set

**Comment by modmuss50** [comment]
Opps wrong issue.

**Comment by ChloeDawn** [comment]
Any update on this?

**Comment by modmuss50** [comment]
You should be able to disable this by doing:

```groovy
remapJar {
   remapAccessWidener = false
}
```

Please let me know if that helps?

**Comment by ChloeDawn** [comment]
It seems to have no effect. I also tried in a `doLast` and it still results in the same error.

If I try in a `doFirst` I get:
```
The value for task ':remapJar' property 'remapAccessWidener' is final and cannot be changed any further.
```
```kt
remapJar {
  doFirst {
    remapAccessWidener.set(false)
  }
}
```

**Comment by ChloeDawn** [comment]
After a brief search online it appears to be related to modules, and may need further fixes in Loom

**Comment by modmuss50** [comment]
I havent looked into modules at all in loom, I have some plans but need to gain some input on what people will want.

I am creating a test for compile only access wideners atm, as it should work. The work around for now is to just include the AW in the jar.

**Comment by Chocohead** [comment]
You wouldn't want it in a `doFirst` or a `doLast`, it's a task property which means it should be being changed during task configuration time not task execution. As you're working on the default `remapJar` task things are configured a little late:
https://github.com/FabricMC/fabric-loom/blob/429d2dadb1f223a0399e1557ce0b305056b5c497/src/main/java/net/fabricmc/loom/configuration/RemapConfiguration.java#L77-L80
So you'll want something like
```groovy
remapJar {
	afterEvaluate {
		remapAccessWidener = false
	}
}
```
to configure it after Loom has done but before the task has started.

**Comment by modmuss50** [comment]
Yes, that should work.

I should look into making the remap jar task lazy to remove the need for the afterEvaluate, but thats something for 0.9 loom.

**Comment by ChloeDawn** [comment]
Attempting to use `afterEvaluate` results in
```
org.gradle.api.internal.AbstractMutationGuard$IllegalMutationException: Project#afterEvaluate(Action) on root project 'BeaconOverhaul' cannot be executed in the current context.
```
```kt
remapJar {
  afterEvaluate {
    remapAccessWidener.set(false)
  }
}
```

**Comment by ChloeDawn** [comment]
Ah I had to invert the scopes. This works:
```kt
afterEvaluate {
  remapJar {
    remapAccessWidener.set(false)
  }
}
```

**Comment by modmuss50** [comment]
Great, ill leave this issue open as a reminder to make remapJar lazy to hopefully remove the need for the afterEvaluate, if you dont mind.

**Comment by ChloeDawn** [comment]
~~Still occuring on `0.9.54` using:~~
```kotlin
remapJar {
  remapAccessWidener.set(false)
}
```
Nvm, working on `0.10.21`. I wasn't using 0.10 because https://fabricmc.net/versions.html implies that it targets 1.18
