### ISSUE TITLE
Mapping processors

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#315]
Basically jar processors, but for mappings -- mappings go in, mappings come out. This would be useful for applying changes to upstream Yarn mappings (including but not limited to renaming a certain screen-related class).

I've got a "working" example of this [on my Loom fork](https://github.com/Juuxel/fabric-loom/tree/feature/mapping-processor), but the implementation is pretty buggy.

**Comment by haykam821** [comment]
This can be revisited now that the basis for layered mappings is complete. For simplicity, an easier way to simply overwrite mappings based on the intermediary would be preferred over defining an entire processor for it.

**Comment by Juuxel** [comment]
I'd still prefer some way to do regex/pattern replacements over the whole mappings, since that'd allow users to specify replacements that don't need to be updated when new matching names are added. (Like changing a bunch of similarly named classes that have a common superclass.)

Simple replacements would probably be easier, though, and there's also existing examples of that like in Chocoloom.

**Comment by modmuss50** [comment]
I currently have some work done towards loading in mapping files on top of previous layeres, with intermediary always being the base. I hope to have a PR up fairly soon.


I like the idea of being able to mass process names, will need to come up with a good way to make it cacheable so it doesn’t run every time gradle runs. Not sure sure what that will look like.

**Comment by Juuxel** [comment]
At least regex mass processing could be cached if it was configured declaratively (so no arbitrary processing logic in code, but only stuff like `rename "abc", "def"` in build.gradle).

**Comment by modmuss50** [comment]
This can be done by creating a layered mapping that warps other layers.
