### ISSUE TITLE
An OutOfMemoryError while remapping mods will result in a partially-remapped mod, causing confusing errors

### ISSUE THREAD

**Issue by coderbot16** [FabricMC/fabric-loom#321]
There's two issues here:

1. The fact that there's an OOM in the first place (memory leak?)
2. That the partially remapped jar isn't detected / discarded somehow

The partially-remapped mod will likely cause all sorts of weird errors about missing classes that should exist in that mod.

**Comment by modmuss50** [comment]
This should slove that, I imagine there are other places where loom should cleanup after a failure as well.

**Comment by coderbot16** [comment]
Sounds good, thanks!
