### ISSUE TITLE
Kapt 1.4.21 causes NoSuchFieldError with Loom

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#324]
Loom version: both `0.5-SNAPSHOT` and `0.6-SNAPSHOT`  
[Log](https://gist.github.com/Juuxel/35b3a5f4f1919cb4061b867e946ffb5d#file-log-L289)

Loom's `KaptApInvoker` tries to access `Kapt3KotlinGradleSubplugin.Companion`, which has been removed in some newer release of Kapt.

**Comment by modmuss50** [comment]
Thats fun.

**Comment by Juuxel** [comment]
Isn't it? Downgrading to Kotlin 1.3.72 works as a workaround.

**Comment by modmuss50** [comment]
Its what we get for using `org.jetbrains.kotlin.gradle.internal` sounds like its going to need a nasty refleciton hack or something to ideally support both. Failing that 0.6 can just support the latest version.

**Comment by modmuss50** [comment]
Looks like a trivial fix, the method its calling is very basic ill just copy it out.

**Comment by modmuss50** [comment]
Please try 0.6 loom build 18 and let me know if that sloves it. If so ill backport to 0.5 loom.
