### ISSUE TITLE
Is there any way to just add decompiled minecraft to the classpath without adding fabric loader classes, registering fabric's reobf task or automatically generating intellij runs as well?

### ISSUE THREAD

**Issue by Rubydesic** [FabricMC/fabric-loom#325]
Trying to setup a multi-project build which simply produces an unobfuscated "dev" jar. All I want is basically to add the remapped minecraft sources to my classpath, no fabric loader classes, no autogenerated intellij runs, nothing else. Is there a simple way to do that?

**Comment by Juuxel** [comment]
Not sure about the others, but Fabric Loader classes can be removed by just removing the dependency.

**Comment by modmuss50** [comment]
Yes, you can just remove the loader dep from the build.gradle.

As for the runs they can be removed by doing I believe

```gradle
loom {
   autoGenIDERuns = false
}
```

**Comment by Rubydesic** [comment]
Thanks
