### ISSUE TITLE
Publish multiple artifacts with different mappings?

### ISSUE THREAD

**Issue by Rubydesic** [FabricMC/fabric-loom#327]
How would I go about publishing two JAR artifacts remapped by two different mappings?

**Comment by modmuss50** [comment]
I dont quite follow what the use case for this would be? Do you want an intermediary and offical named jar?

Or do you want to use 2 named inputs? If thats the case this would take a considrable refactor to allow this, not something I really want to undertake without a good reason.

**Comment by Rubydesic** [comment]
The use case is producing both a fabric intermediary mapped JAR and an SRG mapped JAR for making libraries compatible with multiple modloaders. The current solution is to do some shenanigans with gradle multiproject that's very finicky, or just symlink in the sources into two different loom projects, which seems rather silly.

**Comment by modmuss50** [comment]
This should now be possible with my jar remapping rewrite. You can set the target namespace here: https://github.com/FabricMC/fabric-loom/blob/03d3950d119830edb65d35bafb90c330aa3a78d1/src/main/java/net/fabricmc/loom/task/AbstractRemapJarTask.java#L59
