### ISSUE TITLE
Throw error on mods without `fabric.mod.json`

### ISSUE THREAD

**Issue by yyny** [FabricMC/fabric-loom#329]
I accidentally put my `fabric.mod.json` in the wrong folder, causing it to not appear in the jar. Instead of throwing an error, loom caused cryptic error messages in a different mod in the form `error: cannot access class_${intermediate_id}: class file for net.minecraft.class_${intermediate_id} not found`.

 * `modImplementation` should throw an error when receiving a `.jar` without `fabric.mod.json`.
 * `loom` should throw an error when attempting to build a `.jar` without a `fabric.mod.json`.

**Comment by zml2008** [comment]
The first case is valid and should not throw an error - modImplementation is needed to make sure non-mod libraries are included in the mod's pom

The second could be an optional check on the remapJar task, but it seems like there would be reasonable cases to have outputs that don't get remapped and that aren't themselves mods

**Comment by yyny** [comment]
@zml2008 There could be a `modLibrary "..."` then for jars that don't have a `fabric.mod.json`. I think there will definitely be people that need jars without `fabric.mod.json`, but that should be opt-in, not opt-out.

**Comment by zml2008** [comment]
no - the mod* configurations aim to mirror standard gradle configurations, and library is not a standard gradle configuration

**Comment by yyny** [comment]
Then `nonModImplementation`. Or add a `{ nonMod = true }` property. My point is that this behaviour shouldn't be the default since it's rarely useful and more often a bug.

Also
> The second could be an optional check on the remapJar task, but it seems like there would be reasonable cases to have outputs that don't get remapped and that aren't themselves mods

If you aren't going to remap the jar, then why would you add it to `remapJar`?

**Comment by modmuss50** [comment]
I dont think this needs fixing. The debug log should provide more info to aid with debugging issues caused by this.
