### ISSUE TITLE
IDEA run configuration generation uses wrong default for 'shorten command line'

### ISSUE THREAD

**Issue by McJty** [FabricMC/fabric-loom#33]
When I was on windows and generated an IDEA project using 'gradlew genSources idea' the run configuration used a command line shortening method that makes the mod not load. The configuration was set too:

Shorten command line: 'user-local default: JAR manifest'

I had to set it to 'none' to have a working loading mod

Versions:

	minecraft "com.mojang:minecraft:18w49a"
	mappings "net.fabricmc:yarn:18w49a.10"
	modCompile "net.fabricmc:fabric-loader:0.2.0.64"
	modCompile "net.fabricmc:fabric:0.1.0.37"

**Comment by modmuss50** [comment]
I havent seen this issue again, please open a new issue if it still happens with the latest versions. Thanks.
