### ISSUE TITLE
Improve support for cfr

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric-loom#336]
Now that fabric has an updated version of cfr which can dump javadoc and cfr itself has increased support for line numbers, it would be interesting to see if cfr would be a viable alternative for source generation than fernflower.

**Comment by modmuss50** [comment]
Yes, I did look into this, I was close but didnt quite get it working, see https://github.com/FabricMC/fabric-loom/pull/248

**Comment by modmuss50** [comment]
CFR is now fully supported.
