### ISSUE TITLE
where is the minecraft source code

### ISSUE THREAD

**Issue by MrGeorgen** [FabricMC/fabric-loom#339]
I ran `gradle genSoucres`, but I only can find a few jars in `~/.gradle/caches/fabric-loom`.
Where is the generated source code

**Comment by Genau6502** [comment]
The jars are the source code...
Also it's `gradlew genSources`, not `gradle genSoucres`
Please close this, it isn't a bug

**Comment by YTG1234** [comment]
> Please close this, it isn't a bug

umm, technically issues *can* be questions but you're not supposed to be viewing the source files directly anyway.
