### ISSUE TITLE
IllegalStateException during remapSourcesJar when a JavaDoc @links to a package

### ISSUE THREAD

**Issue by The-Fireplace** [FabricMC/fabric-loom#341]
During the build process, if a Javadoc uses `{@link package.here.not.class}` an exception will be thrown during remapSourcesJar.
I've made [a quick change to the Fabric example mod](https://github.com/The-Fireplace/fabric-example-mod/commit/e74b8d1c16c69ba408ec0f59284521b4997dc13f) to demonstrate.
The exception:
https://gist.github.com/The-Fireplace/17364d63fb80d1aa8e07bad6bd3de982

Tested with Loom 0.5-SNAPSHOT

**Comment by modmuss50** [comment]
IDK if this is a loom bug or a mecury bug or even jdt. 

@jamierocks any ideas?

**Comment by jamierocks** [comment]
Looks like a Mercury bug to me, we need to support whatever AST node package Javadoc links uses.

edit: my previous comment was wrong.

**Comment by jamierocks** [comment]
Fix merged with https://github.com/CadixDev/Mercury/commit/7fa0ba1e03bec3facd084e3d69102a2f6e7afa17, will make an rc2 release shortly.

**Comment by modmuss50** [comment]
Closing as this was fixed.
