### ISSUE TITLE
Rebuilding Yarn in local repo does not cause rebuilt minecraft.jar 

### ISSUE THREAD

**Issue by codewarrior0** [FabricMC/fabric-loom#35]
When yarn is built outside of the usual CI system and installed in the local Maven repo, its jar is assigned a name like "yarn-18w50a-local.jar". This name does not change if yarn is rebuilt and installed again. Thus, after rebuilding yarn a second time, the changes are not detected when a mod (that is configured to fetch yarn from the local repo) is built with `--refresh-dependencies`, and so the `minecraft-18w50a-mapped-local.jar` is not rebuilt with the new mappings. To force a proper rebuild, both the mapped jar and the mappings must be removed from the cache folder.

The loom mechanisms (MinecraftMappedProvider, MappingsProvider, et al) for extracting the mappings from the yarn jar and rebuilding the mapped minecraft jar using those mappings only rely on the version numbers (or rather, filenames) of the mappings and the minecraft jar to decide whether to rebuild the mapped minecraft jar.

**Comment by modmuss50** [comment]
running with `--refresh-dependencies` in 0.4+ will now do this.
