### ISSUE TITLE
Could not find or load main class net.fabricmc.loom.decompilers.fernflower.FabricForkedFFExecutor

### ISSUE THREAD

**Issue by warjort** [FabricMC/fabric-loom#355]
This is a reopening of #288

https://github.com/warjort/fabric-example-mod

The above fork modifies the example mod to use subprojects and the latest loom from maven. 
There is no loom in the root project.
Both "gensources" and "example:gensources" fail to launch the jvm with that classpath error.

**Comment by warjort** [comment]
The workaround is to change "subprojects" to "allprojects" while you generate the sources.

**Comment by modmuss50** [comment]
Im not quite sure what is wrong with the loom code here: https://github.com/FabricMC/fabric-loom/blob/dev/0.6/src/main/java/net/fabricmc/loom/decompilers/fernflower/AbstractFernFlowerDecompiler.java#L103

Unless hasPlugin returns true even if the project has not applied loom?

**Comment by warjort** [comment]
I am far from an expert, but the docs say to use the plugin manager instead of the plugin container.

https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:pluginManager

https://docs.gradle.org/current/dsl/org.gradle.api.plugins.PluginManager.html#org.gradle.api.plugins.PluginManager:hasPlugin(java.lang.String)

**Comment by jakobkmar** [comment]
I have a project with multiple modules, the `genSources` task is executed for each submodule (which I do not want), but already fails at the first submodule with `Could not find or load main class net.fabricmc.loom.decompilers.fernflower.FabricForkedFFExecutor`.

Is there any workaround which allows me to execute genSources normally?

**Comment by modmuss50** [comment]
You should only need to run it for the root module with `gradlew :genSources` note the `:` to specify it for only the root project.

**Comment by jakobkmar** [comment]
should I apply the loom plugin to the root project even though it isn't a fabric mod by itself?

**Comment by warjort** [comment]
> should I apply the loom plugin to the root project even though it isn't a fabric mod of itself?

That is what my workaround suggested above does.
You can revert the change once you've generated the sources.

**Comment by jakobkmar** [comment]
I see, since I would have to specify a Minecraft dependency and so on for the root project as well, I will just run `genSources` in another project for now.

**Comment by modmuss50** [comment]
https://github.com/FabricMC/fabric-loom/pull/511/files Will fix this.
