### ISSUE TITLE
Remap Jar rework

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-loom#358]
- [ ] Allow creating custom batched jar remapping tasks. - Fabric API should be able to remap its testmods jars in a batch when shared caches is enabled.
- [ ] Allow using custom configrations for nested jars - Fabric API should be able to create a fat jar with the testmods in jar
- [x] Fix include warnings when running on gradle 7
- [ ] Expands the tests on this stuff. There are some basic loom tests but these dont cover everything.
- [x] Remove the 2 code paths when using shared caches and not. This code needs quite a bit of cleanup.

**Comment by Juuxel** [comment]
Would it be possible to make it actually support `Jar`'s API instead of just extending it for the file name generation? It would let people do things like `from "myFile.txt"` for just the remapJar task. (IIRC @Chocohead's Loom fork has something like this)

**Comment by modmuss50** [comment]
Humm, yeah that might be useful. I will look into it.
