### ISSUE TITLE
kotlinx.serialization generated serializers not working in remapped jar

### ISSUE THREAD

**Issue by jakobkmar** [FabricMC/fabric-loom#365]
I have a class annotated with `@Serializable` right [here](https://github.com/bluefireoly/fabrikmc/blob/main/fabrikmc-core/src/main/kotlin/net/axay/fabrik/core/math/FabrikPosition.kt), which means that a serializer for that class will be generated when building the project with gradle.

Now the problem is that in every project depending on my API (and using the remapped jar, because of `modImplementation` or because this is the only jar I uploaded to the maven repository) cannot use the serializer generated by the compiler plugin for kotlinx.serialization.

Inside of IntelliJ it just shows that the serializer was not found. When building with Gradle the following error comes up:
`java.lang.AssertionError: Class with incorrect id found: expected net/axay/fabrik/core/math/FabrikPosition.$serializer, actual net/axay/fabrik/core/math/FabrikPosition.serializer`
It seems like there is a problem with the class id.

Why do I know that the remapped jar causes this problem? I assume that this is the case because the serializer is not missing (working normally) in the dev jar.

**Comment by modmuss50** [comment]
I have had a crack at trying to reproduce this without much luck, not sure what im missing. Doesnt help that my knowlage of how kotlin and `@Serializable` is minimal to none.

**Comment by modmuss50** [comment]
A full stack trace would go a long way to help me as well, as I have no idea where that is coming from.

**Comment by jakobkmar** [comment]
> not sure what im missing

The library part is important here, it has to be a serializer provided by a library which is then included using `modImplementation` - it is not reproduceable in one project alone. Did you maybe miss this one?

> A full stack trace would go a long way to help me as well, as I have no idea where that is coming from.

I will try to get one, but I guess that back when this problem appeared there was no additional useful information - I will try it again with the new kotlinx.serialization release!

**Comment by CmdrNorthpaw** [comment]
Here's the full stacktrace that I get when my compile fails: https://paste.ubuntu.com/p/3GpvMc626F/

**Comment by CmdrNorthpaw** [comment]
Just as a quick update the issue is still present on Kotlin 1.5.0 and kotlinx.serialization 1.2.0.

**Comment by Masterzach32** [comment]
I think I might be encountering a similar issue. I have an inline decode function, [`decodeFromByteBuf`](https://github.com/SummerModVenture/SpicyCore/blob/master/common/src/api/kotlin/com/spicymemes/core/api/serialization/ByteBufSerializer.kt), which can be used within the same project fine, but if the remapped jar is used in another mod I get this compile error: https://gist.github.com/Masterzach32/f61e33656b7b2c28f26411e79ac5ea20

**Comment by jakobkmar** [comment]
For the [same class as mentioned in the initial issue comment](https://github.com/jakobkmar/fabrikmc/blob/main/fabrikmc-core/src/main/kotlin/net/axay/fabrik/core/world/pos/FabrikPosition.kt) the generated metadata of **the generated serializer class** currently has this diff when remapped by loom:

(left: remapped | right: the original metadata)
![image](https://user-images.githubusercontent.com/52456572/158677583-ca01934a-7f71-4940-99a3-8dd70ab5918c.png)

This results in the Kotlin compiler (for a mod consuming this library) not knowing that the class is a valid serializer for `FabrikPosition` (in this case).
