### ISSUE TITLE
[BUG] Unable to get certain mods as dependencies properly.

### ISSUE THREAD

**Issue by SelfMadeSystem** [FabricMC/fabric-loom#371]
Same issue as with these two:

https://github.com/FabricMC/fabric-loom/issues/162
https://github.com/FabricMC/fabric-loom/issues/164

The two I tried using are WorldEdit `modImplementation "com.sk89q.worldedit:worldedit-fabric-mc1.16.4:7.3.0-SNAPSHOT"` and BitsAndChisels (from JitPack) `modImplementation 'com.github.CoolMineman:BitsAndChisels:master-SNAPSHOT'`.

If I just use `implementation`, it works but the mods are mapped to the obfuscated mappings, not yarn. Please fix this. This is very frustrating and it's been known for close to two years.

**Comment by SelfMadeSystem** [comment]
I might try to figure out the issue and fix myself if I can figure out how to use gradle properly.

**Comment by modmuss50** [comment]
Humm, I bet its the -SNAPSHOT causing this....

**Comment by modmuss50** [comment]
I have created quite an indpeth intergration test around this to see if I can reproduce it. Sadly ive not been able to...

https://github.com/FabricMC/fabric-loom/pull/372

**Comment by SelfMadeSystem** [comment]
I made a repo w/ the stuff I used. https://github.com/True-cc/FabricTest

**Comment by SelfMadeSystem** [comment]
I tried even using mavenLocal and that doesn't seem to work. (`modImplementation "io.github.coolmineman:BitsAndChisels:2.1.4"`)

**Comment by modmuss50** [comment]
Ok, thanks ill take a look and see if I can reproduce it.

**Comment by modmuss50** [comment]
I have cloned your example and am unable to get the ones that you suggest work to work. They are all failing to resolve trasitive dependencies.

**Comment by SelfMadeSystem** [comment]
On my actual mod, I managed to get the dependencies for the BitsAndChisels mod by including their repos, but not worldedit-fabric. Do you have a discord account? We could chat a lot quicker there.
<details>
  <summary>The BitsAndChisels repos</summary>

```groovy
maven {
    name = "dblsaiko"
    url = "https://maven.dblsaiko.net/"
}
maven {
    name = "Cotton"
    url = "http://server.bbkr.space:8081/artifactory/libs-release/"
}
// REI, odds and ends
maven {
    name = "CurseForge"
    url = "https://minecraft.curseforge.com/api/maven"
}
maven {
    url = 'https://raw.githubusercontent.com/Devan-Kerman/Devan-Repo/master/'
}
maven {
    url "https://www.cursemaven.com"
    content {
        includeGroup "curse.maven"
    }
}
maven { url "https://maven.shedaniel.me/" }
```
</details?

**Comment by modmuss50** [comment]
Yeah the fabric discord (https://discord.gg/v6v4pMv) has a #loom channel. Would like to get the bottom of this.

**Comment by modmuss50** [comment]
Closing this as I have a feeling this was resolved on discord. Please open a new issue with more details if its still an issue.
