### ISSUE TITLE
Questionable annotation remapping in 21w13a

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#377]
Loom remaps the javax nullability annotations (`Nonnull` and `Nullable`) to their JetBrains alternatives (`NotNull` and `Nullable`). This might have some problems in 21w13a as some Minecraft annotations that I've mapped in FabricMC/yarn#2244 use `Nonnull` as a meta-annotation, which the JetBrains annotations don't seem to support at all.

**Comment by modmuss50** [comment]
I cannot really think of a good solution, they wont cause harm not being used, if someone really wants them they add jsr, similar to how it used to work.

**Comment by liach** [comment]
Currently this is the same case in yarn's named jar. Imo we will depend on a different system for annotations since we don't have the same ~~cursed~~ packages as mojang and hence it's unrealistic to reuse their package info annotations.

**Comment by teddyxlandlee** [comment]
It seems that IntelliJ is compatible with Google Findbugs JSR. (I'm not sure.)

**Comment by modmuss50** [comment]
Not seen an actual problem with this, going to close.
