### ISSUE TITLE
A copyright problem

### ISSUE THREAD

**Issue by heipiao233** [FabricMC/fabric-loom#381]
Can I use it to build my project? This project is not a fabric mod!

**Comment by modmuss50** [comment]
Loom is MIT licensed: https://github.com/FabricMC/fabric-loom/blob/dev/0.7/LICENSE

Loom is generally required to build your mod. It is a gradle plugin and not a mod.

**Comment by heipiao233** [comment]
I know and read the MIT License, but it said: "License violations were found"

**Comment by Earthcomputer** [comment]
What said that?

**Comment by Juuxel** [comment]
I would assume that's the licenser gradle plugin applied to some gradle project (no idea what though).

**Comment by heipiao233** [comment]
> What said that?

"gradlew build" command

**Comment by modmuss50** [comment]
In this repo? If so did you add a class and forgot to apply the license header to it?
