### ISSUE TITLE
"got unexpected hash", gradle hangs

### ISSUE THREAD

**Issue by matijakevic** [FabricMC/fabric-loom#384]
Using the [latest](https://github.com/FabricMC/fabric-example-mod/commit/29c522536fc16233833221e22eed3f106c0726bc) `fabric-example-mod`, I receive the following error during configure project task:

`Caused by: java.io.IOException: Downloaded file from http://resources.download.minecraft.net/99/991b421dfd401f115241601b2b373140a8d78572 to C:\Users\Matija\.gradle\caches\fabric-loom\assets\objects\99\991b421dfd401f115241601b2b373140a8d78572 and got unexpected hash of 5160151ce3bf1b5c20e041164b99b4df79c128a4 expected 991b421dfd401f115241601b2b373140a8d78572`

after which gradle hangs.

I tried rerunning it a few times, deleting `%USERPROFILE%/.gradle/caches` files and making a fresh clone of the `fabric-example-mod` repo which didn't help.

I use `AdoptOpenJDK 1.8.0_282`.

**Comment by matijakevic** [comment]
Seems like it was a connection, maybe firewall issue...

**Comment by doinkers** [comment]
This still seems to be happening. I'm using an [existing project](https://github.com/omega-mc/leaf-decay/tree/1.18), and opening it in IntelliJ Community Edition results in this error:

`java.io.IOException: Downloaded file from https://resources.download.minecraft.net/99/991b421dfd401f115241601b2b373140a8d78572 to /home/dinkley/.gradle/caches/fabric-loom/assets/objects/99/991b421dfd401f115241601b2b373140a8d78572 and got unexpected hash of 991b421dfd401f115241601b2b373140a8d78572 expected 991b421dfd401f115241601b2b373140a8d78572`

The 'unexpected' hash and the expected hash _are the same_
![image](https://user-images.githubusercontent.com/105917902/181726713-110b1a92-4b44-4b41-a5fc-45276051f780.png)

EDIT: It looks like this error is non-fatal, as the runClient and build tasks still work just fine.
