### ISSUE TITLE
modCompile does not add to compile

### ISSUE THREAD

**Issue by NikkyAI** [FabricMC/fabric-loom#39]
output of `dependencies`: https://gist.github.com/NikkyAI/5d209104e3b2883322082a4f497d918b

with these dependnecies:

```
dependencies {
    minecraft(group = "com.mojang", name = "minecraft", version = Minecraft.version)

    mappings(group = "net.fabricmc", name = "yarn", version = "${Minecraft.version}.${Fabric.Yarn.version}")

    modCompile(group = "net.fabricmc", name = "fabric-loader", version = Fabric.version)

    modCompile(group = "net.fabricmc", name = "fabric-language-kotlin", version = Fabric.LanguageKotlin.version)

    modCompile(group = "net.fabricmc", name = "fabric", version = Fabric.FabricAPI.version + ".+")

    api(
        group = "org.jetbrains.kotlinx",
        name = "kotlinx-serialization-runtime",
        version = KotlinX.Serialization.version
    )
    shadow(
        group = "org.jetbrains.kotlinx",
        name = "kotlinx-serialization-runtime",
        version = KotlinX.Serialization.version
    ) {
        isTransitive = false
    }

    api(group = "com.github.kittinunf.Fuel", name = "fuel", version = Fuel.version)
    shadow(group = "com.github.kittinunf.Fuel", name = "fuel", version = Fuel.version) {
        isTransitive = false
    }
    api(group = "com.github.kittinunf.Fuel", name = "fuel-coroutines", version = Fuel.version)
    shadow(group = "com.github.kittinunf.Fuel", name = "fuel-coroutines", version = Fuel.version) {
        isTransitive = false
    }
    api(group = "com.github.kittinunf.Fuel", name = "fuel-kotlinx-serialization", version = Fuel.version)
    shadow(group = "com.github.kittinunf.Fuel", name = "fuel-kotlinx-serialization", version = Fuel.version) {
        isTransitive = false
    }

    api(group = "com.github.kittinunf.result", name = "result", version = "2.0.0")
    shadow(group = "com.github.kittinunf.result", name = "result", version = "2.0.0") {
        isTransitive = false
    }

    api(group = "blue.endless", name = "jankson", version = "1.0.0-7")
    shadow(group = "blue.endless", name = "jankson", version = "1.0.0-7") {
        isTransitive = false
    }
}
```

`fabric-language-kotlin` does not even appear in the dependnecies list ?
there is no modCompile section at all (i remember there was one before)

furthermore there seems to be no good way for me to look at which dependnecies `fabric-language-kotlin` bundles and exclude them from shadowjar (even if i add it to `runtimeOnly`)

probably related to #32

**Comment by liach** [comment]
Just add `configurations.compile.extendsFrom configurations.modCompile` for now?

**Comment by NikkyAI** [comment]
another problem is that it should be `api` in the first place, so if that could be fixed while it gets changed that would be nice

**Comment by liach** [comment]
We need `modApi` and `modImplementation` then.

**Comment by NikkyAI** [comment]
```kotlin
configurations.runtimeOnly.extendsFrom(configurations.modCompile)
```

this works well for me

what would be the difference between api and implementation for mods ? its not like mod dependencies are like normal dependencies..

**Comment by NikkyAI** [comment]
well.. for a while now i have been trying to get this solution to work again and failed,
seems like somehow gradle 5 or maybe the changes in remapping modCompile dependencies made it stop working

**Comment by liach** [comment]
hmm, must you use implementation or api in gradle 5

**Comment by NikkyAI** [comment]
it works when you copy the dependency with implementations but not extending the configuration with modCompile anymore

i assume that this is correct in the pom though ?
```xml
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-coroutines-core</artifactId>
      <version>1.0.1</version>
      <scope>runtime</scope>
    </dependency>
```

offtopic: should we possibly add modCompile as scope here ? would gradle be able to pick that up ?

**Comment by modmuss50** [comment]
This seems to be have been fixed, please open a new issue if its still an issue.
