### ISSUE TITLE
Enhancement: Task for updating dependencies

### ISSUE THREAD

**Issue by actuallyasmartname** [FabricMC/fabric-loom#390]
You know, like updating Minecraft dependencies with a task like ./gradlew updatemcDeps or something. Probably should update the Minecraft version, yarn mappings, and fabric api.

**Comment by modmuss50** [comment]
This isnt really possible as there isnt a strict definition of where these values are located with gradle.

It would be more suited to a custom task or an external tool IMO.

**Comment by dexman545** [comment]
There are tools for it, both inside and outside gradle.
You could also write your own version checks/updates within your gradle script.

Be careful with auto-updates, Loom's deps don't seem to handle Gradle's dep locking mechanic very well.

**Comment by modmuss50** [comment]
> Loom's deps don't seem to handle Gradle's dep locking mechanic very well.

Can you expand on that? I dont quite understand what you mean?

**Comment by dexman545** [comment]
> > Loom's deps don't seem to handle Gradle's dep locking mechanic very well.
> 
> Can you expand on that? I dont quite understand what you mean?

Last time I tried to use dep locking, gradle failed to perform the locking due to either Minecraft or yarn (I forget which, it is one Loom adds). I don't have the error handy, and I gave up on that method as it looked nontrivial to fix/workaround, though I may have missed something obvious.

**Comment by actuallyasmartname** [comment]
> This isnt really possible as there isnt a strict definition of where these values are located with gradle.
> 
> It would be more suited to a custom task or an external tool IMO.

Closing.
