### ISSUE TITLE
DownloadUtil assumes that the passed-in URL is HTTP or HTTPS, and crashes on file:// URLs

### ISSUE THREAD

**Issue by coderbot16** [FabricMC/fabric-loom#391]
This complicates any attempt to point the intermediary URL at a local file on the disk.

https://github.com/FabricMC/fabric-loom/blob/12ac6cfcfe94fc3dd7029b18207b61c27effdea4/src/main/java/net/fabricmc/loom/util/DownloadUtil.java#L63

**Comment by modmuss50** [comment]
I want to revisit the download util. I’ll keep this in mind

**Comment by Chocohead** [comment]
For reference the project I loaned `DownloadUtil` from dispatched based on `URL` protocol before hand given FTP and local files don't really download in the same sense.

**Comment by modmuss50** [comment]
Im unsure on where this is an actuall issue, please open a new bug report with a usecase.
