### ISSUE TITLE
Dependency remap fails to remap accesswidener to named

### ISSUE THREAD

**Issue by official-markus-maurer** [FabricMC/fabric-loom#392]
I receive this error when trying to run the game.

[message.txt](https://github.com/FabricMC/fabric-loom/files/6407156/message.txt)

These are my dependencies.

[My build.gradle.txt](https://github.com/FabricMC/fabric-loom/files/6407149/My.build.gradle.txt)

**Comment by modmuss50** [comment]
This is a loader issue.
