### ISSUE TITLE
Incompatibility with dependencyResolutionManagement setting in gradle

### ISSUE THREAD

**Issue by Logiquo** [FabricMC/fabric-loom#395]
It seems that loom is incompatible with `dependencyResolutionManagement`. The problem is the same as the one described in this issue  https://github.com/gradle/gradle/issues/15754.

To summarize, the three options in `dependencyResolutionManagement` are
- `FAIL_ON_PROJECT_REPOS`: a repository declared in the project will trigger a build error.
- `PREFER_PROJECT`: ignore repository declared in the settings.
- `PREFER_SETTINGS`: ignore repository declared in the project.
based on documentation https://docs.gradle.org/current/javadoc/org/gradle/api/initialization/resolve/RepositoriesMode.html

Since loom declared its repository in the plugin, it will cause `FAIL_ON_PROJECT_REPOS` and `PREFER_SETTINGS` not to work. However, `PREFER_PROJECT` will cause the Gradle to ignore the repository declared in the settings, which can be problematic for large projects.

One solution might be to not declare a repo in the plugin, but I am not sure if it is possible.

**Comment by liach** [comment]
The idea on moving away from hardcoded repos and declaring them in setting gradle does have advantages, like people can then use proxy maven for minecraft or fabric stuff. I personally support doing so, but there are other hardcoded components, like the launchermeta for minecraft.

On this setting thing, it's weird that gradle doesn't allow repositories to be declared in both places with this update.

**Comment by Logiquo** [comment]
I think the solution for this problem should similar to https://github.com/SpongePowered/VanillaGradle/blob/7b86f75197363cf725c4351dd5a46de62e021c4b/src/main/java/org/spongepowered/gradle/vanilla/VanillaGradle.java
Make the loom both works for settings and project, and when the plugin applies on settings it add dependency and when the plugin applies to the project it does other stuff.

**Comment by liach** [comment]
I suggest shipping an additional plugin that sets the repositories for the settings than making the same plugin work for both environments like sponge does. having the same plugin target two different things is quite confusing.

**Comment by Logiquo** [comment]
Currently many repos (i.e. repos related to mappings) depend on the configuration in the projects. Without a local repo re-structure, it is impossible to make the loom work with dependencyResolutionManagement. Not matter we choose to use the same plugin or use another plugin for repos. I think it is necessary to remove the project-configuration-specific-name in the path of the repo.

**Comment by Logiquo** [comment]
> I suggest shipping an additional plugin that sets the repositories for the settings than making the same plugin work for both environments like sponge does. having the same plugin target two different things is quite confusing.

To have compatibility with the people who choose not to use dependencyResolutionManagement, the plugin needs to have the ability to declare repos in the project. Thus, the idea is if depedencyResolutionManagement is used, the repo will be declared in the settings, and if it is not used, the repo needs to be declared in the project. These two parts of the code share a great similarity, hence it makes sense to write them in the same plugin. Thus, I would prefer a solution similar to sponge vanillagradle.

**Comment by liach** [comment]
The new plugin will be used exclusively to declare repos. Another good thing about a separate plugin is that people might use mirror repos, especially like in china or in offline development. @modmuss50 What's your opinion on this?

**Comment by modmuss50** [comment]
I really don’t know enough about it to provide any useful input right now. When I get a chance I’ll take a look.

There is a huge amount of work to get loom up to speed with the new gradle changes. I do have a future/dev branch where I have started on the easy bits.

**Comment by Logiquo** [comment]
> The new plugin will be used exclusively to declare repos. Another good thing about a separate plugin is that people might use mirror repos, especially like in china or in offline development. @modmuss50 What's your opinion on this?

Ok, I see want you mean. I think this is a reasonable design decision, and actually, the vanillagradle use the same strategy, they have two different plugins that serve these two purposes separately, one is `MinecraftRepositoryPlugin` which only do the repo declaration and another one is `VanillaGradle` which only do the non-repo-declaration stuff. They just choose to ship them together, but the code structure is completely separated, and you may compile them into two irrelevant plugins if you want to.

**Comment by Logiquo** [comment]
Regardless, the structure for the local repos need to be changed. The current problem is the path of some local repo involves the configuration of the project. Then there are only two solutions
1. We somehow mimic this configuration of the project in the settings file (I currently don't know how to do it, please tell me if this is possible).
2. We restructure the location of local repos so that the path of them does not involve any configuration of the project, i.e. the path of the repo becomes static (I prefer this one).
@liach any suggestion on this one?

(I am currently working on bringing the support of dependencyResolutionManagement to loom, but stuck on this problem)

**Comment by liach** [comment]
For the local repositories, I think we looked at [artifact transforms](https://docs.gradle.org/current/userguide/artifact_transforms.html). Maybe we are now forced to use it.

**Comment by Logiquo** [comment]
Hi, I have solved all other places for repo declarations except 
https://github.com/FabricMC/fabric-loom/blob/9fb167d50622af561efb9cc91150126ba87a66f2/src/main/java/net/fabricmc/loom/configuration/LoomDependencyManager.java#L196-L205
The problem is that in order to read the correct JSON file, a configuration in the project needs to be read. This makes sense since each JSON file should be project-specific. However, this creates a problem since there is nothing identical in the settings phase. 

I am thinking that we could just skip these lines if the central repository setting is used, as the user could declare those repositories manually in the settings. (And this is what the central repository is for, right?)

@liach any suggestion on this one?

**Comment by liach** [comment]
In this case, I guess an acceptable approach is to print out that url from json and declare that you are missing that repo and have to add it. This way imo fits the reasoning of gradle controlling the source of artifacts and loom wanting you to include the repos

**Comment by Logiquo** [comment]
This is fixed by #400 .
