### ISSUE TITLE
Cant Update to Loom 0.8 Because of an error

### ISSUE THREAD

**Issue by Blobanium** [FabricMC/fabric-loom#398]
Apologies if i opened this issue in the wrong repo

So im trying to port my mod (Loading Timer) to 21w19a on my 1.17 branch which required me to update Loom to version 0.8. however, it seems that it won't compile my mod because of this error. 

![Capture](https://user-images.githubusercontent.com/45613796/118056296-8a9fba00-b33e-11eb-9b84-867517103191.PNG)

And here are things that i tried

- Using Java 16 to compile using gradle (And i ensured it was java 16, that didnt work(Image below for proof))
![Capture](https://user-images.githubusercontent.com/45613796/118057547-0c90e280-b341-11eb-85f2-cf293eac0165.PNG)

- i also tried doing some other things which also didnt work(Updating gradle and everything else).

And for some reason committing it to github seems to compile it just fine (https://github.com/Blobanium/Loading-Timer/runs/2571013166) So im thinking if it is something to do with my local machine or something else i might have did wrong.

**Comment by haykam821** [comment]
Make sure Java, Gradle, and Loom are all using their latest versions, and then run with the `--refresh-dependencies` flag.

**Comment by Blobanium** [comment]
> Make sure Java, Gradle, and Loom are all using their latest versions, and then run with the `--refresh-dependencies` flag.

I made sure, java seems to be using JDK version 16.0.1+9, Gradle is on 7.0.1, and Loom Seems to be using 0.8 and still getting no luck..

**Comment by triphora** [comment]
Same issue here. IDE and everything is 16; all I did was change loom version in build.gradle from `0.7-SNAPSHOT` to `0.8-SNAPSHOT`, and target versions from 1.8 to 16.

**Comment by ghost** [comment]
Your IDE isn't using java 16 to run gradle.
If your using intellij nagivate to: `File -> Settings -> Build, Execution, Deployment -> Build Tools -> Gradle` and change the `Gradle JVM` to java 16. 
![image](https://user-images.githubusercontent.com/5214513/118084925-692fe400-b3b9-11eb-8c64-0b6a6893448c.png)

There probably is a way to change this in gradle but I'm not aware of any as of yet.

**Comment by Blobanium** [comment]
> Your IDE isn't using java 16 to run gradle.
> If your using intellij nagivate to: `File -> Settings -> Build, Execution, Deployment -> Build Tools -> Gradle` and change the `Gradle JVM` to java 16. 
> ![image](https://user-images.githubusercontent.com/5214513/118084925-692fe400-b3b9-11eb-8c64-0b6a6893448c.png)
> 
> There probably is a way to change this in gradle but I'm not aware of any as of yet.

What about for visual studio code? which is the IDE I use. I don't use intellij

**Comment by triphora** [comment]
> Your IDE isn't using java 16 to run gradle.
> If your using intellij nagivate to: `File -> Settings -> Build, Execution, Deployment -> Build Tools -> Gradle` and change the `Gradle JVM` to java 16.
> snip
> 
> There probably is a way to change this in gradle but I'm not aware of any as of yet.

I already have that set to 16. Same exact error.

**Comment by haykam821** [comment]
Is your Gradle wrapper updated to 7.0.1 as well?

**Comment by Blobanium** [comment]
> Is your Gradle wrapper updated to 7.0.1 as well?

yes correct

**Comment by triphora** [comment]
@Blobanium So it turns out it was just an issue on my local system. Running with GitHub Actions, it (appears?) to work fine, so maybe just clear your caches or something?
https://github.com/wafflecoffee/prideflags/actions/runs/847178970

**Comment by modmuss50** [comment]
Loom 0.8 requires gradle 7+ and Java 16. If you are sure you are running on those versions try running with `--refresh-dependencies` as this usually solves the weird issues.
