### ISSUE TITLE
Support Java 8 

### ISSUE THREAD

**Issue by QuImUfu** [FabricMC/fabric-loom#402]
Java 8 is still updated and the most reliably working version of java, especially for older versions of Minecraft (I know of Minecraft 1.12.2 mods not working on anything newer!), and AFAIK the one shipped with Minecraft.  
As a Gradle plugin for the development of mods for serval Minecraft versions supported by Fabric, loom should IMO (baring technical infeasibility) continue to support Java 8 until updates for that platform are discontinued.

**Comment by frqnny** [comment]
MC’s latest snapshot is now on java 16, so 1.17 will be the first major version to use java 16. There is no reason to support older java now that minecraft itself won’t even be able to run on it. Close this issue.

**Comment by ghost** [comment]
Java 8 can still be used for development and running minecraft using loom however it now requires using gradle's toolchains feature and a bit of configuration.

**Comment by modmuss50** [comment]
Loom 0.7 will contiune to work with support for Java 8 and gradle 4.9 through to 7.0+. Any issues found can still be fixed there.

You can also use Loom 0.8 to target mods for java 8 but you will need to run it on Java 16 to do so.

With loom 0.8 we took the jump to require Gradle 7 and Java 16 for a few reasons, partly becuase we want to make use of the new featues when developing loom + related tools and it also reduces the testing surface.

Fabric has never supported 1.12, and all versions we do support (1.14 for example) will run on the latest java versions.
