### ISSUE TITLE
modImplementation cannot accept local files

### ISSUE THREAD

**Issue by valoeghese** [FabricMC/fabric-loom#403]
A lib I was using had problems with its maven, so, naturally, I downloaded the jar and added it with a fileTree for all jars in the libs folder. But, it silently failed to add it to my workspace
Assuming it was just fileTree, I then included it manually with `files`, but that, too, failed.
I ended up needing to use regular `implementation` to get it onto the classpath! This is stupid.
Using Loom 0.7.30, minecraft 1.16.5
Likely related to #391
Please fix when possible

**Comment by valoeghese** [comment]
Almost definitely related to #250

**Comment by Juuxel** [comment]
Yeah, this is pretty much the same issue as #250. AFAIK you can work around this by using a `flatDir` repository instead. (Not related to #391 by the way, `DownloadUtil` is not used for dependencies)
