### ISSUE TITLE
Cannot sign mods

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [FabricMC/fabric-loom#404]
When trying to sign a mod using the gradle signing plugin and creating a simple signing task like 
```gradle
signing {
    sign configurations.archives
}
```
I get a weird error that seems to imply the `remapSourcesJar` task is making the `signArchives` task depend on another task while it's already running as you can see in this error right here:
```gradle
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':remapSourcesJar'.
> Cannot call Task.dependsOn(Object...) on task ':signArchives' after task has started execution.
```

My entire build.gradle file (excluding the publishing task as that has no impact anyway) can be found here: https://gist.github.com/PlanetTeamSpeakk/ab75ec6c45fbd9e1d699220552099b2f

**Comment by PlanetTeamSpeakk** [comment]
Upon further attempts, I've noticed that putting 
```gradle
signing {
	sign publishing.publications.mavenJava
}
```
after the publishing task does work just fine.
I'm assuming that's because at this point the jars have already been created, it doesn't sign them until you try to upload whereas the former method signs them on the go which Loom does not seem to cooperate with.  
In this case my build.gradle looks like this: https://gist.github.com/PlanetTeamSpeakk/fbdb067f6c505f231d71174a97afcf81

**Comment by OroArmor** [comment]
https://github.com/OroArmor/Oro-Config, https://github.com/OroArmor/Multi-Item-Lib, https://github.com/OroArmor/oro-mod-template, https://github.com/OroArmor/PortalHelper, and https://github.com/OroArmor/CustomItemRangeCombination all have working signing for mods. While most of these are all for Loom 0.6, the process should hopefully be the same.

**Comment by PlanetTeamSpeakk** [comment]
> https://github.com/OroArmor/Oro-Config, https://github.com/OroArmor/Multi-Item-Lib, https://github.com/OroArmor/oro-mod-template, https://github.com/OroArmor/PortalHelper, and https://github.com/OroArmor/CustomItemRangeCombination all have working signing for mods. While most of these are all for Loom 0.6, the process should hopefully be the same.

Well, the uploadArtifacts task is gone in Gradle 7, I believe, so the publishing process is not the same. The signing process, however, does not appear to work on my end with Loom 0.8, haven't tested with Loom 0.6 tho.

**Comment by OroArmor** [comment]
yes, you can look at https://github.com/OroArmor/java-vulkan for a gradle 7 publishing, but it is not mod related

**Comment by PlanetTeamSpeakk** [comment]
> yes, you can look at https://github.com/OroArmor/java-vulkan for a gradle 7 publishing, but it is not mod related

Not saying you can't publish anymore, just not with the uploadArtifacts task anymore as that's gone. I too now use the publishing task instead.

**Comment by OroArmor** [comment]
No, im saying that my layout works for loom 6, and then something else for gradle 7. If I am remembering correctly, you need to order your steps correctly, with signing above the other tasks.

**Comment by modmuss50** [comment]
```
signing {
	sign publishing.publications.mavenJava
}
```

Is the way to go I think, and what the gradle signing docs suggest. I have started adding an intergration test for this, so will leave this ticket open until thats done.

**Comment by modmuss50** [comment]
I have added an intergration test for this and it seems to work as expected, and you have provided a fix yourself. Going to close this ticket for now, please open a new one if you come across any more issues.
