### ISSUE TITLE
migrateMappings task adding incorrect imports for record classes

### ISSUE THREAD

**Issue by ishland** [FabricMC/fabric-loom#405]
Using loom 0.8.8, I sometimes get some pointless extra imports that cause compilation failures. 
All source files with record classes contains `import record;` and sometimes contains additional `import <record class name>;`

**Comment by modmuss50** [comment]
[Mercury ](https://github.com/CadixDev/Mercury)is the tool loom uses to handle source remapping, it might be worth opening an issue there as I doubt its a loom issue. (Please correct me if im wrong).

https://github.com/CadixDev/Mercury/issues/40 seems possibly related.
