### ISSUE TITLE
Sources don't attach with vscode and 0.8

### ISSUE THREAD

**Issue by CoolMineman** [FabricMC/fabric-loom#407]
I can't get sources to attach with vscode since I switched to 1.17 and loom 0.8
I've tried everything:
- update project
- using cfr
- nuking the whole workspace
- restarting vscode
- restarting my computer
The sources jar is generating but not attaching

**Comment by modmuss50** [comment]
There are also issues when using eclipse, I will take a look into this.

**Comment by modmuss50** [comment]
I can reproduce this in vscode and eclipse, as for why and what the fix is im unsure.

**Comment by modmuss50** [comment]
Should be fixed now, I will look into adding a test for this to ensure it does not regress.
