### ISSUE TITLE
Use More Threads

### ISSUE THREAD

**Issue by gudenau** [FabricMC/fabric-loom#42]
During the setup process gradle starts up four worker threads, often times only one is doing any actual work. Would be nice if the load was distributed for multi-threaded systems to decrease build times.

**Comment by modmuss50** [comment]
To be honest most things cannot be multi threaded in loom as in most cases tasks need files to be created.

Stuff like the asset downloading could be made parallel however

**Comment by gudenau** [comment]
I would assume the remapping could be done as well, load the database and then split the classes into different threads.

**Comment by modmuss50** [comment]
We looked at multithreading FF but this wasnt possible. For now its as good as its going to be. If someone finds a specific part of loom that could make sure of more threads please open another issue.
