### ISSUE TITLE
Patch in ARM64 LWJGL natives

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-loom#426]
An increasing number of people are using Apple Silicon macs that use the ARM64 architecture, right now there is a manual way to use custom natives but loom can/should replace the x64 with either officially or custom build arm natives.

To use offical natives we may need to update LWJGL I dont know if this is possible atm.

**Comment by kloenk** [comment]
Interesting here would be codesinging. If you just replace the natives, macOS will complain

**Comment by modmuss50** [comment]
Yes I’d prefer to use the officially built natives but that will require updating LWJGL. Hopefully that should work.

**Comment by kloenk** [comment]
Official as build by Microsoft or build by lwjgl Organisation

**Comment by modmuss50** [comment]
LWJGLs

**Comment by tasgon** [comment]
@modmuss50 Could you share the manual method? I've found https://github.com/yusefnapora/m1-multimc-hack, but I've been struggling to apply those changes to a development environment.

**Comment by modmuss50** [comment]
1. Download the natives that I have built 
[modmuss50-LWJGL-natives-arm64-macos.zip](https://github.com/FabricMC/fabric-loom/files/6800928/modmuss50-LWJGL-natives-arm64-macos.zip) others may work, but mine are known to be working.
2. Extract those to a folder, and make a note of the path.
3. Set that path in `~/.gradle/gradle.properties` (create the file if it does not exist) by adding `fabric.loom.natives.dir=/Users/user/Desktop/natives`.
Runing  `echo "fabric.loom.natives.dir=/Users/user/Desktop/natives" >> ~./gradle/gradle.properties` should do it for you, of course update the path to where you extracted them to.
4. Refresh gradle pjoect in your IDE and make sure you are using native java.


EDIT: This is no longer required with Loom 0.11 (or 0.12 if you are using Minecraft 1.19 or newer)

**Comment by 3TUSK** [comment]
> To use offical natives we may need to update LWJGL I dont know if this is possible atm.

Only possible with latest LWJGL 3.3.0 ***snapshot*** versions. LWJGL 3.3.0 snapshot version builds may be found on either LWJGL's own website (listed in ["Customize"](https://www.lwjgl.org/customize) tab, or [here](https://www.lwjgl.org/browse/nightly/bin) without any version information) or [SonaType's snapshot repo](https://oss.sonatype.org/#view-repositories;snapshots~browsestorage~org/lwjgl/lwjgl/3.3.0-SNAPSHOT/). I am not certain about the origin of those builds on SonaType, though.

IIRC, using these LWJGL 3.3.0 snapshot builds in vanilla lead to crashes; in my own testing, a coremod in any form is needed to workaround those crashes. 

------

This issue is reported in Loom repo. Loom is a dev-facing tool set. What about regular users? Is "substituting correct native libs in regular Fabric installer" a priority?

**Comment by modmuss50** [comment]
> LWJGL 3.3.0 snapshot builds in vanilla lead to crashes

Ughh I had hoped that would not be the case, I dont really fancy auto downloading unsigned natives that I have built. I wonder if this is something LWJGL could fix? im not too sure how much they care about backwards compat.

**Comment by 3TUSK** [comment]
IIRC the crash I encountered is related to Minecraft calling `glfwSetWindowIcon` somewhere, and GLFW starts to [give error instead of silence](https://github.com/glfw/glfw/commit/9a87c2a4b49808d3666c7b093b77e8512fa23908#diff-b37cd88f1337abc4ba24aaef1fffbbdcb1d7fbae309d299bed6a140ec5ee77c9L985-R986), and Minecraft decides to throw an exception whenever GLFW errors. 
IMHO it is up to Minecraft/Mojang to adopt the change. My own workaround is to skip the call.

**Comment by modmuss50** [comment]
I agree, I dont think there is much we can do here then. Could possibly look into making loom make a similar patch to yourself but its kinda gross. For now I think this needs to say on the backburner. The workaround is to use the natives that I built.

**Comment by sargunv** [comment]
This worked for me, but I had to go through a bunch of start, crash, start, crash cycles to allowlist all the unsigned libraries with macOS in System Preferences. Here's a workaround to streamline that process: https://github.com/Jackett/Jackett/issues/5589#issuecomment-508560798

**Comment by ezfe** [comment]
@3TUSK That issue was fixed in 1.18

**Comment by modmuss50** [comment]
Yes, that was fixed in 1.18, so does hint that they may have been looking at updating LWJGL and/or adding official ARM support.

I have a WIP PR to loom here: <https://github.com/FabricMC/fabric-loom/pull/554> That updates LWJGL and adds in the arm natives (windows, mac and linux). My plan it to make a small mod to fix the window icon crash for macos, and get loom to include that when required.

**Comment by modmuss50** [comment]
In 0.11 loom this should now "just work" for ARM machines on Windows, MacOS and Linux.

**Comment by woodenlalaloo** [comment]
> 1. Download the natives that I have built
>    [modmuss50-LWJGL-natives-arm64-macos.zip](https://github.com/FabricMC/fabric-loom/files/6800928/modmuss50-LWJGL-natives-arm64-macos.zip) others may work, but mine are known to be working.
> 2. Extract those to a folder, and make a note of the path.
> 3. Set that path in `~/.gradle/gradle.properties` (create the file if it does not exist) by adding `fabric.loom.natives.dir=/Users/user/Desktop/natives`.
>    Runing  `echo "fabric.loom.natives.dir=/Users/user/Desktop/natives" >> ~./gradle/gradle.properties` should do it for you, of course update the path to where you extracted them to.
> 4. Refresh gradle pjoect in your IDE and make sure you are using native java.
> 
> Let me know if you have any issues.

its kind of complicated and i was wondering if you could explain them better
like i dont understand what natives are or how to replace them

**Comment by birbe** [comment]
> > 1. Download the natives that I have built
> >    [modmuss50-LWJGL-natives-arm64-macos.zip](https://github.com/FabricMC/fabric-loom/files/6800928/modmuss50-LWJGL-natives-arm64-macos.zip) others may work, but mine are known to be working.
> > 2. Extract those to a folder, and make a note of the path.
> > 3. Set that path in `~/.gradle/gradle.properties` (create the file if it does not exist) by adding `fabric.loom.natives.dir=/Users/user/Desktop/natives`.
> >    Runing  `echo "fabric.loom.natives.dir=/Users/user/Desktop/natives" >> ~./gradle/gradle.properties` should do it for you, of course update the path to where you extracted them to.
> > 4. Refresh gradle pjoect in your IDE and make sure you are using native java.
> > 
> > Let me know if you have any issues.
> 
> its kind of complicated and i was wondering if you could explain them better like i dont understand what natives are or how to replace them

it seemed perfectly explained, I was able to do it easily

**Comment by ezfe** [comment]
I've created a Fabric profile that is pre-patched for 1.18.1 here:

https://gist.github.com/ezfe/f63a11ffae3cf4d92ad299fcf3869db8

It is created by taking the non-ARM Fabric installation and applying its changes from the base 1.18.1 JSON file to [this](https://gist.github.com/ezfe/8bc43a65e16b79c955f81b4d7fa4ae6a) JSON file modified for ARM support. You'll still need to assign an ARM build of Java 17.

**Comment by unnamedlife** [comment]
> 

I need help on how to do this i'm an absolute monkey

**Comment by modmuss50** [comment]
Updating to loom 0.11 (or 0.12 if you are using the 1.19 snapshots) will do everything for you. My original method is no longer required.
