### ISSUE TITLE
Changing your mappings prevents you from going back to a previous version of the mappings that you have used

### ISSUE THREAD

**Issue by RedstoneParadox** [FabricMC/fabric-loom#43]
Essentially, if you were to update to the latest mappings version and then go back to the previous version, for example, attempting to do so will throw an error saying that the jar file for the previous mappings cannot be deleted because it is in use by another program.

**Comment by RedstoneParadox** [comment]
Deleting the jar file manually seems to fix it.

**Comment by modmuss50** [comment]
Closing as this is really old, and ive not seen it happen. Open a new issue if its still an issue.
