### ISSUE TITLE
Java 16 not working?

### ISSUE THREAD

**Issue by Orangenal-name** [FabricMC/fabric-loom#435]
I am trying to make a fabric mod, but I cannot even start, as for some reason, when I launch vscode, it comes up with this error:
```
 {
	"resource": "/C:/Users/USERNAME/Documents/mod/build.gradle",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "0",
	"severity": 8,
	"message": "Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.0.2-bin.zip'.\r\nBuild file 'C:\\Users\\USERNAME\\Documents\\mod\\build.gradle' line: 2\r\nAn exception occurred applying plugin request [id: 'fabric-loom', version: '0.8-SNAPSHOT']\r\nFailed to apply plugin 'fabric-loom'.\r\nYou are using an outdated version of Java (15). Java 16 or higher is required.\nThe JAVA_HOME environment variable is currently set to (C:\\Program Files\\Java\\jdk-16.0.1).",
	"source": "Java",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}
```
It says I am using Java 15, when I have Java 16.0.1 installed.

**Comment by Orangenal-name** [comment]
If this should instead be an issue reported with gradle please let me know because I cannot find a way to fix this on my own and I need as much help as I can get

**Comment by Technici4n** [comment]
Make sure your JAVA_HOME environment variable is pointing at the java 16 install.

**Comment by Orangenal-name** [comment]
That didn't do anything. Same error, just different java home path

**Comment by Technici4n** [comment]
Hmmm right, I guess vscode is using the wrong version of java?

**Comment by Orangenal-name** [comment]
After playing around for ages it seems to have fixed itself, however, even though the project is on a shared drive my other computer still has the issue and I can only code on one of them even though both have the same version of java?
