### ISSUE TITLE
Unable to upgrade from 1.17 to 1.17.1

### ISSUE THREAD

**Issue by zfxstd** [FabricMC/fabric-loom#437]
Hello.
I have strange error. Im using idea and i have problem with updating mod envirovement to 1.17.1.
When im changing the versions of  minecraft and mappings, the following error appears in console. Im using this website for versions: https://fabricmc.net/versions.html
After the gradle task is done, whole "net.minecraft" package is just gone and im unable to complie and run the mod. 
I just tried on clean instance (https://github.com/FabricMC/fabric-example-mod) and i have same error. 

There is error message:

```
> Configure project :
Fabric Loom: 0.8.20
:remapping 46 mods (TinyRemapper, intermediary -> named)
:remapping sources
Status ERROR: org.eclipse.jdt.core code=4 Could not retrieve declared methods org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type net.minecraft.class_2960 cannot be resolved. It is indirectly referenced from required .class files
Could not remap fabric-content-registries-v0-0.2.2+a02b446318-sources.jar fully!
java.lang.ArrayIndexOutOfBoundsException

BUILD SUCCESSFUL in 15s
```

**Comment by modmuss50** [comment]
I think it is safe to ingore this error for now. Hopefully when we update mercury and/or JDT this will be fixed.

**Comment by zfxstd** [comment]
But which reason to be this happened? i mean, i know some mods which are compiled with 1.17.1... Is there anything what i may do from my side ( local for example ) to fix this problem?
