### ISSUE TITLE
Automatic refmaps aren't added to mixin jsons if the name is not *.mixins.json

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#448]
Before #423, mixin jsons were scanned by their contents (whether they contained `mixins`, `client` or `server`). This allowed them to have pretty much any name that doesn't match the most popular `*.mixins.json`. Some Fabric mods, like [Adorn](https://github.com/Juuxel/Adorn/blob/1.16/src/main/resources/mixins.adorn.json) or [Litematica](https://github.com/maruohon/litematica/blob/master/src/main/resources/mixins.litematica.json) use prefix notation for their mixins instead. (For example, due to the MCDev IDEA plugin not supporting `*.mixins.json` in the past)

If a mixin JSON still uses this naming or any other naming pattern that does not end in `.mixins.json`, the `refmap` property isn't automatically added to the mixin json, since `*.mixins.json` is hardcoded in Loom:
https://github.com/FabricMC/fabric-loom/blob/b558ee1a4604a0fbf0eba8edab401f2a831e4fb6/src/main/java/net/fabricmc/loom/extension/MixinApExtensionImpl.java#L62

There are three possibly fixes to this:
1. Reading the mixin json paths by the contents. This is cursed and not really efficient, either. (It reads all top-level json files in the jar)
2. Reading the mixin json paths from a fabric.mod.json (possibly in addition to a pattern). This is the most reliable way to catch the mixin jsons.
3. Switching to a more sophisticated pattern, like in modern MCDev (minecraft-dev/MinecraftDev#691)

**Comment by Logiquo** [comment]
My bad. I didn't notice the possibility that a mixin json file could end with other things. I will start a fix once I got time.

**Comment by modmuss50** [comment]
Great, I would just revert it back to how it worked in the past.
