### ISSUE TITLE
Global Access Wideners

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-loom#450]
This is an issue to keep track of ideas for global access wideners:

- Be specified with a `global-` prefix in the aw file. Doesnt require any changes to loader (other than an AW update)
- Apply comments to the generated source with the modid on each member that has had it access changed.
- Add an option to exclude modid's for when you depend on optional mods

**Comment by shartte** [comment]
@modmuss50 probably done, right?

**Comment by modmuss50** [comment]
Yes. Thanks.
