### ISSUE TITLE
Option to disable mixin annotation processor

### ISSUE THREAD

**Issue by ScorchedPsyche** [FabricMC/fabric-loom#456]
### Context
I've developed a suite of plugins initially to Bukkit, however decided to move to Fabric. In order to not waste the work I had already done for Bukkit I've decided to create a **Multi-Platform (Bukkit, Fabric, etc) and Multi-Project setup that would contain all the modules in one repository** which is located here: https://github.com/ScorchedPsyche/scorchedcraft

### Project Structure (of the relevant parts)
```
scorchedcraft
├── build.gradle
├── settings.glade
├── scorchedcraft-bukkit
│   ├── ...
├── scorchedcraft-fabric
│   ├── ...
│   └── worlds
│       └── build.gradle
│       └── gradle.properties
│   └── build.gradle
├── scorchedcraft-shared
│   ├── ...
│   └── worlds
│       └── build.gradle
│       └── gradle.properties
```

### The issue
The issue was located on **scorchedcraft-shared.worlds** project (**worlds**, child of **scorchedcraft-shared**). I just wanted to include the mappings to the shared module so that I'd have access to NMS, so to my dependencies on **build.gradle** from **scorchedcraft-shared.worlds** I added:

- **build.gradle** dependencies for **scorchedcraft-shared.worlds**:
```
dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
}
```

However, that alone was making **gradlew build** fail with the following error:
```
Execution failed for task ':scorchedcraft-shared:worlds:compileJava'.
> java.lang.NoClassDefFoundError: org/objectweb/asm/tree/MethodNode
```

The root cause is that the Fabric Loader has these configurations for the annotation processor: https://github.com/FabricMC/fabric-loader/blob/master/build.gradle#L49-L54

- build.gradle for Fabric Loader:
```
// Required for mixin annotation processor
annotationProcessor "org.ow2.asm:asm:${project.asm_version}"
annotationProcessor "org.ow2.asm:asm-analysis:${project.asm_version}"
annotationProcessor "org.ow2.asm:asm-commons:${project.asm_version}"
annotationProcessor "org.ow2.asm:asm-tree:${project.asm_version}"
annotationProcessor "org.ow2.asm:asm-util:${project.asm_version}"
```

### The solution
The solution was to add the following code to **scorchedcraft-shared.worlds**:

- add the following dependencies at **build.gradle** for **scorchedcraft-shared.worlds**:
```
// Required for mixin annotation processor
annotationProcessor "org.ow2.asm:asm:${project.asm_version}"
annotationProcessor "org.ow2.asm:asm-analysis:${project.asm_version}"
annotationProcessor "org.ow2.asm:asm-commons:${project.asm_version}"
annotationProcessor "org.ow2.asm:asm-tree:${project.asm_version}"
annotationProcessor "org.ow2.asm:asm-util:${project.asm_version}"
```

- add the following property at **gradle.properties** for **scorchedcraft-shared.worlds**:
```
asm_version = 9.1
```

### Suggestion
Add a way to disable this so that mapping can be added without extra and unneeded dependencies for this use-case.

### Final comments
I hope this is well put together. If anything more is needed let me know and I'll add to the issue!

Thanks to @modmuss50 for helping with finding the root cause and solution for this use-case's issue.

**Comment by modmuss50** [comment]
This is possible with:

```
loom {
	mixin {
		useLegacyMixinAp = true
	}
}
```
