### ISSUE TITLE
0.2.0 does not support paths with spaces

### ISSUE THREAD

**Issue by Daomephsta** [FabricMC/fabric-loom#46]
https://pastebin.com/DHTpLeKu

0.1.0 is quite happy with this path and project.

**Comment by quat1024** [comment]
My Windows username has a space in it, very similar stacktrace when running e.g. `./gradlew -S`: https://paste.ee/p/5Wmn2

(for anyone else with the same problem, `gradlew --gradle-user-home "C:/SomePathWithoutSpace/" yourGradleCommand` is a temporary workaround)
