### ISSUE TITLE
Can't find minecraft version Minecraft 1.18 exp1 or exp2

### ISSUE THREAD

**Issue by TNTChinaAAA** [FabricMC/fabric-loom#471]
According to fabricmc.net/versions.htmls, I change the gradle.properties, but I always said "java.lang.RuntimeException: Failed to find minecraft version: 1.18_experimental-snapshot-1"(as the picture shows); Then I try exp2, the same problem is. So I have to change the version.manifest and it's etag to avoid the fabric-loom redownload a non-1.18 version.manifest. But when I want to download 1.18-exp2-client.jar, it always said "connect reset", then I try exp1, the same problem.So, I want to ask for guys how to manual setting the fabric loom not to detect the caches changed with the sha1 files? (I'm a chinese, I have to use vpn to download fabric libaries or connect failed(timeout) ) (Because the vpn problem I can't connect so I must manual setting it).
![1](https://user-images.githubusercontent.com/40199850/128966919-eda18000-9030-448c-81d0-253f2f19466e.png)
![3](https://user-images.githubusercontent.com/40199850/128966930-dd6737ee-b369-4cc3-a84e-a682c819e57d.png)
![4](https://user-images.githubusercontent.com/40199850/128966936-ad0cad06-d488-40dd-a730-dc4073715142.png)
![2](https://user-images.githubusercontent.com/40199850/128967008-c0cd93b6-c934-4545-bb03-f23494d60e4a.png)
![5](https://user-images.githubusercontent.com/40199850/128967043-8f7a6422-c07f-4e58-9dac-d340452149ec.png)

**Comment by TNTChinaAAA** [comment]
Can use something make the fabric loom find minecraft version 1.18? Or have something to address the connect reset problem?

**Comment by TNTChinaAAA** [comment]
I just want to find minecraft version so have to change the version.manifest, but when I change successfully, I can't download the client.jar, may be my network problem (My area is China so connect always slowly to the amazon server). So I want to let the plugin skip the file delect.

**Comment by modmuss50** [comment]
This does look like a network problem, not sure there is anything we can do about it. You can use a custom manfiest if you need.

**Comment by Logiquo** [comment]
Maybe try this. https://github.com/FabricMCCN/fabric-loom-cn. They change all url in loom to china mirror (IIRC).
