### ISSUE TITLE
IntelliJ does not use the `test` class path when running, because the main class is always in `main`

### ISSUE THREAD

**Issue by FoxSamu** [FabricMC/fabric-loom#476]
As of loom 0.6, run configurations can be modified in the build script. This adds the option to set which source set is used for the class path. However, IntelliJ does not properly include the class path if the main class specified in the run configuration is not in the same source set, even though it might be accessible.

To give a more closer idea, I created a mod in the `test` source set that includes a couple of game tests for the now available framework. However, Fabric does not seem to find the fabric.mod.json there. This is because the dev launch injector main class is part of the `main` source set and hence IntelliJ uses the `main` class path regardless of what is configured in the run configuration. This causes Fabric not knowing about the test sources.

What I would propose to fix this is a custom JVM property that manually tells Fabric which build outputs must be included in mod discovery, so that a fabric.mod.json in the `test` source set is correctly discovered.

Note that this will probably overlap with fabric-loader.

**Comment by modmuss50** [comment]
The run configs use the main source set by default, you can change this, or add new run configs

To add new run configs, something  similar to what fabric api does:
```gradle
	loom {
		runs {
			testmodClient {
				client()
				name = "Testmod Client"
				source sourceSets.test
			}
			testmodServer {
				server()
				name = "Testmod Server"
				source sourceSets.test
			}
		}
	}
```

To just change the existing client/server configs:


```gradle
	loom {
		runs {
			client {
				source sourceSets.test
			}
			server {
				source sourceSets.test
			}
		}
	}
```

**Comment by FoxSamu** [comment]
Ah yes I know, it was literally my PR a while back in loom 0.6 ;)

I already configured the source sets in the build script, and the generated IntelliJ run configurations are configured as such. 

I tested in a separate project how IntelliJ selects the class path under certain conditions, and it assumes that the test class path is not reachable when the main class is on the main class path. In other words, even though the run configuration is configured to use the test class path, it only uses the main class path.

Since the dev launch injector is on the main, IntelliJ assumes the test class path does not need to be included, even though I specifically configured it to use the test source set. I just might be doing something wrong though if fabric-api actually utilizes it but I cannot check that right now.

**Comment by modmuss50** [comment]
Oh my bad, you must have a new icon :D (I forget names easily...)

Ok, ill take a look, DLI should work on the test classpath. Fabric API adds a new sourceset for its test mods, I forgot the reason behind that, but it seems to work ok.

**Comment by FoxSamu** [comment]
I did some more experimenting and found out that the class path is correct (includes test classes) if I run the `runClient` task. However, if I run the generated "Test Minecraft Client" configuration from IntelliJ, it only uses the main classes even when the configuration is set to use module `Mod.test`.
![image](https://user-images.githubusercontent.com/11669132/130809231-67bd7d34-81e5-4e75-ac74-1397fa731619.png)

I printed the class path in log, and I got this on `runClient` (main and test classes):
![image](https://user-images.githubusercontent.com/11669132/130809493-841079ae-f9af-44fb-8a38-ce935c67f26e.png)
...and this when running the belonging run configuration when running the run configuration from IntelliJ (only main classes):
![image](https://user-images.githubusercontent.com/11669132/130809720-3491888c-60bf-4039-b242-a586197228da.png)

Aside, I also messed with a basic Gradle project, adding a custom source set, and the same happens: IntelliJ uses the class path from the source set the main class is in. I think the easiest workaround is to manually set `-cp` in the JVM options of the generated run configuration. I'll try this in my build script.

**Update**
I tested adding a `-cp`, or `-Djava.class.path=` JVM argument, but for that I need to configure the run configurations within `afterEvaluate`, which runs _after_ run configurations have been generated. After manually adding `-cp ...` to the run configuration, the class path was correct, yet I prefer not to modify the run configurations as they are not shared over version control.

**Comment by FoxSamu** [comment]
Oh also, let me also give some context :P

I am working on a mod that enables various debugging features included within Minecraft but disabled. The feature I'm working on here is a wrapper around the GameTest framework, that makes it easy to run tests on GitHub Actions. The mod looks for files called `jedt.tests.json` in mod containers, via `ModContainer.getPath`, to register test classes (has some advantages when it comes to configuration of the server that is ran in the Actions CI). 

To test the testing integration I wrote a test mod with some random tests in the `test` source set. When this source set's class path is used, the tests are available at runtime. I configured all configurations to use the `test` source set classpath, which works when running the `runClient`/`runServer` tasks from Gradle, but not when running the generated run configuration (which is nonetheless correctly configured) because of the behaviour I mentioned.

**Comment by modmuss50** [comment]
FYI, I have been working on an fabric API module for this that will be merged in a few days: https://github.com/FabricMC/fabric/pull/1622 you may well be able to provide some input on it.

**Comment by FoxSamu** [comment]
Ah yes, saw that one, but was unsure about the status of it. It seems to work in an very different way. Could give some input, but I'll have to look closer on the PR for that first.

Yet, I see a similar issue arising there, where tests are `test` sources, and will not be on the class path (when ran from IntelliJ) if the main class is is not a `test` source.

**Comment by FoxSamu** [comment]
I found out that it indeed makes sense if you use the `test` source set, so I added a custom a custom source set (`gametest`), and it worked. This might also be the reason Fabric API uses the `testmod` sourcesets instead of `test`.

```gradle
sourceSets {
    gametest {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
    main {
    }
}

dependencies {
    gametestImplementation sourceSets.main.output
}
```

Not sure why `test` doesn't work, but this is enough for me. I'll close the issue, thanks for the help :D
