### ISSUE TITLE
Mappings for methods not present in intermediary (constructors, overridden JDK methods) are ignored

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#506]
Yarn has mappings for them, but since they're not in intermediary files, this ignores them:
https://github.com/FabricMC/fabric-loom/blob/7d2dad6e4604c3ff0a8521ae1304ef664ebbfc27/src/main/java/net/fabricmc/loom/configuration/providers/mappings/MappingsProviderImpl.java#L298-L300

I'm not very knowledgeable about mapping-io, but it seems that the `visitMethod("<init>", ...)` calls done by the tiny reader to the tree (already containing intermediary) always result in this code path:

https://github.com/FabricMC/mapping-io/blob/4cd971a1cdc71e588dc73ce1ff8343d27e0348e2/src/main/java/net/fabricmc/mappingio/tree/MemoryMappingTree.java#L331-L334

This leads to constructors and methods like `equals` not having parameters or docs.

**Comment by Player3324** [comment]
There are two namespace sets, one for the visitation and one for the tree. The set for the visitation is communicated by visitNamespaces, the tree's comes from how the tree has been constructed / fed with mappings before.

The visitation involves translating from the visitation-ns-set to the tree-ns-set. `srcNsMap` maps from visitation-srcNs to the corresponding tree namespace.

MemoryMappingTree currently accepts class visits in two cases:
1. The class `srcName` already exists in the tree (after translating visitation-srcNs to the tree ns)
2. The supplied `srcName` is for the actual source namespace for the tree, allowing the tree to create a new entry

Theoretically it could extend 1. and 2. to use any visitDstName to try the same kind of lookup, but that isn't implemented yet.

So with the current limitations in mind, you need to make sure the srcName is either matching an existing element or that it is in the tree's source namespace so a new element can be added. This may involve inferring the name (MappingNsCompleter) or reordering the names (MappingSourceNsSwitch) before visiting the tree.

I need more details about the specific issue to suggest something concrete.

**Comment by Juuxel** [comment]
> I need more details about the specific issue to suggest something concrete.

@sfPlayer1 I don't have the files at hand right now, but I suppose it should be reproducible with the usual intermediary/yarn tiny files.

Basically, if there's a method entry that Yarn has but intermediary doesn't (examples: `<init>`, methods overridden from the JDK), it doesn't get included here. Only methods that are present in intermediary (which is loaded first) are included.

Any documented/param-mapped constructor can be used as an example of this, I think. Not sure if the problem is with Loom's code or MIO's, though.
