### ISSUE TITLE
Crash when running migrateMappings to a Yarn version of 21w38a+build.10 or newer

### ISSUE THREAD

**Issue by Virtuoel** [FabricMC/fabric-loom#510]
**Commands tested:**
`./gradlew migrateMappings --mappings "21w38a+build.10" --stacktrace`
`./gradlew migrateMappings --mappings "21w38a+build.11" --stacktrace`
`./gradlew migrateMappings --mappings "21w39a+build.3" --stacktrace`

**Crash:**
[Stacktrace](https://gist.github.com/Virtuoel/e0b1f151314e67c6599241fd8bbe7d63) (identical for all the above commands other than the execution time)

**Tested on:**
`fabric-example-mod` with:
Loom: `0.10.23`
Minecraft: `21w38a`
Yarn: `21w38a+build.9`
Fabric Loader: `0.11.7`
Fabric API: `0.40.4+1.18`

**Comment by modmuss50** [comment]
Should be fixed, added a very basic migrate mappings test to help catch this again. Let me know if things arent working quite right.
