### ISSUE TITLE
Occasional FileAlreadyExistsException for META-INF when remapping

### ISSUE THREAD

**Issue by The-Fireplace** [FabricMC/fabric-loom#512]
Occasionally when I gradle sync, I get a message saying "An unknown exception occured when remapping" (Side note, typo in occurred)
Upon looking at the logs, I found that it's a FileAlreadyExistsException.
Loom 0.9.54
Log:
http://hastebin.com/ututipisuw.csharp

Workaround:
Gradle sync again, the second time usually works.

**Comment by modmuss50** [comment]
Log link is dead, please open an new issue if this is still the case.
