### ISSUE TITLE
Feature Request: Ability to specify packages to decompile rather than the whole thing for genSources  

### ISSUE THREAD

**Issue by valoeghese** [FabricMC/fabric-loom#539]
When modders make a mod, it's not every day that they will be creating a great mega mod which expands into all aspects of modding. Some will only be doing rendering. Others might add a few blocks and items. And then there's world gen mods, which pretty much only touch stuff in the `world` package. Sure, many mods do somewhat dabble in a bit of everything, but in a lot of cases mods, especially smaller mods, will only be touching one aspect of the minecraft codebase.

Now, let's move on to decompilation. Loom's genSources takes a significant amount of time to complete. But if a modder is only going to be touching one aspect of the codebase... why decompile the whole thing? It's a waste of time. When I'm running genSources for a mod, I afk or do something else because of how long it takes.

Solution? The ability to only partially decompile the game. If I am making worldgen mods, for example, I most of the time will not be going anywhere near rendering or networking. So why spend the time decompiling that?

**Comment by valoeghese** [comment]
This could be implemented as a blacklist (decompile everything but this) and/or a whitelist

**Comment by modmuss50** [comment]
Really depends on how well IDEs handle a partial sources jar, I expect it should be fine tho. Good idea 👍 

Generating sources shouldn't be too slow (60-90 seconds max seems resonable on a slow computer, 30 on a good PC), if its taking a long time I would love to make it better for everyone. I would be very intested to know more about why gen sources (or loom in general) is really slow for people, I know not everyone has top end computers like I do, and getting more insight/numbers would help me make it faster.

**Comment by modmuss50** [comment]
When using split jars (experimental atm) you will have 2 decompile tasks, one for the client and one for the server. This should help cover most of the use case here. I dont think its worth the added complexity to allow specific packages.
