### ISSUE TITLE
Kotlin library jar in intermediary gets remapped to wrong mappings

### ISSUE THREAD

**Issue by jakobkmar** [FabricMC/fabric-loom#558]
When adding a Kotlin mod library using `modImplementation`, and this library publishes its sources, you currently cannot use this library with different mappings than the ones that library chose to use for its own development.

**in the maven repo** there are:
- the actual library jar, correctly remapped to intermediary
- the sources jar, not remapped because this is not supported for Kotlin sources

**during compilation**:
- a jar remapped from the intermediary jar *not* to the mappings chosen in the current environment, but to the mappings used in the sources jar, is used (which is unwanted)
- this causes incompatible type errors, making it impossible to use the Kotlin library with other mappings than those used when this library was developed

For example, if my library uses **Yarn** mappings, others can only use it if they use Yarn as well, they cannot use it with **Mojmap**.

**Comment by jakobkmar** [comment]
I am pretty sure that this can be fixed, because loom actually produces a correctly remapped version of the library jar under `.gradle/loom-cache/remapped_mods/...` - that's just not the jar used for compilation.

**Comment by modmuss50** [comment]
> but to the mappings used in the sources jar

I fail to see how this is possible, the soruces jar does not contain any mappings, and should not affect complition (it doesnt with java at the very lesat)

> remapped version of the library jar under .gradle/loom-cache/remapped_mods/... - that's just not the jar used for compilation.

Are you sure this is the case? When you get the incompatible type errors are they from yarn, or from intermediary?

The only downside of writing a library in kotlin should be the that the sources dont match your namespace.

**Comment by jakobkmar** [comment]
The following screenshots are all in a mojmap environment. The displayed function is the same.

### Under remapped_mods

The one under `.gradle/loom-cache/remapped_mods/...`:

![grafik](https://user-images.githubusercontent.com/52456572/145870908-c79a7695-c336-4ca4-a502-865193905ec9.png)

Correctly remapped to mojmap:
![grafik](https://user-images.githubusercontent.com/52456572/145871836-68aaa055-46cc-4427-bcab-dae30a6e2837.png)
![grafik](https://user-images.githubusercontent.com/52456572/145871760-d1121fda-d1b5-4412-ab29-38d527e390a2.png)

### Compilation

However, during compilation, I get the following error:
`Cannot access class 'net.minecraft.util.math.BlockPos'. Check your module classpath for missing or conflicting dependencies`

displayed by the Kotlin IntelliJ frontend as well:
![grafik](https://user-images.githubusercontent.com/52456572/145871986-638d0f3a-afc6-463a-9fe0-1c51fbfbe11d.png)

Even though in the first three screenshots, the jar has been correctly remapped to mojmap, it is still using the yarn types during compilation.

**Comment by modmuss50** [comment]
Can you check what jar is beign used to compile with? You should be able to find it under the "External Libraries" section in intelij.

**Comment by jakobkmar** [comment]
That is even more confusing, if I do the following:

![grafik](https://user-images.githubusercontent.com/52456572/145872682-3bbdc274-3a36-4bfe-acba-e91790e6f413.png)

it actually points to the jar under `.gradle/loom-cache/remapped_mods/...`.

However, I doubt that this is correct. Also, if I browse the decompiled code there, it is in Yarn mappings, while the jar it points to when opening it in the explorer is in Mojmap 😕 .

**Comment by jakobkmar** [comment]
> I fail to see how this is possible, the soruces jar does not contain any mappings, and should not affect complition (it doesnt with java at the very lesat)

Yeah, but I really can't see where the Yarn mappings are coming from then. It is a Mojmap environment (no Yarn mappings applied in Gradle) and in the Maven repo everything is in intermediary, except the sources: https://repo1.maven.org/maven2/net/axay/fabrikmc-core/1.7.0/

**Comment by Juuxel** [comment]
It *might* be that IDEA prefers the sources for code analysis (the errors you see in your IDE) over bytecode. The actual compilation with kotlinc shouldn't use the sources in any case AFAIK.

**Comment by jakobkmar** [comment]
I thought of that as well, but the same error appears when using `./gradlew build` - and that does not involve IntelliJ in any way, right?

**Comment by jakobkmar** [comment]
Ok seems like I found the issue.

All other issues which I had are basically a result from the fact that the content of the Metadata annotation has not been remapped.

Even in a Mojmap environment, the Metadata annotation still contains the original Yarn mappings:
```kt
@Metadata(
   mv = {1, 5, 1},
   k = 1,
   xi = 48,
   d1 = {"\u00000\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\b\n\u0002\b\f\n\u0002\u0010\u000b\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u000e\n\u0000\b\u0086\b\u0018\u00002\u00020\u0001B\u000f\b\u0016\u0012\u0006\u0010\u0002\u001a\u00020\u0003¢\u0006\u0002\u0010\u0004B\u001d\u0012\u0006\u0010\u0005\u001a\u00020\u0006\u0012\u0006\u0010\u0007\u001a\u00020\u0006\u0012\u0006\u0010\b\u001a\u00020\u0006¢\u0006\u0002\u0010\tJ\t\u0010\u000e\u001a\u00020\u0006HÆ\u0003J\t\u0010\u000f\u001a\u00020\u0006HÆ\u0003J\t\u0010\u0010\u001a\u00020\u0006HÆ\u0003J'\u0010\u0011\u001a\u00020\u00002\b\b\u0002\u0010\u0005\u001a\u00020\u00062\b\b\u0002\u0010\u0007\u001a\u00020\u00062\b\b\u0002\u0010\b\u001a\u00020\u0006HÆ\u0001J\u0013\u0010\u0012\u001a\u00020\u00132\b\u0010\u0014\u001a\u0004\u0018\u00010\u0001HÖ\u0003J\u000e\u0010\u0015\u001a\u00020\u00032\u0006\u0010\u0016\u001a\u00020\u0017J\t\u0010\u0018\u001a\u00020\u0006HÖ\u0001J\t\u0010\u0019\u001a\u00020\u001aHÖ\u0001R\u0011\u0010\u0005\u001a\u00020\u0006¢\u0006\b\n\u0000\u001a\u0004\b\n\u0010\u000bR\u0011\u0010\u0007\u001a\u00020\u0006¢\u0006\b\n\u0000\u001a\u0004\b\f\u0010\u000bR\u0011\u0010\b\u001a\u00020\u0006¢\u0006\b\n\u0000\u001a\u0004\b\r\u0010\u000b¨\u0006\u001b"},
   d2 = {"Lnet/axay/fabrik/core/world/pos/PosInChunk;", "", "blockPos", "Lnet/minecraft/util/math/BlockPos;", "(Lnet/minecraft/util/math/BlockPos;)V", "x", "", "y", "z", "(III)V", "getX", "()I", "getY", "getZ", "component1", "component2", "component3", "copy", "equals", "", "other", "getBlockPos", "chunkPos", "Lnet/minecraft/util/math/ChunkPos;", "hashCode", "toString", "", "fabrikmc-core"}
)
```

This annotation is used by the Kotlin compiler and Kotlin reflection, therefore it might be a good idea to remap it as well.
