### ISSUE TITLE
Multi-project builds are broken: "build" must be run manually for project dependencies to resolve

### ISSUE THREAD

**Issue by NightEule5** [FabricMC/fabric-loom#562]
I have a project with a few sub projects. There are `modImplementation` dependencies between them and the root project adds them all as `include` and `modImplementation` dependencies to build a unified jar.

Say I have two modules, A and B. The root project's build.gradle.kts looks like this:

```kotlin
plugins {
    kotlin("jvm") version "1.6.10"
    id("fabric-loom")
}

allprojects {
    apply(plugin = "org.jetbrains.kotlin.jvm")
    apply(plugin = "fabric-loom")

    group = "org.example"
    version = "1.0.0"

    repositories {
        maven(url = "https://maven.fabricmc.net")
        mavenCentral()
    }

    dependencies {
        minecraft(group = "org.mojang", name = "minecraft", version = "1.18.1")
        
        mappings(group = "net.fabricmc", name = "yarn", version = "1.18.1+build.6")
        {
            artifact { classifier = "v2" }
        }
        
        modImplementation(group = "net.fabricmc", name = "fabric-loader", version = "0.12.9")
        modImplementation(group = "net.fabricmc", name = "fabric-language-kotlin", version = "1.7.0+kotlin.1.6.0")
    }
}

dependencies {
    include(project(":module-a"))
    include(project(":module-b"))

    modImplementation(project(":module-a"))
    modImplementation(project(":module-b"))
}
```

`module-a`'s:

```kotlin
dependencies {
    modImplementation(project(":module-a"))
}
```

And `module-b`'s is blank.

When importing the project for the first time, the project dependencies fail to resolve; Gradle throws an error for every module, like "Could not find org.example:module-a:1.0.0". You have to remove the `modImplementation` lines and run the build task for every module manually, then add them back and import.

After that, it builds and runs fine, but if you make changes to your code you have to rebuild everything again or the jars are out of date. A workaround for this is to add each module's build task as a "Before Launch" task in IntelliJ

I've attached an example project that reproduces this issue.

[LoomMultiModuleBug.zip](https://github.com/FabricMC/fabric-loom/files/7749061/LoomMultiModuleBug.zip)

**Comment by modmuss50** [comment]
Replace
```gradle
dependencies {
    modImplementation(project(":module-a"))
}
```

With:

```gradle
dependencies {
    implementation project(path: ":module-a", configuration: 'namedElements')
}
```
