### ISSUE TITLE
Should remapJar use runtimeClasspath instead of compileClasspath?

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#563]
It might make a bit more sense since the runtime CP is what running the jar actually depends on and should contain everything important that is referenced in the bytecode (otherwise it would, you know, crash). This affects the remapJar config both 0.10 and 0.11.

**Comment by modmuss50** [comment]
No I don’t think so. The compile classpath contains all possible deps, including some that may have been disabled in dev. There is no harm in having stuff that is never used.

**Comment by Juuxel** [comment]
Yeah, makes sense. At least the new RemapJarTask in 0.11 also lets users add their own files to the remap classpath if needed :smile:
