### ISSUE TITLE
Support dependency remapping with more configurations

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [FabricMC/fabric-loom#57]
[The dependency management page for the Java Plugin explains how configurations should probably be dealt with.](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management)

[The Java Library Plugin adds a few more configurations as well.](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph)

A possible use case is for mods exposing an API with separate API and implementation artifacts. The API would be depended on as `compileOnly` and the implementation as `runtimeOnly`

First of all, `compile` has been deprecated. At minimum we might want to deprecate `modCompile` and introduce `modImplementation`, but more ideally I think remapping should work with any configuration. This has been shown to work in practice in ForgeGradle.

**Comment by sargunv** [comment]
I'd love to see a version of `api` and `implementation` that supports remapping. It'd make managing dependencies so much easier.

**Comment by liach** [comment]
Can we just make a separate configuration `modDep` for deobfuscating a dependency, and users declare their own which modDep and api or implementation extend from?

**Comment by modmuss50** [comment]
Long since added.
