### ISSUE TITLE
ANSI Control Sequences Showing in Eclipse Console

### ISSUE THREAD

**Issue by TheKodeToad** [FabricMC/fabric-loom#570]
When running the game in Eclipse IDE (and possibly other IDEs), the console is filled with ANSI control sequences. When running in a terminal they appear coloured, but Eclipse doesn't understand these codes and they are printed like the rest of the text.

I do not want to use IntelliJ as I have been trying to use it for over a year, and I still prefer Eclipse because of its performance (despite being less polished). This issue is probably not a priority, unless Eclipse is more popular among Fabric modders than I thought.

A possible solution would be to check the value of `System.console()`, as it suggests that you are running in an environment that supports more advanced features.

**Comment by modmuss50** [comment]
This shouldnt be enabled by default for eclipse. I believe there is a plugin that supports this.

See the logic here: https://github.com/FabricMC/fabric-loom/blob/d40241d75aa4065bcb3e2f9378f890fdd5bb1bba/src/main/java/net/fabricmc/loom/task/launch/GenerateDLIConfigTask.java#L64-L66

I expect you have a .vscode, .idea or .iws file?

This is a log4j setting and not something that we can easily control at runtime.

**Comment by TheKodeToad** [comment]
Thank you for responding. That was the issue.

It seems that there isn't any easy way to fix it. I'd just been hopping between IDEs.

**Comment by modmuss50** [comment]
Ah no worries, you can force disable it by running gradle with `gradlew --console=plain` we dont really have a better way to dectect ansi compatibility sadly.

**Comment by TheKodeToad** [comment]
Eclipse now has native ansi support.
