### ISSUE TITLE
[Suggestion] @Entrypoint annotation processing

### ISSUE THREAD

**Issue by SHsuperCM** [FabricMC/fabric-loom#577]
### The idea:
Mods could annotate classes, methods and static fields with `@Entrypoint` to make loom automatically add them to the mod json's entrypoints.
The annotation's `String` value is the entrypoint identifier.
Because this will be done in loom, the annotation does not need runtime retention. (making it have no effects on the loader in runtime)

### Example usage:
`CITResewn.java`
```java
package shcm.shsupercm.fabric.citresewn;
...
@Entrypoint("client")
public class CITResewn implements ClientModInitializer {
    ...
```
Loom appends:

`fabric.mod.json`
```patch
{
    ...
    "entrypoints": {
        ...
        "client": [
            ...
+          "shcm.shsupercm.fabric.citresewn.CITResewn"
        ],
        ...
```

### Pros:
 - Reduces source mod json clutter. (especially when a lot of mod-provided entrypoints are present)
 - Gives in-code context/reasoning for entrypoints' relevance.
 - Less hassle adding new entrypoint implementations.
 - Refactoring of entrypoints(moving/renaming) results in less missed errors and needed actions.
 - Simplifies entrypoint examples and code snippets.
 - Fully backwards compatible with current projects' declaration of entrypoints.

### Cons:
 - Viewing sources' mod json won't show where entrypoints are in the source.
 - Slightly slows down project compiling.
 - Requires a loader or loom provided api for the annotation's class to be in the compile classpath.

**Comment by modmuss50** [comment]
I think this is out of scope for loom. Might make a good 3rd party library.

**Comment by SHsuperCM** [comment]
For anyone that stumbles across this suggestion in the future, I ended up writing a whole gradle plugin with a bunch of features including this suggestion called [Fletching Table](https://github.com/SHsuperCM/FletchingTable).

I still think that(even if not in loom) fabric should have this functionality by default. But yeah, it did make for a good 3rd party library, I was not aware of how easy plugins were to set up in gradle.
