### ISSUE TITLE
0.11 decompiler api crashes when the classpath is specified

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#578]
When you add files to `DecompilerOptions.getClasspath` ([like in loom-quiltflower](https://github.com/Juuxel/LoomQuiltflower/blob/6481e61c790d5b96bb5fb4b67d8295e544809b5d/src/loom011/java/juuxel/loomquiltflower/impl/module/Loom011Setup.java#L15)), the genSources tasks crash with the error message:

> -Xbootclasspath is no longer a supported option.

**Comment by modmuss50** [comment]
I think we might need to remove this, gradle doesnt seem to provide a solution for this.

**Comment by Juuxel** [comment]
That'd sadly make it as inflexible as before. A JavaExec-based task like in <0.9 would definitely be nicer for extending it since that can have proper classpaths.

**Comment by modmuss50** [comment]
JavaExec had some issues, especially around multi project builds. I think the solution will be to provide an API for registing a custom task so your plugin can handle the forking (or not) as it wants to. Its worth getting this fully sorted before 0.11 becomes stable.

**Comment by Juuxel** [comment]
Fixed in b69404ea03cbe70c610eb60b5d49500ded3bcb6e
