### ISSUE TITLE
[0.3.0] Could not find net.fabricmc.yarn.19w11b-9.net.fabricmc:fabric-loader:0.3.7.109.

### ISSUE THREAD

**Issue by NikkyAI** [FabricMC/fabric-loom#58]
log: https://gist.github.com/NikkyAI/b079732fa19dda6bb2012063cb753abc

apparently dependnecies are getting accessed too early?

**Comment by NikkyAI** [comment]
in idea these tasks are listed: ![tasks](https://i.imgur.com/YWvDQmo.png)
when i run the ones it fails on and sync idea again more tasks are available
until all dependencies are mapped

to me it seems like registering these tasks depends on the some other tasks having been run and thus they never get added or run through task dependencies

i hope those tasks can be run during sync (ie when the system property `ide.active` == true)
to make opening a project friction/effort-less

**Comment by modmuss50** [comment]
I can reproduce something similar, just importing the example mod into idea fails to find the minecraft jar.

![](https://ss.modmuss50.me/idea64_2019-03-27_09-41-27.png)

**Comment by modmuss50** [comment]
Edit, seems like running genIdeaRuns and then refreshing the gradle project fixed this.

**Comment by covers1624** [comment]
The docs haven't been written yet, but you need to mark the following tasks as Before Sync.
![](https://ss.covers1624.net/76587)
@NikkyAI i forgot to mention this on IRC the other week. please verify this fixes your issue.

**Comment by NikkyAI** [comment]
i guess i will try this one 0.3.0 also supports `include`

**Comment by modmuss50** [comment]
0.3.0 isnt going to be a thing
