### ISSUE TITLE
Multiple subprojects remapping classes with the same name causes weird issues

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#587]
1. Sometimes the class in question is not included at all into one of the subprojects
2. Sometimes one project's class goes into another project's jar

See:
- Reproduction code: https://github.com/Juuxel/loom-reproducer-2022-01-26
- TR's duplicate handling: https://github.com/FabricMC/tiny-remapper/blob/master/src/main/java/net/fabricmc/tinyremapper/TinyRemapper.java#L451
- Log spam as a byproduct of this issue: https://gist.github.com/Juuxel/18264b0d82365a4a1c25b51ed7838694

**Comment by modmuss50** [comment]
This was fixed by adding an option to isolate the remapper. https://github.com/FabricMC/fabric-loom/commit/4fe19028cf4194e3982adb28d7c51ddb27fed28b
