### ISSUE TITLE
Caused by: java.lang.ClassFormatError: Illegal class name "com.jab125.soul.EntityExtension" in class file net/minecraft/entity/Entity

### ISSUE THREAD

**Issue by Jab125** [FabricMC/fabric-loom#592]
Loom 0.11's interface injection is acting up with this: `"net/minecraft/class_1297": ["com.jab125.soul.EntityExtension"]`
and the interface doesn't matter

**Comment by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET** [comment]
replace `com.jab125.soul.EntityExtension` with `com/jab125/soul/EntityExtension`
