### ISSUE TITLE
Library sources don't match class bytecode

### ISSUE THREAD

**Issue by nskobelevs** [FabricMC/fabric-loom#594]
I'm getting an issue exactly like #150 but on a recent development setup.

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/34107736/153099034-be6cb721-7701-413d-b98e-1f2b691e30d8.png">

**Version:**

* Fabric API 0.46.4+1.18
* Fabric Loader 0.13.1
* Minecraft 1.18.1
* Yarn 1.18.1+build.22
* Loom 0.11-SNAPSHOT
* IDE: IntelliJ 2021.3

All the versions are from https://fabricmc.net/develop/ so I believe everything is up to date

My Gradle experience is subpar so I wasn't able to look much into it. I tried cleaning the project, invalidating the cache in IntelliJ but no luck.

Just to double check I opened the sources and compiled jar with a decompiler and they're definitely different so I don't think (hope) this is an issue on my end.

ServerWorld inside sources jar:

![image](https://user-images.githubusercontent.com/34107736/153101049-448af7f2-1cd0-475d-a2e6-6555506a489e.png)

ServerWorld decompiled:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/34107736/153100978-ab9c17b3-4a84-481c-997d-65f3a90382b9.png">

**Comment by Juuxel** [comment]
This is probably just an issue with the CFR decompiler that Loom uses to generate the MC sources - no decompiler is perfectly accurate, sadly.

**Comment by nskobelevs** [comment]
I think you're right. I had more of a look and none of the differences seem code breaking. Either slight formatting differences, or constants in place of enums, some rearranging but the underlying code looks the same. Checked a bunch of classes and wasn't able to find anything breaking like a conflicting method signature.

Is there anything else (apart from a different method signature) that would signify there's something wrong in case I run into it?


I saw there's a gradle task that generates sources with fern flower and that seems to work a bit better as I wasn't able to find classes with that error when just randomly having a look through them. No saying they don't exist but seem alright!

**Comment by Juuxel** [comment]
Complex control flow structures (nested loops, especially if mixed with returns) are also something decompilers struggle with. But unless you're familiar with reading bytecode (or work at Mojang and have access to the real Minecraft sources), you can't really know if the decompiled code is 100% correct.

**Comment by nskobelevs** [comment]
> or work at Mojang

~~Corporate espionage time?~~

That's fair then! I'll consider this a non-issue as nothing is appearing to be actually broken
