### ISSUE TITLE
Interface Injection can cause Mixin remapping to fail

### ISSUE THREAD

**Issue by LambdAurora** [FabricMC/fabric-loom#595]
While reworking and porting Quilt's Tags API to 22w06a I tried to use interface injections to simplify some interfaces and make their usage more easy.

Everything was working fine when IDEA was compiling itself, running the run configs in IDE worked great, then `gradle build` happened: failure.

Before diving more into the possible causes, [here's the failing commit](https://github.com/LambdAurora/quilt-standard-libraries/tree/d0a0c275b09a1fc43be63c1b4e89a25756eaa8e4), and the [build error](https://github.com/LambdAurora/quilt-standard-libraries/runs/5200634559?check_suite_focus=true#step:4:494).

As the error highlights it seems to be affecting `QuiltTagKey`, the interface adds a new method, and is injected into `TagKey`.
It is worth noting that 2 other interfaces are injected similarly: `QuiltTagBuilder` and `QuiltTag`, both work without any issues.

[Someone on the Fabric Discord seems to have encountered a similar issue with their setup.](https://discord.com/channels/507304429255393322/807617700734042122/939471152504504340)

So, what happened?

The method in `QuiltTagKey` is used in other places of the codebase including the mixin itself, outside of the mixin and in the `main` source set a cast is still used.
It seems whatever triggers the mixin remapper to need to use the interface will make it fail.

Other approaches have been attempted without success:
 - using another mixin for implementing the injected interface separately
 - using `@Implements`
 - updating loom from 0.11.29 to 0.11.30
 
Reproduction: https://github.com/LambdAurora/loom_interface_injection_issue

**Comment by modmuss50** [comment]
Your interface methods need to have a default impl.

**Comment by modmuss50** [comment]
This needs a simple reproduction case either based off the example mod or the intergration test in loom.
