### ISSUE TITLE
The project creates but doesnt build, with MCdeveloper plugin

### ISSUE THREAD

**Issue by milosworks** [FabricMC/fabric-loom#596]
I just created a proyect but i cant compile it, i tried uninstalling java and reinstalling it (java its not the problem), im new in this and idk how to solve it

_Sorry if it is a large error_

![image](https://user-images.githubusercontent.com/65917996/154180555-64905650-9e9c-49e8-9f83-905eb65dc24b.png)
![image](https://user-images.githubusercontent.com/65917996/154180495-a31a5328-4d17-435a-b158-e6c9628a6d8f.png)
![image](https://user-images.githubusercontent.com/65917996/154180526-a9918c66-b599-4778-b88b-29e351b6518f.png)

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
