### ISSUE TITLE
FileSystemAlreadyExists when building in CircleCI

### ISSUE THREAD

**Issue by sargunv** [FabricMC/fabric-loom#60]
I'm getting `FileSystemAlreadyExists` exception from tiny-remapper when building a mod ([sargunv/always-drop-loot](https://github.com/sargunv/always-drop-loot)) in CircleCI. From discussion in https://github.com/FabricMC/tiny-remapper/issues/7, it sounds like loom is not releasing a file. Could be related to https://github.com/FabricMC/fabric-loom/issues/45. 

I can reproduce the issue every time I build in the CircleCI environment. Perhaps building inside a docker container from their image (`circleci/openjdk:8-jdk`) would reproduce it.

Here's a sample stack trace of the crash from tiny-remapper: https://pastebin.com/5MjxLqfd

**Comment by modmuss50** [comment]
Closing this as ive not seen issues with this for a long time. if its still an issue please re-open a new one.
