### ISSUE TITLE
No way to create custom mod* remapped configurations.

### ISSUE THREAD

**Issue by NoComment1105** [FabricMC/fabric-loom#600]
Title says it all

![image](https://user-images.githubusercontent.com/67918617/155178936-5005ca4b-02c3-4fbb-bacc-8455cb6cc7eb.png)
![image](https://user-images.githubusercontent.com/67918617/155179030-a9747e8c-bf5f-427e-a997-c45d1885b8b9.png)
```bash
/home/nocomment/Documents/GitHub/NoComment1105/maybe-more-data/src/testmod/java/maybemoredata/testmod/MaybeMoreDataTestmod.java:34: error: cannot access class_3614
            TEST_BLOCK = Registry.register(Registry.BLOCK, new Identifier("maybemoredata", "test_block"),  new Block(FabricBlockSettings.of(Material.STONE).requiresTool().strength(2f, 4f)));
                                                                                                                                        ^
  class file for net.minecraft.class_3614 not found
```

**Comment by NoComment1105** [comment]
o7, Thank you! Please let me know when this is possible, I look forward to it

**Comment by modmuss50** [comment]
This was resolved with: https://github.com/FabricMC/fabric-loom/commit/da2992e7d9547a1ab14e500ba5ca188733f1bc3f
