### ISSUE TITLE
Library sources don't match class bytecode (again)

### ISSUE THREAD

**Issue by Power-tile** [FabricMC/fabric-loom#614]
I got the same problem as [this issue](https://github.com/FabricMC/fabric-loom/issues/594) and had a significant problem apart from a slight difference in decompilation results. I am trying to use `MinecraftServer.getWorldPath()` to get access to the directory `Path` of the current server in order to save my configuration in a file. This function is used in [`fabric-carpet`](https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/settings/SettingsManager.java#L290) to achieve the same goal. However, I cannot find the same method in my decompiled class and IntelliJ cannot use the method...

Versions:
- Minecraft 1.18.1
- Fabric Loader 0.12.12
- Fabric 0.46.2+1.18
- Yarn 1.18.1+build.22
- Loom (not sure where to view version)
- IDE IntelliJ 2021.3

**Comment by dvitski** [comment]
If you're using yarn and not mojang mappings, you might be looking for `MinecraftServer#getSavePath`?

**Comment by Power-tile** [comment]
@andantet I think there are slight differences between `getWorldPath(LevelResources)` and `getSavePath(WorldSavePath)`. It bothers me that the same versions of Minecraft produces the difference method results...

As a side note, are there any documentation to these Minecraft functions? I am just into modding and am only using `getWorldPath()` since I saw other mods (in this case `carpet`) using it...

**Comment by Power-tile** [comment]
There is also another weird trivia: my decompiled `net.minecraft` classes are under `./net/minecraft/*` directory inside my dependency list instead of the usual `./src/main/net/minecraft/*`:
![image](https://user-images.githubusercontent.com/44731563/158074466-dd6aaaf1-3516-46e6-b4df-4dcf2a2d8933.png)

**Comment by Mimerme** [comment]
1.18 modding in shambles

**Comment by modmuss50** [comment]
Closing this as we have made big improvements in this area since this issue was created.

**Comment by LolItsHaiech** [comment]
same issue when updating from 1.21 to 1.21.2
