### ISSUE TITLE
Loom should clean up its caches on `gradlew clean` (or keep its cache in the build cache)

### ISSUE THREAD

**Issue by SilverAndro** [FabricMC/fabric-loom#618]
Very annoying to run the "delete the build cache" command and not actually have things related to the build be un-cached, personally

**Comment by modmuss50** [comment]
the `clean` task is to clean the build outputs, not the caches. In an ideal world you should never have to clear your caches, if you have an issue that causes this to be a requirement please open another issue so the root cause can be solved.
