### ISSUE TITLE
Mixin Remapping with Alternative Namespace

### ISSUE THREAD

**Issue by TheKodeToad** [FabricMC/fabric-loom#622]
Despite #191 being resolved, there still isn't a method to change the namespace of mixin refmaps.

Even if I use:
```gradle
remapJar {
	targetNamespace = "official"
}
```
the mixin annotation processor ignores it.

You can see this in [AnnotationProcessorInvoker](https://github.com/FabricMC/fabric-loom/blob/fff4afe4051a905320cdef616c61b7094b66b369/src/main/java/net/fabricmc/loom/build/mixin/AnnotationProcessorInvoker.java#L92).

**Comment by modmuss50** [comment]
This was done here: https://github.com/FabricMC/fabric-loom/commit/5f5dfcb3a7395910e0fda53e09503a43a7eb8de1
