### ISSUE TITLE
What Loom version do I use for a given version of Gradle/Minecraft/Fabric API/whatever it depends on?

### ISSUE THREAD

**Issue by Keheck** [FabricMC/fabric-loom#623]
Since there are no emplate projects for Fabric 1.14 (anymore), I'm using the [Minecraft Development](https://plugins.jetbrains.com/plugin/8327-minecraft-development) plugin for IntelliJ IDEA, and I find it frustrating to use because no matter what Loom version I select, I either get a duplicate remapping name error, a Java version error (when I use the version recommended on the [develop page](https://fabricmc.net/develop/) of the Fabric wiki) or a missing property error for the version automatically selected by Minecraft Development. 

I have found no documentation on which Loom version to use for what versions and there is also no explanation on what the Loom version actually **does**, so I am kind of at a loss of what I am supposed to do now.

**Comment by modmuss50** [comment]
The latest version of loom supports all versions of Minecraft. The current recommended version is 0.11. You should be able to take the latest example mod and change the versions to match for 1.14 quite easily.

One thing to note is that that modern loom versions require modern java (16/17). You will most likely want to compile your mod to Java 8 so all 1.14 users can use it, this is easy to do by basicaly changing everywhere it says 17 to 8 in the build.gradle.

I do have some longer term plans to create an official template generator that will allow you to pick the minecraft version. I have also started posting a changelog of loom versions here: https://github.com/FabricMC/fabric-loom/releases

**Comment by Keheck** [comment]
I see...
I'll try your recommendation and come back with any news of success/failure

**Comment by Keheck** [comment]
Didn't work. Instead of getting the outdated version error I now get the duplicate [mapping name error](https://pastebin.com/uqs4SYuB)

**Comment by modmuss50** [comment]
Ah, I think there is a bug where v2 1.14 mappings are broken. In your build.gradle change:

`mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"`

to `mappings "net.fabricmc:yarn:${project.yarn_mappings}"` (note the missing `:v2`)

**Comment by Keheck** [comment]
That worked! Thanks for your help!

One small issue though, I'm missing the run/build profiles. How do I set them up?

**Comment by modmuss50** [comment]
What IDE are you using? Asumming idea they should just show up, sometimes you need to close and open the project for idea to detect them.

**Comment by Keheck** [comment]
Oh yeah, there they are now...
I'm gonna close this issue now as all my questions have been answered.

Thanks so much again for your help
