### ISSUE TITLE
Generate fabric.classPathGroups when needed

### ISSUE THREAD

**Issue by Player3324** [FabricMC/fabric-loom#629]
Running the game in-dev for more complex projects may result in more than one class path entry for a mod. These entries would get composed into a single production jar at the end, but in the unpackaged state they could be any combination of source set outputs including sub projects or non-mod libraries that'd eventually get shaded into the production jar.

Fabric Loader needs to know that these class path entries belong together in order to expose the full mod contents in `ModContainer.getPaths` and related APIs. It also needs them to add the complete mod to the class loader. Fabric Loader detects mods by looking for `fabric.mod.json` files on the class path. The mod's path is composed of the code source behind this json file (containing base dir or jar) and the `fabric.classPathGroups` entry containing this initial code source. Thus adding all mod associated code sources to the `fabric.classPathGroups` system property enables proper detection.

Loom could try to infer the class path groups from the user supplied dependency configuration automatically or if that's infeasible help with manually specifying it.

See https://github.com/FabricMC/fabric-loader/issues/647 for a related case

**Comment by modmuss50** [comment]
I have added support for adding custom files/directories with: https://github.com/FabricMC/fabric-loom/commit/1dfea9ef7e3df94a3c2714aec5dfb484fdb6623d This should help a lot with manually configuring the classpath groups.

Still TODO is to add some sort of automation around this for basic mods.

**Comment by modmuss50** [comment]
0.12 supports this, must be defined manually.
