### ISSUE TITLE
How do I use fernflower?

### ISSUE THREAD

**Issue by RubixDev** [FabricMC/fabric-loom#632]
When I understand [this page](https://fabricmc.net/wiki/documentation:fabric_loom) correctly it is possible to use loom with fernflower instead of cfr, but I cannot find any documentation on how to use fernflower.

**Comment by frqnny** [comment]
isnt there `gradlew genSourcesWithFernFlower`

**Comment by RubixDev** [comment]
Yes there is, thank you
