### ISSUE TITLE
Deprecated Loom APIs were used in this build, making it incompatible with future  versions of Loom. Use Gradle warning modes to control the verbosity of the warn ings.

### ISSUE THREAD

**Issue by BuffOvrFlw** [FabricMC/fabric-loom#635]
hello everyone .
when im use `gradle genSources`
its has a error
Deprecated Loom APIs were used in this build, making it incompatible with future
 versions of Loom. Use Gradle warning modes to control the verbosity of the warn
ings.

**Comment by BuffOvrFlw** [comment]
* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all task dependencies for configuration ':compileClasspath'.

   > Could not resolve project :theme.
     Required by:
         project :
      > No matching configuration of project :theme was found. The consumer was
configured to find an API of a library compatible with Java 17, preferably in th
e form of class files, preferably optimized for standard JVMs, and its dependenc
ies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.typ
e' with value 'jvm' but:
          - None of the consumable configurations have attributes.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and
 determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:comm
and_line_warnings

BUILD FAILED in 1m 2s

**Comment by sUgarhax** [comment]
how to fix?

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
