### ISSUE TITLE
RemapJarTask should expose the original message of the underlying exception when remapping fails

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#649]
Currently, without `--stacktrace`, it just outputs a very undescriptive 

```
> A failure occurred while executing net.fabricmc.loom.task.RemapJarTask$RemapAction
   > Failed to remap
```

This could easily be improved by adding the original exception class and message after "Failed to remap".

Relevant line:
https://github.com/FabricMC/fabric-loom/blob/9f341a9b47e97ed57f799158052252caf520cef4/src/main/java/net/fabricmc/loom/task/RemapJarTask.java#L244

**Comment by modmuss50** [comment]
Yes, very similar issue as: https://github.com/FabricMC/fabric-loom/issues/638
