### ISSUE TITLE
Private methods overridden via AW are not remapped correctly 

### ISSUE THREAD

**Issue by Technici4n** [FabricMC/fabric-loom#656]
AE2 overrides the private `HandledScreen#renderSlot` method using an AW, however when AE2 is remapped from intermediary to named in mod dev envs, the remapper does not remap AE2's override.

This causes slot amounts to be invisible in AE2 terminals in the dev env of other mods, and provides an easy way to check if this issue occurs.

**Comment by modmuss50** [comment]
To fix this apply all of the the AWs (including none transitive ones) in a tiny remapper AnalyzeVisitor

**Comment by modmuss50** [comment]
This was fixed a while back
