### ISSUE TITLE
Non-existent net.mojang domain in migrateMappings

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#657]
https://github.com/FabricMC/fabric-loom/blob/a2e84e242a59e29db2f455734031e77179b3336c/src/main/java/net/fabricmc/loom/task/MigrateMappingsTask.java#L120

AFAIK, mojang.net doesn't exist at all (it's either minecraft.net or mojang.com)

**Comment by modmuss50** [comment]
Yeah, I was stupuid when I added it, can prob remove this now but was left in as I told everyone to use this :D
