### ISSUE TITLE
ModSettings assumes project is always compiled with Gradle

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#658]
The DLI file contains the Gradle build directories for each source set, which won't work if the project uses IDEA's "Build and Run using: IntelliJ IDEA" option. Not sure if there's any nice way around this, though.

**Comment by modmuss50** [comment]
0.14.6 loader will ingore these directories; https://github.com/FabricMC/fabric-loader/commit/feb10d6d223c63e019a32cdd6afcaa9c90a709fa

Loom will include both directories when the idea compiler output path is set.
