### ISSUE TITLE
File mappings impl doesn't match API spec

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#664]
The API specifies that the mapping path can be null for bare files (though it has no effect on them):
https://github.com/FabricMC/fabric-loom/blob/adc44ce0e9cb76c23710a98b0f16964400638b89/src/main/java/net/fabricmc/loom/api/mappings/layered/spec/FileMappingsSpecBuilder.java#L47

...while the impl crashes if it sees null:
https://github.com/FabricMC/fabric-loom/blob/adc44ce0e9cb76c23710a98b0f16964400638b89/src/main/java/net/fabricmc/loom/configuration/providers/mappings/file/FileMappingsSpecBuilderImpl.java#L57

I guess we could just remove null from the API docs.

**Comment by modmuss50** [comment]
Fixed the docs, can alter the behaviour if needed at a later date.
