### ISSUE TITLE
Fernflower can't decompile TagEntry

### ISSUE THREAD

**Issue by DeathsGun** [FabricMC/fabric-loom#67]
While upgrading to 19w14b.9 i faced the issue that loom couldn't decompile `net/minecraft/world/loot/entry/TagEntry`. This happens with the following mappings:

- 19w14b.9
- 1.14 Pre-Release 1+build.1
- 1.14 Pre-Release 1+build.2
- 1.14 Pre-Release 1+build.3

### Additional information
[Gradle.log](https://github.com/FabricMC/fabric-loom/files/3069760/Gradle.log)
[Project](https://github.com/NuggetMC/CraftNugget)

**Comment by fp-alice** [comment]
Here to confirm -- a colleague and I are also experiencing this issue. [Here's a pastebin with more details](https://pastebin.com/VxJg3Qec)

**Comment by modmuss50** [comment]
My only guess is this PR had something to do with it, https://github.com/FabricMC/yarn/commit/0d36018c1ad76fbf796fd1ea5c2ff665303e8642

**Comment by modmuss50** [comment]
yes, I think `expand` is a mojang name, this would explain some issues I had when updating.

**Comment by asiekierka** [comment]
Issue happens at tiny-remapper step; definitely not here.

**Comment by modmuss50** [comment]
Fixed use yarn build 4
