### ISSUE TITLE
include project dependencies

### ISSUE THREAD

**Issue by RealHeart** [FabricMC/fabric-loom#672]
```
include project(":common")
```

How to add the dependencies of the `:common` to add to jar through the `include`

```
dependencies {
    api "com.github.goxr3plus:java-stream-player:10.0.2"
}
```

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
