### ISSUE TITLE
I got this Caused by: java.lang.NoClassDefFoundError: net/my name/my mods name/my mods name (wrong name: net/my name/my mods name/my mods name) when i pressed runclient in the example mod.

### ISSUE THREAD

**Issue by Fuel498lucky** [FabricMC/fabric-loom#684]
I followed these steps https://youtu.be/RSqSZoJQXvg

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
