### ISSUE TITLE
Interface injection causes a guarenteed crash when used as a compile only dependency

### ISSUE THREAD

**Issue by emilyploszaj** [FabricMC/fabric-loom#687]
If a mod uses interface injection, and you try to depend on it through gradle but don't want it in your runtime, you cannot launch the game. Interface injection puts the interface onto the class for dev sources, and launching the game makes the JVM attempt to load the interface, which does not exist at runtime, causing an instant class not found error.

This effectively means that no API mods can have interface injections, and also content mods with interface injections cannot have optional compatibility made on the end of other mods, since all dependencies are forced to be present at runtime. This is a pretty huge problem.

Possible solution:
* Separate the compile/run sources and only apply interface injection to the former (this was a suggestion from someone else and I'm not sure how reasonable it is to implement)

Hacky solution:
* Detect interface injection of compile only dependencies and, at runtime, add stub interfaces that contain no methods but match the classpath to prevent crashing.

**Comment by modmuss50** [comment]
The code already tries to do this, and even has a comment about it: <https://github.com/FabricMC/fabric-loom/blob/exp/0.13/src/main/java/net/fabricmc/loom/configuration/ifaceinject/InterfaceInjectionProcessor.java#L185-L187> Same idea in 0.12: <https://github.com/FabricMC/fabric-loom/blob/dev/0.12/src/main/java/net/fabricmc/loom/configuration/ifaceinject/InterfaceInjectionProcessor.java#L185-L188>

Im unsure as to why its not working for you.

**Comment by emilyploszaj** [comment]
The comment is saying it's only applying for compile classpath, but the issue is that it's causing classloading crashes if a mod is *only* part of the compile classpath. The interface their interface injection points to will not exist, despite the class saying it implements it, causing an instant class not found.

**Comment by modmuss50** [comment]
Ah I see. Yeah im not too sure what the best course of action here is. I guess it should only be applying them from mods that are both on the compile and runtime configurations.

For now either disable dependency iface injection or add the mod to the runtime.

**Comment by emilyploszaj** [comment]
In this scenario, I am the mod with iface injection, and the mod using my mod requires it to be enabled, and also not be in the runtime, so I have to to remove iface injection wholesale. The hacky solution I considered but decided against was providing a file on maven that would just contain empty interfaces for use at runtime to prevent crashes. Would it be reasonable for loom to generate empty interfaces and add them to the runtime classpath for dependencies with a compile but no runtime configuration? It's not exactly pretty and elegant, but could serve as a bandaid instead of wholesale separating compile and runtime sources.

**Comment by modmuss50** [comment]
Seperating complie and runtime sources isnt going to happen, we have discussed this before and decided its not something we want to do.

> requires it to be enabled, and also not be in the runtime

Im struggling to think of a case where you need to have the injected interfaces only at compile time, and not runtime. 

> loom to generate empty interfaces

No. I dont think that's a good solution. You idea of shipping a jar with the interfaces might be a better workaround.

Another idea may be to strip those interfaces at runtime, but will require something at runtime. Right now loom is the only thing that worries about iface injection. I do have plans to create a "v2" of iface injection that fixes some of these edge cases and removes the need to use mixin at runtime, I think this may be something to solve there.

**Comment by LambdAurora** [comment]
> Im struggling to think of a case where you need to have the injected interfaces only at compile time, and not runtime.

The use case is a mod implementing support for -EI mods, so you if you want to support everyone you get at least 3 compile mods, but you only can test 1 at a time or otherwise you get a mess.

**Comment by modmuss50** [comment]
Ah ok, If you are optionally depending on injected interfaces using subprojects/submod would provide compile time safety against accidentaly using a method from an dep injected iface that may not exist.

You would have an 1-EI sub project and a 2-EI sub project each having its own MC jar with respecitve interfaces, and then JIJ each mod into the root project. Hopefully soon that will then allow the X-EI mod that isnt beign used to skip beign loaded all toeather.

**Comment by emilyploszaj** [comment]
Creating subprojects to support recipe viewers is a pretty absurd ask for modders. Requiring compile *and* runtime to load interface injection would be a bandaid fix that would allow for compile time only dependency. The compile time checking is unfortunate, but a scuffed solution is much better than subprojects.

**Comment by modmuss50** [comment]
I agree that gradle doesn't make it so easy, but it does provide the best solution to the issue imo.

I do think there is still something to fix to make it a little nicer than it currently is tho.

**Comment by emilyploszaj** [comment]
As it stands, EMI needs to have a breaking rollback of interface injection, and it cannot reintroduce it until Loom properly handles interface injection for compile only mods. Requiring subprojects for this functionality is not something that I, as an API developer, would ever even consider. I understand that subprojects provide the most *technical* safety, but I fundamentally disagree with calling it the "best" solution, making a subproject is up there on the list of things that would make me refuse to add compat with a mod.

**Comment by modmuss50** [comment]
I agree I wouldn't create a sub project to add support for 3rd party mod. As it stands with what loom can currently provide I still believe that is the best solution, but far from a perfect one. I would perfer to find a great solution that solves everyone's problems that also isnt a quick/hacky workaround.

Another option would be to add something where you create a new sourceset, with a given set of dependendices. Loom would then need the abbility to create an mc jar with the correct injected interfaces for that sourceset's deps.

This wouldnt require any change at runtime, and loom is already most of the way there with the recent changes to support split mc jars, and mods. My WIP branch 0.13 even has sourceset specific mod* dependencies. It would still be more complex than just added a single dep, but shouldn't be more than a few lines of quite simple configuration into your build.gradle. Im not 100% sure what the API for this would look like, I'd have really have to have a play with it.

This would then still give you the same great compile time safety that multi projects would, the possibility but not a requirement to split the mod into multipule (Either JIJ or just build into the same jar).

**Comment by emilyploszaj** [comment]
Truthfully at this point my desired solution is just requiring compile time and runtime to be present to apply interface injection so that games stop crashing and interface injection doesn't have to be avoided. This would be a one line patch based on the code you sent me, and it'd be make them usable for the time being. A more proper solution can be considered in the v2.

**Comment by modmuss50** [comment]
Let me get this clear, does your mod use iface injection for its API? Or just internally? My suggestion above assumed you were hoping to use it for your API (the main design reason for iface injection)? If your just using it internally and not exposed as public api then it should be easy enough to only apply it when its present at compile and runtime.

Sorry if I got the wrong end of the stick.

**Comment by emilyploszaj** [comment]
EMI uses iface injection for its API. It's unnecessary to use but is a convenience wrapper on vanilla types for conversion. The game crashes if a mod only compiles against EMI because in this scenario iface injection is applied. If iface injection required both compile and runtime availability, the game would be able to launch, but users who only compiled against it would not be able to use the iface injection. This is preferable to crashing the game. Of course the ideal solution is a more comprehensive source set situation based on mods you were describing, where a person could compile against interface injection, but run without it, but this has been slated for a later release, and is a much more complex update.
As it stands the breakdown looks like this.

Require compile (current):
- Compile only dep: Crashes
- Runtime only dep: iface injection not available (intended)
- Both: works fine

Require compile and runtime (suggested):
- Compile only dep: iface injection not available (unintended, but tricky to solve)
- Runtime only dep: iface injection not available (intended)
- Both: works fine

**Comment by modmuss50** [comment]
Ok great, thanks for clearing that up. I think we have a resonable short term solution + a longer term solution.

For now/quick fix:

To compile against injected ifaces the dep must be on both the compile and runtime classpath. The API developer may wish to design an API that can be used without iface injection, worse case the mod needs to cast the target to the iface. A sub project can also be used if really desired.

Sorry again for misunderstanding it's been a long day me 👍

**Comment by emilyploszaj** [comment]
Sounds good to me. ETA on when this will be into latest Loom? Need to know how long I have to tell my users to wait, or if I need to do a rollback later.

**Comment by modmuss50** [comment]
I dont have an ETA, I think its resonable to put into 0.12 instead of waiting for 0.13.

**Comment by emilyploszaj** [comment]
If not clear I was asking about the quick fix, just wondering if I need to remove interface injection from my API so it can be used or if it'll be quick fixed within the week and I can just have people wait. If this is a week or more out, I'll just revert my usage of it for now.

**Comment by modmuss50** [comment]
I have opened https://github.com/FabricMC/fabric-loom/pull/689 its getting a little late now to release right into 0.12, so all going well (tests pass and no one has any objections) I can merge it in the morning.

**Comment by emilyploszaj** [comment]
That's wonderful, thanks modmuss :+1:
