### ISSUE TITLE
Error When Importing 19w13b Project

### ISSUE THREAD

**Issue by michelangeloobrien** [FabricMC/fabric-loom#694]
I am working on a mod for 19w13b/3D Shareware v1.34. I have gotten multiple errors, but I have fixed most of them. I removed v2 from build.gradle, and I am using the 1.19 example mod with the versions in gradle.properties changed appropriately so as to not use an old loom version. However, I am still getting this error that prevents the project import from finishing: 

The supplied phased action failed with an exception.
A problem occurred configuring root project '3D Blocks Mod (3D Shareware v1.34)'.
Failed to setup Minecraft, java.lang.RuntimeException: Failed to remap minecraft
Failed to remap minecraft
Failed to remap JAR C:\Users\miche\.gradle\caches\fabric-loom\19w13b\minecraft-merged.jar with mappings from C:\Users\miche\.gradle\caches\fabric-loom\19w13b\net.fabricmc.yarn.19w13b.19w13b.12\mappings.tiny
Unfixable conflicts

I am using VS Code on Windows 11.

**Comment by modmuss50** [comment]
Try using the V1 mappings.

**Comment by michelangeloobrien** [comment]
> Try using the V1 mappings.

Adding :v1 to the mappings makes it unable to find them, and having nothing at the end results in the same error originally shown in this ticket. Adding v2 gives the error:

The supplied phase action failed with an exception. 
A problem occurred configuring root project '3D Blocks (3D Shareware v1.34)'.
Failed to setup Minecraft, java.lang.RuntimeException: Failed to remap Minecraft. 
Failed to remap minecraft
Failed to remap JAR C:\Users\miche\.gradle\caches\fabric-loom\19w13b\minecraft-merged.jar with mappings from C:\Users\miche.gradle\caches\fabric-loom\19w13b\net.fabricmc.yarn.19w13b.19w13b.12-v2\mappings.tiny
duplicate class target name mappings detected
