### ISSUE TITLE
`Configuration 'minecraft' must only have 1 dependency` error across source sets

### ISSUE THREAD

**Issue by SilverAndro** [FabricMC/fabric-loom#713]
The hard cap on one minecraft dependency seems to apply across source sets, unlike other dependency systems for gradle.

This causes issues when, in my case, attempting to setup a kotlin multiplatform project, which manages dependencies per-target with source sets, as you can only have 1 target depend on minecraft.

I'd love to see this restriction lifted somehow, as it seems to be arbitrarily limiting for no obvious reason? It would also allow things like writing tests that verify compatibility with different versions of the game from the main compile target, such as a code change not breaking on 1.19.1 while compiling against 1.19.2 (as well as just generally being a more gradle-esc design).

One concern would be what the "main" minecraft version becomes for things such as run configurations, but I believe this could be solved with some kind of:
- Configuration flag to opt in to this system and manually choose a main version
- Configuration to specify a "main" source set

**Comment by SilverAndro** [comment]
Actually thinking about this more, this could also help with cross-version compat in general

The project im hoping to build specifically is a small shim api over chat + text so that I can rely on it and have my mod work on 1.18.2-1.19.2, if this restriction was released, I could see projects like architectuary picking it up, and devs having to spend less time on updating and have more free time for actually developing

**Comment by modmuss50** [comment]
I have discussed this elsewhere before, its a vast amount of work for very little gain, sub projects work well. It may be possible to get creative and bring the sub projects togeather in one project for the Kotlin stuff? Otherwise use sub projects 👍

**Comment by SilverAndro** [comment]
Funny, my experience is sub projects causing everything to explode the instant you try to cross-depend on them and clear the build folders 😅

And no, the kotlin stuff explicitly only works on source sets because of how the compilation works

**Comment by modmuss50** [comment]
Humm, if you need help with sub projects feel free to ask in one of the discussion channels. This is vast amount of work and complexity (and possibly impossible?).

As for the kotlin stuff im not too sure what to suggest, I wouldnt recomend using it to build multi version mods (there are other ways to do this).
