### ISSUE TITLE
Add a jar manifest option to opt-in and opt-out of remapping when on a mod* configuration.

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-loom#717]
- Manifest entry set to true will always remap (Used by libraries that need to be remapped but dont have a fabric.mod.json)
- Manifest entry set to false will never remap (Could be used by loader and libraries that dont need to be remapped)
- No manifest entry (default) the current status-quo the mod will only be remapped if it has a fabric.mod.json file.

**Comment by Technici4n** [comment]
That would be amazing, I assume that would solve the issue of the JEI API jars not remapping properly to yarn?

**Comment by modmuss50** [comment]
This was done.
