### ISSUE TITLE
Loom uses gradle api methods which are deprecated and will fail with 8

### ISSUE THREAD

**Issue by derklaro** [FabricMC/fabric-loom#724]
I'm not sure if you're aware of that situation, but a lot of deprecation warnings in our build are currently triggered by loom, so I tought I would list them in an issue.

#### Invocation of Task.project at execution time has been deprecated.

* `at net.fabricmc.loom.task.PrepareJarRemapTask.run(PrepareJarRemapTask.java:80)`
* `at net.fabricmc.loom.task.RemapJarTask.run(RemapJarTask.java:118)`
* `at net.fabricmc.loom.task.AbstractRemapJarTask.lambda$submitWork$1(AbstractRemapJarTask.java:116)`

#### Listener registration using Gradle.buildFinished() has been deprecated.
* `at net.fabricmc.loom.util.DeprecationHelper$ProjectBased.<init>(DeprecationHelper.java:53)`
* `at net.fabricmc.loom.util.service.UnsafeWorkQueueHelper.create(UnsafeWorkQueueHelper.java:46)`

#### Build service 'LoomJarManifestService:bridge' is being used by task XXX without the corresponding declaration via 'Task#usesService'.

* `at net.fabricmc.loom.task.AbstractRemapJarTask$AbstractRemapAction.lambda$modifyJarManifest$0(AbstractRemapJarTask.java:168)`

A full build scan of the build is available here: https://scans.gradle.com/s/b26vrnusnvfmu

**Comment by modmuss50** [comment]
What loom version are you using? We are running the intergration tests against 8.0 gradle nightly with `--warning-mode fail` and not seeing these.

**Comment by derklaro** [comment]
I was running 1.0.4 and just tested with 1.0.7 and the same warnings are visible. Might be that these warnings are not visible without the preview feature enabled? https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:stable

**Comment by modmuss50** [comment]
Yes, that will be why. Loom is fundamentally incompatible with the configuration cache.

I have already opened an issue for this here: https://github.com/FabricMC/fabric-loom/issues/640

I dont see how we can support it without incurring a major performance hit.

**Comment by derklaro** [comment]
Oh, didn't see that issue - just searched for Gradle 8 😂 Well then :)

**Comment by modmuss50** [comment]
Just had another look at what it would take to support it, and it seems its still basically impossible. Gradle does not offer a way to share resources (such as tiny remapper) across sub projects.
