### ISSUE TITLE
Runtime crashing with interface injection

### ISSUE THREAD

**Issue by emilyploszaj** [FabricMC/fabric-loom#725]
Similar issue to the past, I'm getting reports of EMI crashing mods in a dev environment when depended on compile time only in 1.0-SNAPSHOT loom with a class not found. Interface injection seems to apply based on compile dependencies and when the class cannot be resolved at runtime it crashes consistently.

**Comment by Juuxel** [comment]
https://github.com/FabricMC/fabric-loom/blob/ffe5e955c5d908b8ab14f157b273e4a582d7dd0a/src/main/java/net/fabricmc/loom/configuration/ifaceinject/InterfaceInjectionProcessor.java#L184-L200

Hmm, it definitely does filter based on the jar being both in compile and runtime classpaths

**Comment by Slomaxonical-907** [comment]
![image](https://user-images.githubusercontent.com/77751655/191328370-f6efcc3e-5513-4f6d-bc48-63777dec3b32.png)

**Comment by emilyploszaj** [comment]
@modmuss50 Create is running into this problem again, [here is their build gradle](https://github.com/Fabricators-of-Create/Create/blob/bd238dab1194daf3fe310831f36923379727a3bf/build.gradle).
They seem to do as is required, use loom `1.0.+`, only depend on EMI (the mod with interface injections) compile time, and conditionally runtime, however when they don't depend on it at runtime, they get the `NoClassDefFoundError`.
If they remove the conditional runtime dependency, it doesn't resolve the issue.
This is a pretty serious issue that's affecting my library, and dropping support for interface injections is an unfortunate thing to have to do.

**Comment by modmuss50** [comment]
The cause for this was found here: https://github.com/FabricMC/fabric-loom/issues/759, was something very silly.. Fix here: https://github.com/FabricMC/fabric-loom/pull/769
