### ISSUE TITLE
Failed to setup Minecraft

### ISSUE THREAD

**Issue by CaryCatZ** [FabricMC/fabric-loom#734]
Can not configure project.
I tries so many times but it can not configure project yet.

Failed to setup Minecraft, com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 30 column 2 path $.depends

[logfile.log](https://github.com/FabricMC/fabric-loom/files/9723950/logfile.log)

**Comment by Phoenix-Starlight** [comment]
Did you check the json files at line, 30, character 2.
