### ISSUE TITLE
Cache the fapi pom when using `fabricApi.module`

### ISSUE THREAD

**Issue by dexman545** [FabricMC/fabric-loom#740]
Pretty consistently after restarting idea/gradle builds fail saying that it couldn't parse the pom... even when the fapi version doesn't change

**Comment by modmuss50** [comment]
Can I have the log please, this is already cached, and supports offline mode:

https://github.com/FabricMC/fabric-loom/blob/dev/1.0/src/main/java/net/fabricmc/loom/configuration/FabricApiExtension.java#L119

**Comment by dexman545** [comment]
Strange, I can no longer reproduce this. It was pretty consistent before. If it happens again I'll save the log and reopen.
