### ISSUE TITLE
Build fails when a subproject references another one 

### ISSUE THREAD

**Issue by natanfudge** [FabricMC/fabric-loom#752]
To reproduce:
1. git clone https://github.com/natanfudge/Loom-Cachelock-bug
2. Import project in IDEA
3. Notice: 
>  Found existing cache lock file, rebuilding loom cache. This may have been caused by a failed or canceled build.
4. Notice how build fails: 
> Caused by: java.lang.RuntimeException: Failed to setup Minecraft, java.io.UncheckedIOException: Failed to check file from zip

Sometimes the build doesn't fail, but it does rebuild the loom cache very time, which takes a LOT of time. This shouldn't happen.

**Comment by modmuss50** [comment]
Hi, please see the wiki page about depending on sub projects: https://fabricmc.net/wiki/documentation:fabric_loom#depending_on_sub_projects

`modImplementation (project(":subprojectB"))` is wrong, you want `implementation project(path: ":subprojectB", configuration: "namedElements")`
