### ISSUE TITLE
Advanced question?: Sharing code between mod implementations using gradle submodules 

### ISSUE THREAD

**Issue by aleksilassila** [FabricMC/fabric-loom#753]
Hey,

I have a question regarding a gradle multiproject setup where common mod code is shared between mc version implementations. I hope this is correct place to ask a question, I'm kind of running out of places to ask since the question is quite advanced I suppose :,)

So I have each version implementation as their own submodule, as shown in this [repository](https://github.com/aleksilassila/litematica-printer/tree/subprojects-example), and my goal is to have all the common code and logic put into the [common](https://github.com/aleksilassila/litematica-printer/tree/subprojects-example/common) submodule, which can then be required and used by each implementation. Currently the versions share a lot of files, that are identical between implementations, because the minecraft api interfaces haven't changed between the versions. These are the files that I would want to move into the common code module.

[CommonCode.java](https://github.com/aleksilassila/litematica-printer/blob/subprojects-example/common/src/main/java/me/aleksilassila/litematica/printer/common/CommonCode.java) is an example of how the common code might look like. 
```java
package me.aleksilassila.litematica.printer.common;

import net.minecraft.client.MinecraftClient;

public class CommonCode {
    public static String getVersion(MinecraftClient client) {
        return client.getGameVersion();
    }

    public static String ping(String string) {
        return string;
    }
}
```
Now: In the implementation submodules, is it possible to somehow only require the common files, so that they would use the implementation's minecraft mappings instead of whatever I have defined in the build.gradle of the common module? In other words CommonCode.java#3 `import net.minecraft.client.MinecraftClient;` would import from 1.19 when used in that implementation submodule and 1.18 when used there.

Currently, I have [common/build.gradle](https://github.com/aleksilassila/litematica-printer/blob/subprojects-example/common/build.gradle) to depend on 1.19 minecraft mappings, but when I try to import the common module in [implementation/v1_19/build.gradle](https://github.com/aleksilassila/litematica-printer/blob/subprojects-example/implementation/v1_19/build.gradle), running the minecraft client gets me the following error:
```
java.lang.NoSuchMethodError: 'java.lang.String me.aleksilassila.litematica.printer.common.CommonCode.getVersion(net.minecraft.client.MinecraftClient)'
```
I really don't have enough knowledge on how the fabric works to go forward from here.

Alternatively, does someone come up with a better way to organize the code between minecraft version implementations? I know that this would be a bit unsafe way of managing the different versions, but I feel like it's better than what I had before. I previously had a separate branch for each version, with all the changes copied over manually and then having a single file called `Implementation` in each version to contain all the version-specific logic, but that has been extremely tedious to maintain. Also someone recommended that I should create "proxy classes" for all the Minecraft classes that I use, but I don't know how viable that is since I use quite a lot of Minecraft classes.

Any help is greatly appreciated.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
