### ISSUE TITLE
Unable to run `gradle wrapper`

### ISSUE THREAD

**Issue by Sammcb** [FabricMC/fabric-loom#754]
I am working on a Quilt mod, and started by setting up the build files. I ran `gradle wrapper` to initialize the project, and got this error:

```shell
$ gradle wrapper --distribution-type all

> Configure project :
Quilt Loom: 0.13.1

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'code'.
> Failed to notify project evaluation listener.
   > Range [0, 16) out of bounds for length 10
   > Cannot get MinecraftProvider before it has been setup

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

The command runs successfully with `Quilt Loom: 0.12.40`. Looking at the [changes](https://github.com/QuiltMC/quilt-loom/commit/c834443fd4eed9d4c7fa7c94f55169395cda6b7d) between `0.12.40` and `0.13.1` I saw that the fabric-loom version was [updated](https://github.com/FabricMC/fabric-loom/compare/8b37b9a3c64d00aa550deee7c2dcb845e35a3f31...a8c2bb1c64edc1012b0dc1f57280fb1b810d562a#diff-c6c892cd1e66d91e977503e0854940da0b3a33a6859507b21b2f7cd3bd4a33c2), which includes [this change](https://github.com/FabricMC/fabric-loom/compare/8b37b9a3c64d00aa550deee7c2dcb845e35a3f31...a8c2bb1c64edc1012b0dc1f57280fb1b810d562a#diff-c6c892cd1e66d91e977503e0854940da0b3a33a6859507b21b2f7cd3bd4a33c2R290).

Please let me know if there's any other info I can provide. I'm not entirely sure whether this is a fabric loom issue or a quilt loom issue, so apologies if this doesn't apply here (I will opening a similar issue on the quilt loom project).

Thanks so much!

**Comment by OroArmor** [comment]
What is your `build.gradle` file?

**Comment by Sammcb** [comment]
[build.gradle.kts](https://github.com/Sammcb/SynthesizerMod/blob/main/build.gradle.kts)

**Comment by modmuss50** [comment]
Your not using fabric loom…
