### ISSUE TITLE
"idea" does not delete old run configurations

### ISSUE THREAD

**Issue by quat1024** [FabricMC/fabric-loom#76]
Hey,

I'm updating an old Fabric mod from 18w50a to the latest prerelease. I needed to delete the old run configurations and generate new ones, since the old ones from back then had some Launchwrapper/18w50a-related cruft in them. However, running `gradlew idea` didn't overwrite the old "Minecraft Client"/"Minecraft Server" run configs, and they still mentioned 18w50a in the command string and depended on the Launchwrapper class.

What's more, removing the run configurations using the minus button in IDEA (
![image](https://user-images.githubusercontent.com/2068021/56454816-5b1b5080-6324-11e9-85a4-5af97c86c36f.png)
), and then running `gradlew idea` again, simply *caused the previously-"deleted" configuration to appear in the menu again* (!)

I needed to open my .iws file manually and remove the old run configurations from the XML.

When I did this, I discovered that Loom seems to have been stacking up a bunch of run configurations in my .iws file. A new copy of both the client and server configs appears every time I run `gradlew idea`.

![image](https://user-images.githubusercontent.com/2068021/56454845-f280a380-6324-11e9-9764-bfcc538b8852.png)

IDEA 2018.2.3 community (yeah, i know, pretty old by now)
Windows 7
Loom 0.2.1-SNAPSHOT

**Comment by modmuss50** [comment]
This was changed to prevent the loss of settings.
