### ISSUE TITLE
Suggestion: `ModSettings.sourceSet` overload taking the name instead of the instance

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#764]
My use case: I have a multiproject build where the `java` plugin isn't applied to the root project. I'm configuring multiple Loom subprojects from this file, but accessing the source set container is a bit unwieldy in Kotlin DSL without the typesafe accessors:
```kotlin
sourceSet(extensions.getByName<SourceSetContainer>("sourceSets").getByName("main"))
sourceSet(project(":b").extensions.getByName<SourceSetContainer>("sourceSets").getByName("main"))
```

This could just be
```kotlin
sourceSet("main") // assume current project
sourceSet("main", project(":b"))
```

This is bit of a niche use case but IMO it could still simplify code (`sourceSets.main` => `'main'` for example).

**Comment by modmuss50** [comment]
Fixed for 1.1, thanks 👍
