### ISSUE TITLE
A way to generate translation files in loom

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric-loom#776]
Since you can’t add all the translations you need in a mod by hand if you don’t know them or have the time can you add a task that uses a online translation system to make them ready for use in mod
For example endrus log
{ block.endrus.endrus_log:endrus log}
with the last bit using the site translation 
For the translation it is linked to

**Comment by modmuss50** [comment]
There are plently of existing 3rd party sites and tools that you can use. I have used Crowdin for one of my mods without issue. There may be existing gradle plugins and/or github actions that you could use to automate it, A few years back I wrote my own Gradle tasks to do it.

I dont think there is anything loom needs to do here.

**Comment by Danjhop4** [comment]
What tools
