### ISSUE TITLE
Fully take advantage of Gradle workers to avoid eager tool downloads

### ISSUE THREAD

**Issue by zml2008** [FabricMC/fabric-loom#779]
Currently, Gradle will download almost all the tools Loom uses for various tasks eagerly while configuring the project. This uses extra disk space, and especially on CI can slow down builds at the configuration stage.

Some tools are never used (like alternate decompilers), or only sometimes used (like mercury), so their downloads could be avoided by using the Worker API.

See an example of the worker setup [here](https://github.com/SpongePowered/VanillaGradle/blob/master/subprojects/gradle-plugin/src/main/java/org/spongepowered/gradle/vanilla/task/DecompileJarTask.java#L169) (process isolation) or [here](https://github.com/SpongePowered/VanillaGradle/blob/0.1/src/main/java/org/spongepowered/gradle/vanilla/task/AccessWidenJarTask.java#L149) (only classloader isolation), with the worker class itself [in a separate source set to limit use of the worker-only dependencies](https://github.com/SpongePowered/VanillaGradle/blob/517410b75a3c521e37e1833a751a4c9cca49a020/subprojects/gradle-plugin/src/jarDecompile/java/org/spongepowered/gradle/vanilla/internal/worker/JarDecompileWorker.java)

Gradle will cache worker processes for potential reuse, which is a bit of a disadvantage in our use case since decompiler workers aren't often reused. Finding a solution to that is a bit of an open discussion on their end -- see gradle/gradle issue #22076 for tracking that.

**Comment by modmuss50** [comment]
> Finding a solution to that is a bit of an open discussion on their end

Decompilers already use a forked worker [here](https://github.com/FabricMC/fabric-loom/blob/dev/1.0/src/main/java/net/fabricmc/loom/task/GenerateSourcesTask.java#L185) and we force them to shutdown with some gross hacks [here](https://github.com/FabricMC/fabric-loom/blob/dev/1.0/src/main/java/net/fabricmc/loom/util/gradle/WorkerDaemonClientsManagerHelper.java) so thats not a major issue for us.

I think to do this well we would need to split parts of loom (such as the source remapper and the decompilers) into their own sourcesets/subprojects so we can be sure we do not depend against libraries in the wrong context.

I would also like to use this idea to lazily download tools such as class tweaker based on the version included with loader. This will make it easier to make changes to it in the future.

**Comment by modmuss50** [comment]
This was done for the decompilers.
