### ISSUE TITLE
Class name references in refmap aren't remapped correctly

### ISSUE THREAD

**Issue by creeper123123321** [FabricMC/fabric-loom#78]
https://github.com/FabricMC/Mixin/commit/d7119e129a4f216a15299846e0035f53ba795905#diff-ead31af018cf3372e81012e962c252d8R771
![screenshot](https://cdn.discordapp.com/attachments/507982478276034570/569221077520089125/Captura_de_tela_de_2019-04-20_15-00-57.png)
Fabric Mixin expects a ``Lpath/to/class/ClassName;`` format but Loom generates in a ``path.to.class.ClassName`` format

**Comment by asiekierka** [comment]
Ah, thanks, that's a side effect of the update I forgot about.

**Comment by asiekierka** [comment]
Wait... why is this on Loom?

**Comment by asiekierka** [comment]
>Fabric Mixin expects a Lpath/to/class/ClassName; format but Loom generates in a path.to.class.ClassName format

Not true. remapClassName() transparently maps from one to the other.
