### ISSUE TITLE
Refmap problems with client-only mixin with mixin config json in common srcset

### ISSUE THREAD

**Issue by Technici4n** [FabricMC/fabric-loom#788]
Basically I have a `BlockMixin` in the client srcset, but it's referenced in the common mixin json.

Loom creates two refmaps (`Modern-Industrialization-refmap.json` and `client-Modern-Industrialization-refmap.json`), but only the former is included in the mixin json. While this is easily fixable, it leads to MI 1.6.0 crashing in client envs. It would be nice if Loom could emit some sort of warning/error at least.

More info about the setup: https://github.com/AztechMC/Modern-Industrialization/blob/f61eec6ef536997db0527286adc96e8ef6fffde3/src/main/resources/modern_industrialization.mixins.json#L13.

**Comment by zml2008** [comment]
For my split environment use cases, I treat each side as a separate mixin set -- so there's a client mixin config, plus a common one. This lets the mapping between refmaps and mixin jsons be simpler, and both configs can be easily referenced in a FMJ.

Any change to Mixin configs or the AP would be way more complex than just having multiple mixin configurations.

**Comment by Technici4n** [comment]
I agree, and I ended up changing to different configs to fix my issue. I think the best course of action would be for Loom to throw an exception in these cases (assuming they can easily be detected).

**Comment by modmuss50** [comment]
Im not sure of an easy way to deal with this, especially on the loom side. All of this is handled by the mixin AP, this has no sense of the other sourceset.

The fix here is to use 2 mixin configs.
