### ISSUE TITLE
Colored output is broken in NeoVim

### ISSUE THREAD

**Issue by eaglesemanation** [FabricMC/fabric-loom#794]
### Problem
Currently `gradle vscode` generates a launch.json file with a `"console": "internalConsole"` field. While it works fine in VSCode, I'm using this file from NeoVim, and `internalConsole` maps to REPL window in nvim-dap-ui, which does not support ANSI colors. 

### Proposed fix
Changing generated value to `integratedTerminal` would fix this while keeping VSCode experience basically the same. I don't have a Windows machine set up to verify that VSCode will keep working fine there as well

### Alternative fixes
- Add another command `gradle nvim` which will generate correct launch.json for nvim. I don't think that's a good solution, because launch.json should be universal. Plus it would indicate that you actively support NeoVim as an IDE, which I'm not asking for. (Even though it would be cool)
- Somehow disable colored output for debug output. Don't know enough about minecraft internals to decide if that's a viable solution + this would degrade developer experience.

**Comment by modmuss50** [comment]
Hi,

Thanks for the issue.

> launch.json should be universal

Is this really a standard? The documentation I follow for this is here: https://github.com/microsoft/vscode-java-debug/blob/main/Configuration.md It seems to be quite specific to the VScode java plugin, and is also placed in the `.vscode` folder. Using `integratedTerminal` seems like a reasonable change anyway.

> Somehow disable colored output for debug output. Don't know enough about minecraft internals to decide if that's a viable solution

Its currently only enabled for specific IDEs using some jank code here: https://github.com/FabricMC/fabric-loom/blob/912e54cd7ac3225777808e3060171615f8478139/src/main/java/net/fabricmc/loom/task/launch/GenerateDLIConfigTask.java#L86-L93

The ansi colors come from a custom log4j config found [here](https://github.com/FabricMC/fabric-loom/blob/dev/1.0/src/main/resources/log4j2.fabric.xml). There is also another similar issue here: https://github.com/FabricMC/fabric-loom/issues/726 about enabling this for eclipse, so its likely we could clean this code up and fix this issue for both.

> Add another command gradle nvim which will generate correct launch.json for nvim

I think this might be the best solution, im always happy to support new IDEs, just requires someone who wants it and is able to provide me with details on how to support it. I might need to have a play with it to help test and write some documentation for it. You mention you are using `nvim-dap-ui` are there any other plugins required to import the Gradle project?

**Comment by eaglesemanation** [comment]
> Is this really a standard?

Not in a sense that it's a standard between multiple IDEs, rather in a sense that if I see `.vscode/launch.json` in a project - I expect it to work in VSCode.

> Are there any other plugins required to import the Gradle project?

Theoretically the only thing needed is [nvim-dap](https://github.com/mfussenegger/nvim-dap) which provides a [function to load launch.json](https://github.com/mfussenegger/nvim-dap/blob/700a3c7d6fbe5b07bee74e9952b456120d355c47/doc/dap.txt#L273). By default, this function is limited to actual json sepc, unlike VSCode which seems to allow json5, fortunately this project already avoids it. (Probably unintentional, but that's still a win)

In reality, there are a bunch of plugins needed for a good bare-bones setup:
- Plugin manager: [packer.nvim](https://github.com/wbthomason/packer.nvim)
- External apps manager: [mason.nvim](https://github.com/williamboman/mason.nvim) (recommended), [nix](https://nixos.org/) (what I use, wouldn't recommend including it in a Minecraft modding documentation 😅)
- Simplified language server config: [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) + [mason-lspconfig.nvim](https://github.com/williamboman/mason-lspconfig.nvim)
- Autocompletion: [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) + [cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp)
- Integration with debuggers: [nvim-dap](https://github.com/mfussenegger/nvim-dap) + [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui)
- Java specific configuration: [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls)

The other option is to start with a preconfigured setup, such as [LunarVim](https://github.com/LunarVim/LunarVim) which comes with all of those plugins preinstalled and a bunch more. But it seems like it doesn't fully support java yet, or maybe it requires some additional configuration, I'm not sure, never used it.

Lastly you could check [my own config](https://github.com/eaglesemanation/nix-config/tree/main/home-manager/bundles/nvim/nvimrc), but only resort to it as a last measure, because it's not pretty)

**Comment by modmuss50** [comment]
Humm, that does seem quite involved, something that might be out of sope for us to support. (Mostly worried if other people want help setting it up).

For now does running `gradlew.bat vscode --console=plain` generate a sutible file?

**Comment by eaglesemanation** [comment]
Yeah, `gradle vscode --console=plain` works fine, but obviously colors are gone, and I would love for them to be there.

As you said, changing launch.json to use `integratedTerminal` would be a sensible change, hope you could do that

**Comment by modmuss50** [comment]
Ah yeah, my bad forgot that colors worked with that. Yes I think I will do that 👍

**Comment by eaglesemanation** [comment]
Had some free time, fixed it myself. Spent more time figuring out how to use own jar as a gradle plugin, should've read README

**Comment by modmuss50** [comment]
Thanks, closing this as fixed as I dont think there is anything more to do for now. Thanks.
