### ISSUE TITLE
Interface injection chooses an overly broad dependency set

### ISSUE THREAD

**Issue by zml2008** [FabricMC/fabric-loom#797]
I have a project where my main source set has a limited subset of fabric api modules on the compile classpath, and a separate testmod source set has all of fabric API available at compile- and runtime.

Currently interface injection sums all remapped configurations together, which injects unresolvable classes onto the compile classpath for some configuration, producing errors like:

```
C:\Users\abby\dev\kyori-text\adventure-platform-fabric\src\main\java\net\kyori\adventure\platform\fabric\impl\server\ServerPlayerAudience.java:236: error: cannot access FabricItem
    final ItemStack bookStack = new ItemStack(Items.WRITTEN_BOOK, 1);
                                ^
  class file for net.fabricmc.fabric.api.item.v1.FabricItem not found
C:\Users\abby\dev\kyori-text\adventure-platform-fabric\src\main\java\net\kyori\adventure\platform\fabric\impl\server\ServerPlayerAudience.java:237: error: cannot access FabricItemStack
    final CompoundTag bookTag = bookStack.getOrCreateTag();
                                         ^
  class file for net.fabricmc.fabric.api.item.v1.FabricItemStack not found
```

Is there a sensible fully automated default here? My feeling is that this may require adding additional configurability to the interface injection extension, maybe taking a list of remapped configurations to use for injection?

I've [temporarily worked around this issue](https://github.com/KyoriPowered/adventure-platform-fabric/blob/mc/1.19/build.gradle.kts#L143) by disabling dependency interface injection entirely.

**Comment by modmuss50** [comment]
Please see #799, the idea is to only apply transforms from dependent mods on configurations targetting the main or client source sets by default.

**Comment by DrMrBepis-hub** [comment]
So my issue with adding a new custom sword is that when I try to copy other people (KaupenJoe), they all do FabricItemSettings, unfortunately it only gives me the option to do FabricItem.Settings and that completely screw me over.

This is what Im trying to do but I get stuck on it.

 public static final Item GREATSWORD = registerItem("greatsword", new FabricItem.Settings());

NOTE: I have the json file, textures and everything else BUT the actual ITEM...
