### ISSUE TITLE
Unable to load class org.cadixdev.mercury.Mercury

### ISSUE THREAD

**Issue by asdu5asg6da8sjd** [FabricMC/fabric-loom#809]
**Moved to discussion [#2857](https://github.com/orgs/FabricMC/discussions/2857)**

The title explains it all.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
