### ISSUE TITLE
[Loom 1.1] Not able to use classes from included deps from dependencies

### ISSUE THREAD

**Issue by oliviathevampire** [FabricMC/fabric-loom#812]
This class will show the issue when viewed in intellij. Can't use Config class or ConfigData class and other classes from it even tho jar is included in external libs in intellij. https://github.com/oliviathevampire/fabric-example-mod-with-vampirelib/blob/1.19/src/main/java/net/fabricmc/example/HGConfig.java

**Comment by modmuss50** [comment]
This is working as intended, and is a breaking fix from 1.0.
