### ISSUE TITLE
Add a flag like --rebuild-loom-cache to force rebuilding of loom cache to the genSources task

### ISSUE THREAD

**Issue by TechPro424** [FabricMC/fabric-loom#819]
Add a flag like `--rebuild-loom-cache` to force rebuilding of loom cache to the `genSources` task, as there are situations for me when using the `genSources` task where it is successful only when loom cache is rebuilt

**Comment by modmuss50** [comment]
`--refresh-dependencies` does this.

> is successful only when loom cache is rebuilt

This sounds like the real issue that needs to be fixed, have you got any more info?

**Comment by TechPro424** [comment]
> `--refresh-dependencies` does this.
> 
> > is successful only when loom cache is rebuilt
> 
> This sounds like the real issue that needs to be fixed, have you got any more info?

@modmuss50 I created a new issue for this https://github.com/FabricMC/fabric-loom/issues/820
