### ISSUE TITLE
genSources task is successful only when loom cache is rebuilt

### ISSUE THREAD

**Issue by TechPro424** [FabricMC/fabric-loom#820]
> is successful only when loom cache is rebuilt

This sounds like the real issue that needs to be fixed, have you got any more info?

_Originally posted by @modmuss50 in https://github.com/FabricMC/fabric-loom/issues/819#issuecomment-1402035089_

I use VSC for making Fabric mods. When I run `./gradlew genSources`, I get an error saying `project root\.gradle\loom-cache\1.19.3\net.fabricmc.yarn.1_19_3.1.19.3+build.5-v2\minecraft-project-@-common-named.jar: The process cannot access the file because it is being used by another process`

`minecraft-project-@-common-named.jar` is also replaced by any other jar in the same folder, such as `minecraft-project-@-clientOnly-named.jar`, it's not always the same jar

I have to keep running this again and again (I did not know about `--refresh-dependencies` till yesterday) till I get the message `Found existing cache lock file, rebuilding loom cache. This may have been caused by a failed or cancelled build`. If I get the message, there is a good chance it is successful, but the possibility of the above error occuring is still there.

**Comment by modmuss50** [comment]
What loom version are you using? This should have been fixed as I think this may be a duplicate of: https://github.com/FabricMC/fabric-loom/issues/813

**Comment by TechPro424** [comment]
> What loom version are you using? This should have been fixed as I think this may be a duplicate of: #813

`1.0-SNAPSHOT`

**Comment by modmuss50** [comment]
Please try with 1.1, ensuring you are using 1.1.4 or newer in the log.

**Comment by TechPro424** [comment]
> Please try with 1.1, ensuring you are using 1.1.4 or newer in the log

Fixed, thanks a lot!
(The template mod generator generates `1.0-SNAPSHOT` by default, should I open a new issue for that?)

**Comment by modmuss50** [comment]
> The template mod generator generates 1.0-SNAPSHOT by default

Thats intended for now, 1.1 is currently in beta.

Hopefully in a few days once more people have tested it I will make it the default.
