### ISSUE TITLE
a odd error i got with some of my dev setups all are the same

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric-loom#822]
![error](https://user-images.githubusercontent.com/106870098/215545368-d767827f-3d12-4779-a6b4-af4627731dfc.png)
i just copy a set up so everything is the same

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
