### ISSUE TITLE
modCompile fails to build when combined with other configurations for different classifiers

### ISSUE THREAD

**Issue by UpcraftLP** [FabricMC/fabric-loom#83]
when combining `modCompile` (for the main artifact) and other classifiers (ex. `implementation` or `compileOnly` on the `api` jar), loom fails to provide that artifact.

ex.
`modCompile "com.github.GlassPane:Mesh:${mesh_version}"`
`implementation "com.github.GlassPane:Mesh:${mesh_version}:api"`

will lead to the following error:
```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find Mesh-api.jar (project :Mesh).```

**Comment by falkreon** [comment]
need more info; In one project I'm combining modCompile, compileOnly, implementation, shadow, testImplementation, and testRuntimeOnly, with some artifacts shared between them.

loom isn't really providing artifacts; that's gradle's maven resolver. What does your repositories block look like? Have you made sure that the `com.github.GlassPane:Mesh:${mesh_version}:api` jar exists somewhere in those repos?

Edit: Looking at the "official" repository listed in the GlassPane github, 1.0.0-SNAPSHOT build 4 was the last version that provided an `api` qualifier jar. If you're trying to pull down build 9 or so, then an error here is correct.

**Comment by UpcraftLP** [comment]
>Edit: Looking at the "official" repository listed in the GlassPane github, 1.0.0-SNAPSHOT build 4 was the last version that provided an api qualifier jar. If you're trying to pull down build 9 or so, then an error here is correct.

I have the artifacts in my local maven repository, and gradle itself can pull both of them just fine (if using other configurations that are nod `modCompile`).

However, I need `modCompile` to work on both the mod jar AND the api, which doesn't work.

**Comment by asiekierka** [comment]
Could you try 0.2.4?

**Comment by modmuss50** [comment]
I believe this is just the way gradle works. If its still an issue please open a new issue.
