### ISSUE TITLE
`KotlinPluginUtils.getKotlinMetadataVersion` returns unexpected version if kotlinx-metadata-jvm `>=0.6.0` is loaded

### ISSUE THREAD

**Issue by SilverAndro** [FabricMC/fabric-loom#842]
Reproducible notably by trying to use https://github.com/Kotlin/binary-compatibility-validator `>=0.13.0`. 

With release 0.6.0 the `Implementation-Version` field changed to a new format, at the moment being `0.6.0-1.8.0-26`. This causes `remapJar` to fail as it tries to resolve kotlinx-metadata with that version, while the actual version is only `0.6.0`

**Comment by modmuss50** [comment]
Look like 0.6.0 of kotlinx-metadata-jvm broke the API as well.

**Comment by modmuss50** [comment]
Looks like I need to fully rewrite the Kotlin metdata remapper 🙃

**Comment by modmuss50** [comment]
Fixed in 1.2, this will likely be an ongoing issue to keep ontop of sadly.
