### ISSUE TITLE
Missing client implementation code in multi module workspace

### ISSUE THREAD

**Issue by CebbyS** [FabricMC/fabric-loom#845]
Hi,

I am working on a multi-module project. I have **core**, **api**, and **implementation** modules. 
When I am linking the **api** module as a dependency for **core** module, I do it by following the discussion here - to avoid issues with modImplementation requiring the module to be built once: https://github.com/FabricMC/fabric-loom/issues/746

`implementation project(path: ":api", configuration: 'namedElements')`

In all modules I have declared the following loom configuration:
```java
loom {
    splitEnvironmentSourceSets()
    mods {
        modid {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}
```

What I face now, is that the client sources/code are not found/available in the project which includes the **api** module.
Is there a way to link the client code as a dependency?

**Comment by modmuss50** [comment]
See: https://fabricmc.net/wiki/documentation:fabric_loom#depending_on_sub_projects this details how to depend on a sub project with split sources.
