### ISSUE TITLE
dependencies that use JarinJar don't get remapped

### ISSUE THREAD

**Issue by KP2048** [FabricMC/fabric-loom#852]
the specific mod in question is this
https://github.com/thedarkcolour/KotlinForForge
from what i can tell, the structure of the jars is this:
root jar
| kotlin library stuff
| mod jar
| - actual mod that needs to be remapped
| forge language extention jar
| - contains the stuff forge looks for to be able to load kotlin based mods
| kotlin lib jar
| - contains the forge specific kotlin stuff

essentially, that mod jar doesn't get remapped, only the root jar, which isn't even really a mod. moreover, the inner jars don't even get added to the external libraries list in my ide, but if i use the modApiMapped one, they do show up, but they aren't mapped and so don't load correctly when i start the game

**Comment by KP2048** [comment]
I'm using architectury, that's why there are forge stuff, but I was told by the architectury devs that this is an artifact of how fabric loom handles jar in jar

**Comment by modmuss50** [comment]
Loom strips JIJ's and uses the maven metadata. For fabric stuff you should use fabric's kotlin module.

**Comment by KP2048** [comment]
But I'm using architectury. The fabric one works fine on the fabric side, but not on the forge side for obvious reasons. Is there a reason why you strip the jar in jar dependencies?

**Comment by modmuss50** [comment]
I have nothing to do with forge or architectury, if they do/need something diffrent thats on them. We dont use them as maven/gradle by design can select the correct version of a depdency, trying to do this for JIJ would basiclaly require loading up fabric-loader to compute the set of mods to load.
