### ISSUE TITLE
Transitive dependencies are no longer accessible in 1.1

### ISSUE THREAD

**Issue by TropheusJ** [FabricMC/fabric-loom#855]
I have a dependency on Trinkets to add compatibility, which uses and transitively pulls in Cardinal Components API.
Declaration:
```java
def compat(DependencyHandler deps) {
    ...
    deps.modCompileOnly("dev.emi:trinkets:$trinkets_version") { exclude(group: "com.terraformersmc") }
    ...
}
```
Functional compatibility as of Loom 1.0:
```java
Optional<TrinketComponent> optional = TrinketsApi.getTrinketComponent(player);
if (optional.isPresent()) {
    TrinketComponent component = optional.get();
    if (component.isEquipped(AllItems.GOGGLES.get())) {
         return true;
    }
}
```
After updating to Loom 1.1, this code no longer compiles:
![image](https://user-images.githubusercontent.com/60247969/230790485-db4c823e-351a-4da6-aa8c-cc7e5e5e5c34.png)

The fix is simple, but this does not seem intentional, as it was not mentioned in the changelog.

**Comment by modmuss50** [comment]
Loom 1.1 fixed a bug where transive dependecies were applied to the wrong scope.

This is working as intended as here https://github.com/emilyploszaj/trinkets/blob/main/build.gradle#L42-L43 cardinal-components is only `implementation` and not on the `api` configuration. See the gradle docs on this here: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

**Comment by TropheusJ** [comment]
makes sense
