### ISSUE TITLE
Multi-project project fails to sync when loom 1.1 is used

### ISSUE THREAD

**Issue by TropheusJ** [FabricMC/fabric-loom#856]
When syncing a multi-project project in IDEA, it fails with an error.

Full log: https://gist.github.com/TropheusJ/60d693ae0f157a428c3eaf58610a980a
Important part: `class net.fabricmc.loom.util.service.BuildSharedServiceManager$Inject cannot be cast to class net.fabricmc.loom.util.service.BuildSharedServiceManager`
Project: https://github.com/TropheusJ/create-monorepo

This worked fine on older versions of loom. 
enabling multi-project optimization has no effect.

**Comment by modmuss50** [comment]
As far as I can tell this is a gradle bug/oddity, if you follow the gradle docs for applying plugins only to sub projects it should work. All of your plugin versions must be defined in the root build.gradle file with `apply false`

See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl and https://github.com/FabricMC/fabric-loader/blob/master/build.gradle#L15

**Comment by TropheusJ** [comment]
Added this to the root project:
```groovy
plugins {
    id "fabric-loom" version "1.1.+" apply false
}
```
And it seems to have worked.

**Comment by BluCobalt** [comment]
![image](https://user-images.githubusercontent.com/37788256/231868752-d3e74133-296b-47ff-a94d-216f526e7e06.png)
worked for me with a kotlin buildscript

**Comment by douzooo** [comment]
I tried it too and still running into the same issue using legacy fabric
and multi modules
https://github.com/NebulaBuilds/NebulaClient
https://pastebin.com/h1eLWDv8
