### ISSUE TITLE
Loom is very slow to download files, often hanging for 10+ minutes

### ISSUE THREAD

**Issue by jellysquid3** [FabricMC/fabric-loom#877]
I'm not sure if this is an issue with Gradle or Loom itself, but in the interest of having _someone_ be aware of it...

It seems that on any Linux distro (Fedora, Ubuntu, Gentoo, and even Arch), that Loom will often take an extremely long time to download certain files, and will even sometimes hang for tens of minutes (most often while downloading assets.) 

An easy way to reproduce this on my machine is to checkout the sources for [Sodium](https://github.com/CaffeineMC/sodium-fabric/tree/1.19.4/dev) and then try to run the `./gradlew build` task after clearing the `~/.gradle/caches` directory. This almost never works and ends up getting stuck on `:downloadAssets`, where it will take 20-30 minutes to get past whatever files it is stuck on, before resuming normally.

On occasion, it seems to spit out the following network error for every file it was stuck on, which then halts the build immediately:

```
A problem occurred configuring root project 'sodium-fabric'.
> Could not resolve all files for configuration ':minecraftLibraries'.
   > Could not resolve com.mojang:authlib:3.17.30.
     Required by:
         project :
      > Could not resolve com.mojang:authlib:3.17.30.
         > Could not get resource 'https://libraries.minecraft.net/com/mojang/authlib/3.17.30/authlib-3.17.30.pom'.
            > Could not GET 'https://libraries.minecraft.net/com/mojang/authlib/3.17.30/authlib-3.17.30.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.6/userguide/build_environment.html#gradle_system_properties
                  > Remote host terminated the handshake
```

While it's easy to think that this is a problem with my specific computer or network connection, it is reproducible on _any_ Linux machine that I have access to, even when using a VPN or a different network entirely (including cellular hotspot.)  But I've never been able to reproduce it on a Windows machine.
 
The only consistent thing about this issue is that Loom will usually log the following warnings before it hangs:

```
Forcing downloading $HOME/.gradle/caches/fabric-loom/assets/objects/a0/a0d43b09bbd3a65039e074cf4699175b0c4724b8 as existing lock file was found. This may happen if the gradle build was forcefully canceled.
```

This doesn't make a lot of sense to me, because stopping all the daemons and deleting the `~/.gradle/caches` directory should also purge any file locks that Loom has created. The only way I could see Loom encountering lock files during a clean build would be if it's downloading the same file multiple times, but I don't know how Loom internals work.

I've tried to collect whatever other diagnostic information below, but due to the nature of the problem, it's very hard to debug. Any help in resolving this would be appreciated. I can provide additional information upon request.

#### TCP connection state
```
$ netstat -nat
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address     Foreign Address         State      
tcp        0      0 <local>:49624     99.84.238.118:443       TIME_WAIT  
tcp        0      0 <local>:55620     104.18.11.207:443       TIME_WAIT  
tcp        0      0 <local>:57446     108.138.239.54:443      TIME_WAIT  
tcp        0      0 <local>:44402     99.84.238.135:443       TIME_WAIT  
tcp        0      0 <local>:57430     108.138.239.54:443      TIME_WAIT  
tcp        0      0 <local>:40612     162.159.135.234:443     TIME_WAIT  
tcp        0      0 <local>:57432     108.138.239.54:443      TIME_WAIT  
```

#### Thread dump
```
$ jstack <pid>
"HttpClient-38-SelectorManager" #495 daemon prio=5 os_prio=0 cpu=1.31ms elapsed=303.92s tid=0x00007fa15800b470 nid=0x56dbd runnable  [0x00007fa11e3fe000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPoll.wait(java.base@17.0.6/Native Method)
        at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@17.0.6/EPollSelectorImpl.java:118)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@17.0.6/SelectorImpl.java:129)
        - locked <0x0000000089638278> (a sun.nio.ch.Util$2)
        - locked <0x0000000089638228> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(java.base@17.0.6/SelectorImpl.java:141)
        at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(java.net.http@17.0.6/HttpClientImpl.java:889)

(repeated once for every HttpClient thread...)
```

**Comment by modmuss50** [comment]
Hi, Thanks for opening an issue hopefully we can get to the bottom of this. I have created a Fedora 36 VM, and I am able to download the assets without issue. We also download the assets regually using Ubuntu running on Github Actions (Loom tests, and Fabric API's client tests) without issue.

I know it sounds silly but can you confirm that are able to download the assets in the vanilla Minecraft launcher, there is an open issue about this: https://bugs.mojang.com/browse/MCL-23025 However I believe this issue was resolved server side as it also affected loom on all platforms, and I havent seen anyone having issues for a few weeks.

Another thing worth playing around with is the number of threads used to download the files (add to build.gradle):

```gradle
afterEvaluate {
   downloadAssets {
      downloadThreads = 4
   }
}
```

Currently this defaults to [Runtime.getRuntime().availableProcessors()](https://github.com/FabricMC/fabric-loom/blob/dev/1.2/src/main/java/net/fabricmc/loom/task/DownloadAssetsTask.java#L74) on some systems this is likely way too high. (If that helps its easy enough to set a max, mabye 8?)

> On occasion, it seems to spit out the following network error for every file it was stuck on, which then halts the build immediately:

This error shown above is coming from Gradle's dependency resolver and is **not** using Loom's downloader, making me even more skeptical about this being a loom issue.

> The only consistent thing about this issue is that Loom will usually log the following warnings before it hangs:

Loom retries the downloads 3 times, this log message is bit misleading as its finding the reminents of the previously failed download. The thread dump is also deep inside Java's HTTP client and doesnt seem to point to anything too useful.

If anyone else has network issues with loom plesae let me know, hopefully we can figure this out.

**Comment by jellysquid3** [comment]
> I know it sounds silly but can you confirm that are able to download the assets in the vanilla Minecraft launcher, there is an open issue about this...

Using either the Minecraft launcher or Prism Launcher doesn't show any issues. The assets download in <30 seconds and make good use of my network connection. It's also worth noting that it's not just asset download which suffers from this problem, as libraries from `maven.fabricmc.net` can be extremely slow to fetch as well. This can actually be seen in the `netstat` dump from above, as connections for two different CDNs (Cloudfront and Cloudflare) are both in the frozen state.

> The thread dump is also deep inside Java's HTTP client and doesnt seem to point to anything too useful.

I was able to enable `-Djdk.internal.httpclient.debug=true` to get some logs out of it, but it doesn't show much useful. It seems to be getting stuck in TLS negotiation rather than the actual content download. However, there's no way that a HTTP server is keeping a socket open for 700+ seconds in a wait state, and the Linux kernel seems ready to close the connection as well... my guess is that the response is already in the socket's buffer and it's just not getting polled correctly.

> Another thing worth playing around with is the number of threads used to download the files (add to build.gradle):

I'll give this a try and report back.

**Comment by jellysquid3** [comment]
Trying to adjust the number of download threads seems to make the problem dramatically worse.

At 4 threads, it takes multiple attempts to get Gradle to download all the files, and (as expected) it's much slower to download everything.

At 1 thread, it seems to hang on every other file, with there being minutes of inactivity between each fetch. I haven't actually managed to get Gradle to download all the files. 

I don't know what to make out of this. Nothing seems strange about what Gradle or Loom is doing. This really looks like a bug in the JDK's HttpClient implementation to me.

**Comment by jellysquid3** [comment]
I've also tried to upgrade to the latest version of Gradle 8.1.1, Loom 1.2.5, and OpenJDK 20.0.0, but it doesn't seem to make any difference.

**Comment by modmuss50** [comment]
> It's also worth noting that it's not just asset download which suffers from this problem.

Ok, thats good to know as it basically rules out any issues with Mojang's CDN.

> I really don't know what to make out of this. This seems like a bug in the JDK's HttpClient implementation to me.

Yeah, I'm as lost as you are. Its possible that Gradle is running the JVM with some funky args/putting the http client into a weird state?

Could be worth creating a very basic Java application to download a file using the HttpClient to see if you can reproduce it without the complexity of Gradle. If that works try doing the same from a gradle build script (maybe with and without loom?) would be intresting. 

You have already mentioned that you have tried multiple machines, so that rules out any possible network card/driver issues as I have personally had issues with some network cards.

**Comment by mjwells2002** [comment]
I think i have found the source of this issue, HTTPClient instances are not re-used, meaning the threads are not re-used and connections are left hanging, as can be seen here 
![image](https://user-images.githubusercontent.com/36360408/235520164-72851eab-2760-475f-89ec-9125a779c18a.png)

i wrote and tested a small code change to fix this, and on my system i see the downloadAssets task takes ~2x less time to run, (~23s, from 44s) and there are not thousands of threads created
![image](https://user-images.githubusercontent.com/36360408/235520336-ae11e9d5-5b55-4183-8173-8d9280505c84.png)

as soon as the automated tests pass i will create a PR with these changes

**Comment by modmuss50** [comment]
Ahh, great spot @mjwells2002 It does seem that the java HttpClient creates a new ThreadPool with no way to close it once complete. Either making the http client static (making sure it can still handle all the threads needed for download assets), or passing a custom (single thread executor?) to each new client and gracefully shutting that down should help.

This still does not fully explain the issues with downloads handled by Gradle, or why it only causes issues on Linux, but should be a great help.

**Comment by mjwells2002** [comment]
Some additonal info, i did run into an issue with it freezing like jellysquid described on MacOS, i also noted that exactly one time while testing the original behaviour, i was seemingly blocked from accessing resources.download.minecraft.net, as downloads started to fail with a 401 error, this resolved itself a few moments later, im guessing this was some form of rate limit

**Comment by jellysquid3** [comment]
For what it's worth, Loom 1.2.7 appears to resolve the issue on my machines. Though I'm encountering a new issue as described in #883 that seems to be a result of these changes.
