### ISSUE TITLE
Integration tests locally often fail with download errors

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#878]
> DownloadException: Download file (*minecraft-info.json or some asset*) may have been modified

Deleting `.gradle/test-files` fixes the issues for a while, but I've had these errors happen twice now.

**Comment by modmuss50** [comment]
Yeah, this is an easy fix. Just need to remove: https://github.com/FabricMC/fabric-loom/blob/dcbdbf0e302fee9745bb8b0db14d627a64a8b968/src/main/java/net/fabricmc/loom/util/download/Download.java#L314-L318

The assumption that this should never happen is wrong, as the minecraft launcher meta does change (When Mojang updates it).
