### ISSUE TITLE
Included dependencies are in every jar

### ISSUE THREAD

**Issue by Pyrofab** [FabricMC/fabric-loom#88]
If a project has multiple source sets, the included dependencies will be jar-in-jar'd in every built artifact. This could be solved by adding source set specific configurations like for `compile` (`apiInclude`, `include`, `testInclude`...).

**Comment by Pyrofab** [comment]
Actually, it seems that the behaviour can be configured per remap task. Loom really needs documentation =)

**Comment by asiekierka** [comment]
Yes, it just changed in Loom 0.2.3. Now, only the default 'remapJar' task will include all nested dependencies, and you can set "addNestedDependencies" otherwise.

**Comment by Pyrofab** [comment]
I would do another suggestion then: allow the nesting to take any configuration, so we can easily have different nested dependencies per artifact.
