### ISSUE TITLE
How do i update gradle on my project?

### ISSUE THREAD

**Issue by LordEnder-Kitty** [FabricMC/fabric-loom#884]
not really an issue, more like just a question, how do you update the gradle version of a project so that i can update the loom version?
i use IntelliJ IDEA Community btw.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
