### ISSUE TITLE
Use of reproducibleFileOrder produces invalid jars

### ISSUE THREAD

**Issue by lukebemish** [FabricMC/fabric-loom#885]
Java expects a manifest in a jar to be the first or second zip entry. For example: https://github.com/openjdk/jdk17u/blob/aa8c46ca52c2f983470ab4c05e64c1ae85aa3b8e/src/java.base/share/classes/java/util/jar/JarInputStream.java#L78-L85
Currently, something is off with loom's remap jar tasks; while when used with `reproducibleFileOrder = false` they seem to maintain the file order they were given, with the manifest first as it was in the pre-remapping jar, if `reproducibleFileOrder` on the task is set to `true`, then the special ordering with the manifest first is destroyed, producing a jar which may cause strange behavior. For a simple reproduction case, see https://github.com/lukebemish/loom-jar-ordering-demo

**Comment by lukebemish** [comment]
I think a good question here is: does the remapped jar have a guarantee to have the same file order as the pre-remapping jar? Because if so, then I don't even need to set that option on that task. However, it's not obvious to me that that is necessarily true across systems or whatever, so some guarantee of that would be useful

**Comment by modmuss50** [comment]
Where does this cause an issue? As Fabric API has had this enabled for a long while now? https://github.com/FabricMC/fabric/blob/a37e8e70b73d4283ebd6081921fb32b9fb61e7b1/build.gradle#L240-L243 Or does tasks.withType not work as I expect?

**Comment by lukebemish** [comment]
If you are consuming the produced jars with some external tool (in my case, something that runs on our maven server), this external tool assumes stuff is a valid jar. If it is using OpenJDK, OpenJDK's implementation of `JarInputStream` (linked in my original comment) assumes that a manifest is the first or second entry of a jar file. `remapJar` with `reproducibleFileOrder` set to true can (and sometimes does!) produce jars where this is not the case

**Comment by lukebemish** [comment]
This does not seem to be the case for fabric api - I would guess that the ordering is redone when the jar is signed to put the manifest first

**Comment by modmuss50** [comment]
Ah ok, that makes sense. I was wondering why we had not seen any issues before. The solution to this issue is to just sort the manifest first. Here: https://github.com/FabricMC/fabric-loom/blob/dev/1.2/src/main/java/net/fabricmc/loom/util/ZipReprocessorUtil.java#L57
