### ISSUE TITLE
Fabric fails to re-download version_manifest.json resulting in failed build snapshot versions

### ISSUE THREAD

**Issue by baka4n** [FabricMC/fabric-loom#896]
minecraft:1.20-rc1
yarn:1.20-rc1+build.2

result:
Occasionally caused by the inability to update automatically, the current solution is to delete version_manifest.json in the gradle directory of fabric-loom to solve the problem, hoping to fix it sooner

**Comment by modmuss50** [comment]
Duplicate of https://github.com/FabricMC/fabric-loom/issues/886

Thanks for the issue 👍
