### ISSUE TITLE
[Suggestion] Allow registering LibraryProcessor in LibraryProcessorManager

### ISSUE THREAD

**Issue by thecatcore** [FabricMC/fabric-loom#904]
I wanted to register a LibraryProcessor from another gradle plugin but I can't because the list of Processor is [private](https://github.com/FabricMC/fabric-loom/blob/dev/1.2/src/main/java/net/fabricmc/loom/configuration/providers/minecraft/library/LibraryProcessorManager.java#L46).

**Comment by modmuss50** [comment]
Moving this to an official/supported API is out of scope I think. However id be happy to open up the internals a bit to at least make it possible, but with no guarentee of API stability.

The ordering can be imporant, is this something you will need contol over?

**Comment by thecatcore** [comment]
Thx, I'll probably prefer my processors to be run last I guess.

**Comment by modmuss50** [comment]
Ok, cool. What is you usecase? knowing that might help me when figuring this out.

**Comment by thecatcore** [comment]
I'm replacing LWJGL 2 with my fork of it, only at runtime is necessary.

**Comment by thecatcore** [comment]
See Legacy Looming: https://github.com/Legacy-Fabric/legacy-looming

**Comment by modmuss50** [comment]
This was done
