### ISSUE TITLE
suggest about loom:injected_interfaces

### ISSUE THREAD

**Issue by baka4n** [FabricMC/fabric-loom#908]
I think it is also possible to implement loom:injected_interfaces for mod dependencies, which reduces a lot of forced transfer costs

**Comment by baka4n** [comment]
The way it was changed so that loom:injected_interfaces supports mod injection

**Comment by modmuss50** [comment]
I dont think this is really necessary, I think its best we keep injected interfaces to only target Minecraft for now.
