### ISSUE TITLE
Loom should put mappings with the autogenerated names on the classpath

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-loom#91]
The yarn names on the class path do not have the auto generated names, this is a bit of a pain

**Comment by Chocohead** [comment]
This would also have to change in the installer if it was done to remain consistent between dev and prod. Might be easier to apply to Yarn's exports.

**Comment by modmuss50** [comment]
I think the idea is to move yarn names out of prod so this wouldnt be an issue there.

**Comment by Chocohead** [comment]
I guess if it switched to just the intermediary mappings in prod that'd work too. Would remain strange that Stitch was always run over the Yarn exports rather than the exports having it pre-applied.

**Comment by modmuss50** [comment]
This has been fixed.
