### ISSUE TITLE
Reproducible ZIP timestamps are dependent on machine timezone

### ISSUE THREAD

**Issue by LostLuma** [FabricMC/fabric-loom#926]
Currently when building with reproducibility enabled the timestamps inside the archive are dependent on the timezone of the machine building the mod. This diverges from the way Gradle itself handles this, as it always outputs a consistent timestamp of `1980-02-01 00:00`, regardless of build environment (at least from my testing).

A few examples obtained using `unzip -v modid-1.0.0.jar` on the example mod built in different environments:

Built via GHA, where I assume the machine time zone is UTC:
```sh
Archive:  modid-1.0.0-actions-build.jar
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     208  Defl:N      148  29% 1980-02-01 01:00 ba7d7dad  modid.mixins.json
```
And from building the exact same commit on my local machine (currently CEST?):
```sh
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     208  Defl:N      148  29% 1980-02-01 00:00 ba7d7dad  modid.mixins.json
```

I assume this is a difference in how timestamps are handled by Java's built in ZIP-related library and the apache compress library which is used by Gradle instead, since the constant timestamp used is exactly the same.

**Comment by modmuss50** [comment]
Humm, intresting I thought I copied the code used by gradle 🤔 

See: https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipCopyAction.java#L41-L56
and
https://github.com/FabricMC/fabric-loom/blob/dev/1.3/src/main/java/net/fabricmc/loom/util/ZipReprocessorUtil.java#L42-L45

**Comment by LostLuma** [comment]
The timestamp that piece of code generates is identical, however Gradle uses the `apache-commons-compress` library to construct the archive ([and it also sets the exact same file flags regardless of operating system!](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipCopyAction.java#L120)) while Loom uses java's built-in zip library. The resulting timestamp in the archive is thus different with Loom (as well as the file flags if built on a different operating system).

**Comment by modmuss50** [comment]
Ah, I see thats a little bit silly how they differ. I will have to take a deeper dive into Java's zip library to see if there is a way around this, id prefer not to use a 3rd party lib if we can help it.

**Comment by LostLuma** [comment]
Good luck! I tried around with that a bit because I wanted to submit a PR to fix this originally but didn't end up anywhere sadly, and was unsure whether introducing another dependency would be wanted.

**Comment by modmuss50** [comment]
Another option might be to look into seeing if its possible to use the gradle API to do this. Worse case we can add another dependency, it just seems a bit silly to need it for this.
