### ISSUE TITLE
Make fabric.loom.multiProjectOptimisation named fabric.loom.multiProjectOptimization because it’s best to use US English

### ISSUE THREAD

**Issue by mrjasonn** [FabricMC/fabric-loom#927]
Make fabric.loom.multiProjectOptimisation named fabric.loom.multiProjectOptimization because it’s best to use US English as by default Minecraft Java uses that.

**Comment by modmuss50** [comment]
At best I might make it accpet both, otherwise Im not too bothered.

**Comment by modmuss50** [comment]
After no deliberation I dont see a need in changing this.

Its an advanced option, used by few who copy/paste it from the wiki and forget about it.
