### ISSUE TITLE
Multi-project project fails to sync when loom is used 

### ISSUE THREAD

**Issue by douzooo** [FabricMC/fabric-loom#928]
Im currently trying to setup legcy fabric and this error cameup using the mod template,  https://pastebin.com/h1eLWDv8

https://github.com/NebulaBuilds/NebulaClient/
here is my project

**Comment by Juuxel** [comment]
You are mixing two different versions of Loom in the same project hierarchy which messes up the classloader. You can instead declare the Loom plugin dependency in the root project with `apply false`:
```gradle
plugins {
  id 'fabric-loom' version '1.3-SNAPSHOT' apply false
}
```
and use it without a manually specified version in subprojects:
```gradle
plugins {
  id 'fabric-loom'
}
```

**Comment by douzooo** [comment]
Thank you that fixed my issue, I've already seen something like this but didn't quiet understood what to do. I wish you a great day / night
