### ISSUE TITLE
Feature: Ability to inject interfaces with generic types

### ISSUE THREAD

**Issue by TropheusJ** [FabricMC/fabric-loom#932]
Injected interfaces can only be the raw type, no generics. 
I wanted to add a `getNullable` to `DefaultedRegistry<T>`, by injecting `DefaultedRegistryExtensions<T>`. However, this is not possible, and only a raw type can be injected. This makes the method only return `Object`, which kind of ruins it.

**Comment by modmuss50** [comment]
The plan was to handle this with classtweaker.

**Comment by modmuss50** [comment]
Duplicate of #597
