### ISSUE TITLE
Loom 1.2+ incompatible with gradle ran on Java 19 

### ISSUE THREAD

**Issue by wefhy** [FabricMC/fabric-loom#933]
Projects using Loom 1.2+ can't be built if the gradle instance is run with Java 19 (or maybe also other versions)
I tested it to fail with:
 - openjdk 19.0.1 for apple silicon (ran inside intellij 2023.1 as well as intellij 2023.2)
 - adoptium 19.0.2+7 for ubuntu (ran on github worker)

Repeatable build result is available here: https://github.com/wefhy/WhyMap/actions/runs/5614704019/job/15213382809

```
 * What went wrong:
A problem occurred configuring root project 'WhyMap'.
> Failed to setup Minecraft, java.lang.IllegalStateException: Cannot mutate content repository descriptor 'LoomLocalRemappedMods(file:/home/runner/work/WhyMap/WhyMap/.gradle/loom-cache/remapped_mods/)' after repository has been used
```

Full stacktrace: https://gist.github.com/wefhy/d809fa3402af004ed67fc85f821d3656

problematic commit: https://github.com/wefhy/WhyMap/commit/b7ba2e736f3ca63f56af568bd56845ca042bdb7d

build goes through on java 17: https://github.com/wefhy/WhyMap/actions/runs/5612855162/job/15207551200
(I mean it would go through if the java code was correct but I mean it doesn't fail before even starting compilation)
build fails on java 19: https://github.com/wefhy/WhyMap/actions/runs/5614704019/job/15213382809

The loom-cache/remapped_mods folder mentioned in error is empty

Loom 1.1.14 and earlier seems to work correctly with java 17 and 19
Loom 1.2.7 and 1.3.8 work only with java 17

Note: I wasn't able to recreate the issue on another project (minihud fork) https://github.com/wefhy/purityhud/actions/runs/5614613165/job/15213119055

First way to recreate the issue is to run the abovementioned github worker
Second way to recreate the issue is to open project in intellij 2023.1, open gradle settings and set Gradle JVM to OpenJDK version 19.0.1 then try to reimport the project 
Probably more ways to recreate exist

**Comment by wefhy** [comment]
Thanks to modmuss help
The issue lays in https://github.com/wefhy/WhyMap/blob/master/build.gradle.kts#L128
`from(extraLibs.resolve().map { if (it.isDirectory) it else zipTree(it) })`
Me trying to pack ktor networking library into my mod
So there is some regression between loom 1.1 and 1.2 in this regard but looks like it's also me doing gradle wizardry.
modmuss suggestion was to replace it with `configurations.named("extraLibs").map { it.resolve().map { if (it.isDirectory) it else zipTree(it) } }`
which does work as a workaround for me

Even if it's not something worth fixing on the loom side, would be good if it gave me more meaningful error

**Comment by modmuss50** [comment]
I dont think there is much that I can do to fix this, it will work when you are using Java 17, or when LWJGL is updated in vanilla to support Java 19+.
