### ISSUE TITLE
Zip entry timestamps in output of `remapJar` depend on timezone

### ISSUE THREAD

**Issue by Johni0702** [FabricMC/fabric-loom#942]
https://github.com/FabricMC/fabric-loom/blob/ffc786d3cd4b6835196a3f8945d01119fcd0ac16/src/main/java/net/fabricmc/loom/util/ZipReprocessorUtil.java#L175-L179

To reproduce:
```bash
$ git clone https://github.com/FabricMC/fabric-example-mod/
$ cd fabric-example-mod
$ TZ=America/New_York ./gradlew --no-daemon clean build
$ TZ=UTC zipinfo -v build/libs/modid-1.0.0.jar modid.mixins.json
...
  file last modified on (DOS date/time):          1980 Feb 1 00:00:00
  file last modified on (UT extra field modtime): 1980 Feb 1 05:00:00 local
  file last modified on (UT extra field modtime): 1980 Feb 1 05:00:00 UTC
...
$ TZ=Japan ./gradlew --no-daemon clean build
$ TZ=UTC zipinfo -v build/libs/modid-1.0.0.jar modid.mixins.json
...
  file last modified on (DOS date/time):          1980 Feb 1 00:00:00
  file last modified on (UT extra field modtime): 1980 Jan 31 15:00:00 local
  file last modified on (UT extra field modtime): 1980 Jan 31 15:00:00 UTC
...
```

Conceptually this is because `setLastModifiedTime` and `setLastAccessTime` store the timezone offset in the file.
The details are a bit backwards: `CONSTANT_TIME_FOR_ZIP_ENTRIES` is not globally constant but rather the epoch time of local 1980 Feb 1 00:00:00, i.e. it varies by timezone. `setTime` will then convert that epoch time to "dos time" by pulling out the local timezone again, and as a result the actual value that will be stored for the dos time in the file is always 0 (conceptually anyway, in reality it's a constant non-0 value that I have not bothered computing). The other two values are stored in UTC, so when the magic not-actually-constant is passed into them, no conversion (or at most a fixed offset) is necessary because `FileTime` already represents a UTC epoch time, and as such the not-actually-constant magic constant becomes part of the zip file.

I believe fixing this should be as simple as dropping the two latter methods. The only thing which `ZipOutputStream` fills in with the current time is the dos time, so only that needs to be set. The other two fields are skipped and not written out if they weren't set.

**Comment by Juuxel** [comment]
Is this a duplicate of #926?

**Comment by Johni0702** [comment]
Ah, yes, I believe it is.
