### ISSUE TITLE
Could not match Kotlin version after Kotlin 1.9.0

### ISSUE THREAD

**Issue by xiguajerry** [FabricMC/fabric-loom#943]
The version of kotlin gradle plugin after 1.9.0 cannot be matched with the current pattern. The version now looks like "1.9.0-release-358"

**Comment by modmuss50** [comment]
What loom version are you using? I thought I fixed this in 1.3

**Comment by xiguajerry** [comment]
Sorry I didn't see the update. I checked the code right now :)
