### ISSUE TITLE
A utility for configuring data generation should be added

### ISSUE THREAD

**Issue by haykam821** [FabricMC/fabric-loom#959]
As per [Discord discussion](https://discord.com/channels/507304429255393322/592749519171616796/1161325248487100416), some syntax for configuring the data generation resources directory, run configuration, and source set would be useful:

```gradle
loom {
	configureDataGeneration()
}
```

In addition, this utility could exclude the `.cache` directory which breaks build reproducibility.

**Comment by modmuss50** [comment]
This was done :)
