### ISSUE TITLE
devlibs configuration should use a lazy provider

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-loom#970]
<https://github.com/FabricMC/fabric-loom/blob/710644129810dbefbb79c0b37781fd2bb3ed77cd/src/main/java/net/fabricmc/loom/task/RemapTaskConfiguration.java#L95>
This should probably use some kind of Provider - `buildDir` can be changed with a setter. That property has also been deprecated and replaced with a DirectoryProperty in [the `ProjectLayout` itf](https://docs.gradle.org/current/javadoc/org/gradle/api/file/ProjectLayout.html#getBuildDirectory--), so that makes a provider an even better fit.

**Comment by modmuss50** [comment]
This was done.
