### ISSUE TITLE
Ints that fit into 16 bits decompiled as chars

### ISSUE THREAD

**Issue by ChloeDawn** [FabricMC/fabric-loom#99]
Ints are being decompiled as chars in some places where they fit into 16 bits. Ideally, they should be represented in hex, but they definitely shouldn't be represented as chars.

Example from `GameRenderer#renderWeather`:
```java
int int_18 = int_17 >> 16 & '\uffff';
int int_19 = int_17 & '\uffff';
```
These should be `0xFFFF` ideally, or `65535` as a raw value.

**Comment by asiekierka** [comment]
IIRC, the thing is that you can't clearly tell apart 16-bit integer constants from char constants at the bytecode level.

**Comment by ChloeDawn** [comment]
If it's being used for a bit op you can probably safely assume it's not supposed to be a char.

```
ILOAD 41
BIPUSH 16
ISHR
LDC 65535
IAND
ISTORE 42
```

**Comment by Runemoro** [comment]
It's not even a short. `LDC` can only load ints, not shorts. There would have to be an `I2S` to make it a short (which couldn't even be used for `IAND`).

**Comment by ChloeDawn** [comment]
Ticket name updated, I named it poorly

**Comment by modmuss50** [comment]
This is a decompiler issue, not a loom issue.
