### ISSUE TITLE
Mixin Refmap json not being added to jar on MacOS

### ISSUE THREAD

**Issue by JT122406** [FabricMC/fabric-loom#995]
When building on loom refmap mixin file doesn't get added to jar this seems to only happen on mac as using the exact same repo and building on my PC this doesn't happen.

**Comment by modmuss50** [comment]
What loom version, can you provide the log as well please? Are you also able to reproduce this with the example mod?

**Comment by JT122406** [comment]
Loom 1.4, Gradle 8.4 and 8.5, I can reproduce with other mods but can try with the example mod and get back to you

**Comment by JT122406** [comment]
Log from current mod:
https://paste.gg/p/anonymous/a8669ae2983944e2aaabd20fd66750be

**Comment by JT122406** [comment]
So far I am unable to reproduce with example mod

**Comment by modmuss50** [comment]
I use MacOS and have had no issues with any mods, have you got a simple project that I can try to reproduce this issue with?

**Comment by JT122406** [comment]
For some reason it seems to be happening randomly so im gonna close this as I assume it's a gradle daemon issue since now sometimes my runs gen the file others don't so either that or a configuration issue.
