### ISSUE TITLE
invalid function

### ISSUE THREAD

**Issue by xkeksi** [FabricMC/fabric-loom#996]
G:\Gradle\caches\fabric-loom\version_manifest.json -> G:\Gradle\caches\fabric-loom\version_manifest.json.part: invalid function

 problem occurred configuring root project 'AdvancedME'.
> Failed to notify project evaluation listener.
   > Failed to setup Minecraft, java.io.UncheckedIOException: Failed download after 3 attempts
   > Failed download after 3 attempts

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

any fix? i tried to rebuild/reload my project

**Comment by xkeksi** [comment]
nice iq hardcoding C: drive for fabric loom hope ur project dies faster than thought 

fixed by moving gradle to C: 
🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒 🐒

**Comment by xkeksi** [comment]
hardcoder skill issuee

**Comment by xkeksi** [comment]
[[insert fabric loom devteam jokes]]

**Comment by modmuss50** [comment]
I could have helped you, but it seems you dont want the help I guess.
