### ISSUE TITLE
The problem with the classloader

### ISSUE THREAD

**Issue by Av0kee** [FabricMC/fabric-loom#998]
Hello, when I launch minecraft, this error comes out https://haste.gravitlauncher.com/018c5b92-bf87-7004-a6f6-1be58b738a4a As I found out, the problem is loading classes. Is it possible to isolate them somehow? Link to the full logs: https://haste.gravitlauncher.com/018c5b92-bf87-7004-a6f6-1be58b738a4a

**Comment by Linguardium** [comment]
also not a loom issue.
